// Generated by osury - Nullable type for JSON null values
// This is option<T> internally but maps to T | null in TypeScript via shim
@genType.import(("./Nullable.shim.ts", "t"))
type t<'a> = option<'a>
