// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "sury/src/S.res.mjs";

let adsExecutiveSummaryResponseSchemaSchema = S.schema(s => ({
  _tag: s.m(S.option(S.literal("AdsExecutiveSummaryResponseSchema"))),
  ad_sales: s.m(S.option(S.float)),
  ad_spend: s.m(S.option(S.float)),
  ad_impressions: s.m(S.option(S.float)),
  ad_ctr: s.m(S.option(S.float)),
  ad_clicks: s.m(S.option(S.float)),
  ad_cvr: s.m(S.option(S.float)),
  ad_orders: s.m(S.option(S.float)),
  ad_units_sold: s.m(S.option(S.float)),
  acos: s.m(S.option(S.float)),
  roas: s.m(S.option(S.float)),
  cpc: s.m(S.option(S.float)),
  cpm: s.m(S.option(S.float)),
  time_in_budget: s.m(S.option(S.float)),
  ad_tos_is: s.m(S.option(S.float)),
  ads_non_optimal_spend: s.m(S.option(S.float))
}));

let attributionExecutiveSummaryResponseSchemaSchema = S.schema(s => ({
  _tag: s.m(S.option(S.literal("AttributionExecutiveSummaryResponseSchema"))),
  attribution_sales: s.m(S.option(S.float)),
  attribution_spend: s.m(S.option(S.float)),
  attribution_impressions: s.m(S.option(S.float)),
  attribution_ctr: s.m(S.option(S.float)),
  attribution_clicks: s.m(S.option(S.float)),
  attribution_cvr: s.m(S.option(S.float)),
  attribution_orders: s.m(S.option(S.float)),
  attribution_units_sold: s.m(S.option(S.float)),
  attribution_acos: s.m(S.option(S.float)),
  attribution_roas: s.m(S.option(S.float)),
  attribution_cpc: s.m(S.option(S.float)),
  attribution_cpm: s.m(S.option(S.float))
}));

let cFOExecutiveSummaryResponseSchemaSchema = S.schema(s => ({
  _tag: s.m(S.option(S.literal("CFOExecutiveSummaryResponseSchema"))),
  available_capital: s.m(S.option(S.float)),
  frozen_capital: s.m(S.option(S.float)),
  borrowed_capital: s.m(S.option(S.float)),
  gross_profit: s.m(S.option(S.float)),
  gross_margin: s.m(S.option(S.float)),
  contribution_profit: s.m(S.option(S.float)),
  contribution_margin: s.m(S.option(S.float)),
  net_profit: s.m(S.option(S.float)),
  net_margin: s.m(S.option(S.float)),
  opex: s.m(S.option(S.float)),
  roi: s.m(S.option(S.float)),
  cost_of_goods_sold: s.m(S.float),
  amazon_fees: s.m(S.float)
}));

let dailyInventoryMetricsSchema = S.schema(s => ({
  date: s.m(S.string),
  available_stock: s.m(S.float),
  in_transit: s.m(S.float),
  receiving: s.m(S.float),
  safety_stock: s.m(S.float),
  total_available: s.m(S.float),
  total_units_sold_30d: s.m(S.float),
  doi_available: s.m(S.float),
  total_doi: s.m(S.float)
}));

let forecastParamsSchema = S.schema(s => ({
  impressions_what_if: s.m(S.option(S.float)),
  clicks_what_if: s.m(S.option(S.float)),
  orders_what_if: s.m(S.option(S.float)),
  units_sold_what_if: s.m(S.option(S.float)),
  sales_what_if: s.m(S.option(S.float)),
  ad_spend_what_if: s.m(S.option(S.float)),
  ad_impressions_what_if: s.m(S.option(S.float)),
  ad_clicks_what_if: s.m(S.option(S.float)),
  ad_orders_what_if: s.m(S.option(S.float)),
  ad_sales_what_if: s.m(S.option(S.float)),
  ad_units_sold_what_if: s.m(S.option(S.float)),
  ad_ctr_what_if: s.m(S.option(S.float)),
  ad_cvr_what_if: s.m(S.option(S.float)),
  cpc_what_if: s.m(S.option(S.float)),
  cpm_what_if: s.m(S.option(S.float)),
  organic_impressions_what_if: s.m(S.option(S.float)),
  organic_clicks_what_if: s.m(S.option(S.float)),
  organic_orders_what_if: s.m(S.option(S.float)),
  organic_sales_what_if: s.m(S.option(S.float)),
  organic_units_sold_what_if: s.m(S.option(S.float)),
  total_sales_what_if: s.m(S.option(S.float)),
  total_spend_what_if: s.m(S.option(S.float)),
  total_impressions_what_if: s.m(S.option(S.float)),
  total_clicks_what_if: s.m(S.option(S.float)),
  total_orders_what_if: s.m(S.option(S.float)),
  total_units_sold_what_if: s.m(S.option(S.float)),
  lost_sales_what_if: s.m(S.option(S.float)),
  ctr_what_if: s.m(S.option(S.float)),
  cvr_what_if: s.m(S.option(S.float)),
  acos_what_if: s.m(S.option(S.float)),
  tacos_what_if: s.m(S.option(S.float)),
  roas_what_if: s.m(S.option(S.float)),
  mer_what_if: s.m(S.option(S.float)),
  aov_what_if: s.m(S.option(S.float)),
  gross_profit_what_if: s.m(S.option(S.float)),
  gross_margin_what_if: s.m(S.option(S.float)),
  contribution_profit_what_if: s.m(S.option(S.float)),
  contribution_margin_what_if: s.m(S.option(S.float)),
  net_profit_what_if: s.m(S.option(S.float)),
  net_margin_what_if: s.m(S.option(S.float)),
  roi_what_if: s.m(S.option(S.float)),
  available_capital_what_if: s.m(S.option(S.float)),
  frozen_capital_what_if: s.m(S.option(S.float)),
  ebitda_what_if: s.m(S.option(S.float)),
  cogs_what_if: s.m(S.option(S.float)),
  cost_of_goods_sold_what_if: s.m(S.option(S.float)),
  amazon_fees_what_if: s.m(S.option(S.float)),
  opex_what_if: s.m(S.option(S.float)),
  discount_what_if: s.m(S.option(S.float)),
  coupon_what_if: s.m(S.option(S.float)),
  subscribe_save_what_if: s.m(S.option(S.float)),
  text_score_what_if: s.m(S.option(S.float)),
  image_score_what_if: s.m(S.option(S.float)),
  video_score_what_if: s.m(S.option(S.float)),
  a_plus_score_what_if: s.m(S.option(S.float)),
  fba_in_stock_rate_what_if: s.m(S.option(S.float)),
  inventory_turnover_what_if: s.m(S.option(S.float)),
  safety_stock_what_if: s.m(S.option(S.float)),
  storage_costs_what_if: s.m(S.option(S.float)),
  shipping_costs_what_if: s.m(S.option(S.float)),
  market_total_sales_what_if: s.m(S.option(S.float)),
  brand_market_share_what_if: s.m(S.option(S.float)),
  market_average_price_what_if: s.m(S.option(S.float)),
  attribution_sales_what_if: s.m(S.option(S.float)),
  attribution_spend_what_if: s.m(S.option(S.float)),
  attribution_impressions_what_if: s.m(S.option(S.float)),
  attribution_clicks_what_if: s.m(S.option(S.float)),
  attribution_orders_what_if: s.m(S.option(S.float)),
  attribution_units_sold_what_if: s.m(S.option(S.float)),
  attribution_ctr_what_if: s.m(S.option(S.float)),
  attribution_cvr_what_if: s.m(S.option(S.float)),
  attribution_acos_what_if: s.m(S.option(S.float)),
  attribution_roas_what_if: s.m(S.option(S.float)),
  attribution_cpc_what_if: s.m(S.option(S.float)),
  attribution_cpm_what_if: s.m(S.option(S.float))
}));

let insightResponseSchema = S.schema(s => ({
  _tag: s.m(S.option(S.literal("InsightResponse"))),
  summary: s.m(S.string),
  date_start: s.m(S.string),
  date_end: s.m(S.string),
  asin: s.m(S.option(S.string)),
  agent: s.m(S.string)
}));

let inventoryExecutiveSummaryResponseSchemaSchema = S.schema(s => ({
  _tag: s.m(S.option(S.literal("InventoryExecutiveSummaryResponseSchema"))),
  fba_in_stock_rate: s.m(S.option(S.float)),
  fbt_in_stock_rate: s.m(S.option(S.float)),
  three_pl_in_stock_rate: s.m(S.option(S.float)),
  storage_costs: s.m(S.option(S.float)),
  shipping_costs: s.m(S.option(S.float)),
  forecasting_accuracy: s.m(S.option(S.float)),
  inventory_turnover: s.m(S.option(S.float)),
  safety_stock: s.m(S.option(S.float)),
  doi_available: s.m(S.option(S.float)),
  total_doi: s.m(S.option(S.float)),
  estimated_stock_out_date: s.m(S.option(S.string))
}));

let marketIntelligenceExecutiveSummaryResponseSchemaSchema = S.schema(s => ({
  _tag: s.m(S.option(S.literal("MarketIntelligenceExecutiveSummaryResponseSchema"))),
  market_total_sales: s.m(S.option(S.float)),
  brand_market_share: s.m(S.option(S.float)),
  market_average_price: s.m(S.option(S.float)),
  market_total_units_sold: s.m(S.option(S.float)),
  market_asin_count: s.m(S.option(S.int)),
  market_promotion_value: s.m(S.option(S.float)),
  market_promotion_count: s.m(S.option(S.int)),
  market_review_score: s.m(S.option(S.float)),
  market_pos: s.m(S.option(S.float)),
  market_ad_spend: s.m(S.option(S.float))
}));

let organicExecutiveSummaryResponseSchemaSchema = S.schema(s => ({
  _tag: s.m(S.option(S.literal("OrganicExecutiveSummaryResponseSchema"))),
  organic_sales: s.m(S.float),
  organic_impressions: s.m(S.option(S.float)),
  organic_ctr: s.m(S.option(S.float)),
  organic_clicks: s.m(S.float),
  organic_cvr: s.m(S.float),
  organic_orders: s.m(S.float),
  organic_units_sold: s.m(S.float)
}));

let strategicPlanResponseSchema = S.schema(s => ({
  _tag: s.m(S.option(S.literal("StrategicPlanResponse"))),
  plan: s.m(S.string),
  forecast_period: s.m(S.string),
  projected_total_sales: s.m(S.float),
  projected_net_profit: s.m(S.float),
  projected_gross_profit: s.m(S.float),
  projected_roi: s.m(S.float),
  total_sales_diff_pct: s.m(S.option(S.float)),
  net_profit_diff_pct: s.m(S.option(S.float)),
  gross_profit_diff_pct: s.m(S.option(S.float)),
  roi_diff_pct: s.m(S.option(S.float)),
  goals: s.m(S.option(S.array(S.dict(S.string)))),
  asin: s.m(S.option(S.string))
}));

let totalExecutiveSummaryResponseSchemaSchema = S.schema(s => ({
  _tag: s.m(S.option(S.literal("TotalExecutiveSummaryResponseSchema"))),
  total_sales: s.m(S.option(S.float)),
  total_spend: s.m(S.option(S.float)),
  total_impressions: s.m(S.option(S.float)),
  ctr: s.m(S.option(S.float)),
  total_clicks: s.m(S.option(S.float)),
  cvr: s.m(S.option(S.float)),
  total_orders: s.m(S.option(S.float)),
  total_units_sold: s.m(S.option(S.float)),
  total_ntb_orders: s.m(S.option(S.float)),
  tacos: s.m(S.option(S.float)),
  mer: s.m(S.option(S.float)),
  lost_sales: s.m(S.option(S.float))
}));

let totalInventoryMetricsSchema = S.schema(s => ({
  available_stock: s.m(S.float),
  in_transit: s.m(S.float),
  receiving: s.m(S.float),
  safety_stock: s.m(S.float),
  total_available: s.m(S.float),
  total_units_sold_30d: s.m(S.float),
  doi_available: s.m(S.float),
  total_doi: s.m(S.float)
}));

let whatifAppliedEntrySchema = S.schema(s => ({
  current_value: s.m(S.option(S.float)),
  percentage_change: s.m(S.float),
  target_value: s.m(S.option(S.float))
}));

let whatifModelInfoSchema = S.schema(s => ({
  metrics_count: s.m(S.int),
  correlations_count: s.m(S.int),
  data_points: s.m(S.int)
}));

let adsExecutiveSummaryWithForecastBreakdownSchema = S.schema(s => ({
  _tag: s.m(S.option(S.literal("AdsExecutiveSummaryWithForecastBreakdown"))),
  ad_sales: s.m(S.option(S.float)),
  ad_spend: s.m(S.option(S.float)),
  ad_impressions: s.m(S.option(S.float)),
  ad_ctr: s.m(S.option(S.float)),
  ad_clicks: s.m(S.option(S.float)),
  ad_cvr: s.m(S.option(S.float)),
  ad_orders: s.m(S.option(S.float)),
  ad_units_sold: s.m(S.option(S.float)),
  acos: s.m(S.option(S.float)),
  roas: s.m(S.option(S.float)),
  cpc: s.m(S.option(S.float)),
  cpm: s.m(S.option(S.float)),
  time_in_budget: s.m(S.option(S.float)),
  ad_tos_is: s.m(S.option(S.float)),
  ads_non_optimal_spend: s.m(S.option(S.float)),
  real: s.m(adsExecutiveSummaryResponseSchemaSchema),
  forecasted: s.m(adsExecutiveSummaryResponseSchemaSchema)
}));

let attributionExecutiveSummaryWithForecastBreakdownSchema = S.schema(s => ({
  _tag: s.m(S.option(S.literal("AttributionExecutiveSummaryWithForecastBreakdown"))),
  attribution_sales: s.m(S.option(S.float)),
  attribution_spend: s.m(S.option(S.float)),
  attribution_impressions: s.m(S.option(S.float)),
  attribution_ctr: s.m(S.option(S.float)),
  attribution_clicks: s.m(S.option(S.float)),
  attribution_cvr: s.m(S.option(S.float)),
  attribution_orders: s.m(S.option(S.float)),
  attribution_units_sold: s.m(S.option(S.float)),
  attribution_acos: s.m(S.option(S.float)),
  attribution_roas: s.m(S.option(S.float)),
  attribution_cpc: s.m(S.option(S.float)),
  attribution_cpm: s.m(S.option(S.float)),
  real: s.m(attributionExecutiveSummaryResponseSchemaSchema),
  forecasted: s.m(attributionExecutiveSummaryResponseSchemaSchema)
}));

let cFOExecutiveSummaryWithForecastBreakdownSchema = S.schema(s => ({
  _tag: s.m(S.option(S.literal("CFOExecutiveSummaryWithForecastBreakdown"))),
  available_capital: s.m(S.option(S.float)),
  frozen_capital: s.m(S.option(S.float)),
  borrowed_capital: s.m(S.option(S.float)),
  gross_profit: s.m(S.option(S.float)),
  gross_margin: s.m(S.option(S.float)),
  contribution_profit: s.m(S.option(S.float)),
  contribution_margin: s.m(S.option(S.float)),
  net_profit: s.m(S.option(S.float)),
  net_margin: s.m(S.option(S.float)),
  opex: s.m(S.option(S.float)),
  roi: s.m(S.option(S.float)),
  cost_of_goods_sold: s.m(S.float),
  amazon_fees: s.m(S.float),
  real: s.m(cFOExecutiveSummaryResponseSchemaSchema),
  forecasted: s.m(cFOExecutiveSummaryResponseSchemaSchema)
}));

let tierLevelForecastParamsSchema = S.schema(s => ({
  impressions_what_if: s.m(S.option(S.float)),
  clicks_what_if: s.m(S.option(S.float)),
  orders_what_if: s.m(S.option(S.float)),
  units_sold_what_if: s.m(S.option(S.float)),
  sales_what_if: s.m(S.option(S.float)),
  ad_spend_what_if: s.m(S.option(S.float)),
  ad_impressions_what_if: s.m(S.option(S.float)),
  ad_clicks_what_if: s.m(S.option(S.float)),
  ad_orders_what_if: s.m(S.option(S.float)),
  ad_sales_what_if: s.m(S.option(S.float)),
  ad_units_sold_what_if: s.m(S.option(S.float)),
  ad_ctr_what_if: s.m(S.option(S.float)),
  ad_cvr_what_if: s.m(S.option(S.float)),
  cpc_what_if: s.m(S.option(S.float)),
  cpm_what_if: s.m(S.option(S.float)),
  organic_impressions_what_if: s.m(S.option(S.float)),
  organic_clicks_what_if: s.m(S.option(S.float)),
  organic_orders_what_if: s.m(S.option(S.float)),
  organic_sales_what_if: s.m(S.option(S.float)),
  organic_units_sold_what_if: s.m(S.option(S.float)),
  total_sales_what_if: s.m(S.option(S.float)),
  total_spend_what_if: s.m(S.option(S.float)),
  total_impressions_what_if: s.m(S.option(S.float)),
  total_clicks_what_if: s.m(S.option(S.float)),
  total_orders_what_if: s.m(S.option(S.float)),
  total_units_sold_what_if: s.m(S.option(S.float)),
  lost_sales_what_if: s.m(S.option(S.float)),
  ctr_what_if: s.m(S.option(S.float)),
  cvr_what_if: s.m(S.option(S.float)),
  acos_what_if: s.m(S.option(S.float)),
  tacos_what_if: s.m(S.option(S.float)),
  roas_what_if: s.m(S.option(S.float)),
  mer_what_if: s.m(S.option(S.float)),
  aov_what_if: s.m(S.option(S.float)),
  gross_profit_what_if: s.m(S.option(S.float)),
  gross_margin_what_if: s.m(S.option(S.float)),
  contribution_profit_what_if: s.m(S.option(S.float)),
  contribution_margin_what_if: s.m(S.option(S.float)),
  net_profit_what_if: s.m(S.option(S.float)),
  net_margin_what_if: s.m(S.option(S.float)),
  roi_what_if: s.m(S.option(S.float)),
  available_capital_what_if: s.m(S.option(S.float)),
  frozen_capital_what_if: s.m(S.option(S.float)),
  ebitda_what_if: s.m(S.option(S.float)),
  cogs_what_if: s.m(S.option(S.float)),
  cost_of_goods_sold_what_if: s.m(S.option(S.float)),
  amazon_fees_what_if: s.m(S.option(S.float)),
  opex_what_if: s.m(S.option(S.float)),
  discount_what_if: s.m(S.option(S.float)),
  coupon_what_if: s.m(S.option(S.float)),
  subscribe_save_what_if: s.m(S.option(S.float)),
  text_score_what_if: s.m(S.option(S.float)),
  image_score_what_if: s.m(S.option(S.float)),
  video_score_what_if: s.m(S.option(S.float)),
  a_plus_score_what_if: s.m(S.option(S.float)),
  fba_in_stock_rate_what_if: s.m(S.option(S.float)),
  inventory_turnover_what_if: s.m(S.option(S.float)),
  safety_stock_what_if: s.m(S.option(S.float)),
  storage_costs_what_if: s.m(S.option(S.float)),
  shipping_costs_what_if: s.m(S.option(S.float)),
  market_total_sales_what_if: s.m(S.option(S.float)),
  brand_market_share_what_if: s.m(S.option(S.float)),
  market_average_price_what_if: s.m(S.option(S.float)),
  attribution_sales_what_if: s.m(S.option(S.float)),
  attribution_spend_what_if: s.m(S.option(S.float)),
  attribution_impressions_what_if: s.m(S.option(S.float)),
  attribution_clicks_what_if: s.m(S.option(S.float)),
  attribution_orders_what_if: s.m(S.option(S.float)),
  attribution_units_sold_what_if: s.m(S.option(S.float)),
  attribution_ctr_what_if: s.m(S.option(S.float)),
  attribution_cvr_what_if: s.m(S.option(S.float)),
  attribution_acos_what_if: s.m(S.option(S.float)),
  attribution_roas_what_if: s.m(S.option(S.float)),
  attribution_cpc_what_if: s.m(S.option(S.float)),
  attribution_cpm_what_if: s.m(S.option(S.float)),
  no_sales: s.m(S.option(forecastParamsSchema)),
  poor: s.m(S.option(forecastParamsSchema)),
  mid: s.m(S.option(forecastParamsSchema)),
  good: s.m(S.option(forecastParamsSchema))
}));

let inventoryExecutiveSummaryWithForecastBreakdownSchema = S.schema(s => ({
  _tag: s.m(S.option(S.literal("InventoryExecutiveSummaryWithForecastBreakdown"))),
  fba_in_stock_rate: s.m(S.option(S.float)),
  fbt_in_stock_rate: s.m(S.option(S.float)),
  three_pl_in_stock_rate: s.m(S.option(S.float)),
  storage_costs: s.m(S.option(S.float)),
  shipping_costs: s.m(S.option(S.float)),
  forecasting_accuracy: s.m(S.option(S.float)),
  inventory_turnover: s.m(S.option(S.float)),
  safety_stock: s.m(S.option(S.float)),
  doi_available: s.m(S.option(S.float)),
  total_doi: s.m(S.option(S.float)),
  estimated_stock_out_date: s.m(S.option(S.string)),
  real: s.m(inventoryExecutiveSummaryResponseSchemaSchema),
  forecasted: s.m(inventoryExecutiveSummaryResponseSchemaSchema)
}));

let marketIntelligenceExecutiveSummaryWithForecastBreakdownSchema = S.schema(s => ({
  _tag: s.m(S.option(S.literal("MarketIntelligenceExecutiveSummaryWithForecastBreakdown"))),
  market_total_sales: s.m(S.option(S.float)),
  brand_market_share: s.m(S.option(S.float)),
  market_average_price: s.m(S.option(S.float)),
  market_total_units_sold: s.m(S.option(S.float)),
  market_asin_count: s.m(S.option(S.int)),
  market_promotion_value: s.m(S.option(S.float)),
  market_promotion_count: s.m(S.option(S.int)),
  market_review_score: s.m(S.option(S.float)),
  market_pos: s.m(S.option(S.float)),
  market_ad_spend: s.m(S.option(S.float)),
  real: s.m(marketIntelligenceExecutiveSummaryResponseSchemaSchema),
  forecasted: s.m(marketIntelligenceExecutiveSummaryResponseSchemaSchema)
}));

let organicExecutiveSummaryWithForecastBreakdownSchema = S.schema(s => ({
  _tag: s.m(S.option(S.literal("OrganicExecutiveSummaryWithForecastBreakdown"))),
  organic_sales: s.m(S.float),
  organic_impressions: s.m(S.option(S.float)),
  organic_ctr: s.m(S.option(S.float)),
  organic_clicks: s.m(S.float),
  organic_cvr: s.m(S.float),
  organic_orders: s.m(S.float),
  organic_units_sold: s.m(S.float),
  real: s.m(organicExecutiveSummaryResponseSchemaSchema),
  forecasted: s.m(organicExecutiveSummaryResponseSchemaSchema)
}));

let totalExecutiveSummaryWithForecastBreakdownSchema = S.schema(s => ({
  _tag: s.m(S.option(S.literal("TotalExecutiveSummaryWithForecastBreakdown"))),
  total_sales: s.m(S.option(S.float)),
  total_spend: s.m(S.option(S.float)),
  total_impressions: s.m(S.option(S.float)),
  ctr: s.m(S.option(S.float)),
  total_clicks: s.m(S.option(S.float)),
  cvr: s.m(S.option(S.float)),
  total_orders: s.m(S.option(S.float)),
  total_units_sold: s.m(S.option(S.float)),
  total_ntb_orders: s.m(S.option(S.float)),
  tacos: s.m(S.option(S.float)),
  mer: s.m(S.option(S.float)),
  lost_sales: s.m(S.option(S.float)),
  real: s.m(totalExecutiveSummaryResponseSchemaSchema),
  forecasted: s.m(totalExecutiveSummaryResponseSchemaSchema)
}));

let inventoryMetricsResponseSchema = S.schema(s => ({
  _tag: s.m(S.option(S.literal("InventoryMetricsResponse"))),
  daily_metrics: s.m(S.array(dailyInventoryMetricsSchema)),
  total_metrics: s.m(totalInventoryMetricsSchema)
}));

export {
  adsExecutiveSummaryResponseSchemaSchema,
  attributionExecutiveSummaryResponseSchemaSchema,
  cFOExecutiveSummaryResponseSchemaSchema,
  dailyInventoryMetricsSchema,
  forecastParamsSchema,
  insightResponseSchema,
  inventoryExecutiveSummaryResponseSchemaSchema,
  marketIntelligenceExecutiveSummaryResponseSchemaSchema,
  organicExecutiveSummaryResponseSchemaSchema,
  strategicPlanResponseSchema,
  totalExecutiveSummaryResponseSchemaSchema,
  totalInventoryMetricsSchema,
  whatifAppliedEntrySchema,
  whatifModelInfoSchema,
  adsExecutiveSummaryWithForecastBreakdownSchema,
  attributionExecutiveSummaryWithForecastBreakdownSchema,
  cFOExecutiveSummaryWithForecastBreakdownSchema,
  tierLevelForecastParamsSchema,
  inventoryExecutiveSummaryWithForecastBreakdownSchema,
  marketIntelligenceExecutiveSummaryWithForecastBreakdownSchema,
  organicExecutiveSummaryWithForecastBreakdownSchema,
  totalExecutiveSummaryWithForecastBreakdownSchema,
  inventoryMetricsResponseSchema,
}
/* adsExecutiveSummaryResponseSchemaSchema Not a pure module */
