// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "sury/src/S.res.mjs";

let floatOrDictSchema = S.union([
  S.schema(s => ({
    _tag: "Float",
    _0: s.m(S.float)
  })),
  S.schema(s => ({
    _tag: "Dict",
    _0: s.m(S.dict(S.string))
  }))
]);

let stringOrIntSchema = S.union([
  S.schema(s => ({
    _tag: "String",
    _0: s.m(S.string)
  })),
  S.schema(s => ({
    _tag: "Int",
    _0: s.m(S.int)
  }))
]);

let adsExecutiveSummaryResponseSchemaSchema = S.schema(s => ({
  ad_sales: s.m(S.float),
  ad_spend: s.m(S.float),
  ad_impressions: s.m(S.float),
  ad_ctr: s.m(S.option(S.float)),
  ad_clicks: s.m(S.float),
  ad_cvr: s.m(S.option(S.float)),
  ad_orders: s.m(S.float),
  ad_units_sold: s.m(S.float),
  acos: s.m(S.option(S.float)),
  roas: s.m(S.option(S.float)),
  cpc: s.m(S.option(S.float)),
  cpm: s.m(S.option(S.float)),
  time_in_budget: s.m(S.option(S.float)),
  ad_tos_is: s.m(S.option(S.float)),
  ads_non_optimal_spend: s.m(S.option(S.float))
}));

let attributionExecutiveSummaryResponseSchemaSchema = S.schema(s => ({
  attribution_sales: s.m(S.option(S.float)),
  attribution_spend: s.m(S.option(S.float)),
  attribution_impressions: s.m(S.option(S.float)),
  attribution_ctr: s.m(S.option(S.float)),
  attribution_clicks: s.m(S.option(S.float)),
  attribution_cvr: s.m(S.option(S.float)),
  attribution_orders: s.m(S.option(S.float)),
  attribution_units_sold: s.m(S.option(S.float)),
  attribution_acos: s.m(S.option(S.float)),
  attribution_roas: s.m(S.option(S.float)),
  attribution_cpc: s.m(S.option(S.float)),
  attribution_cpm: s.m(S.option(S.float))
}));

let cFOExecutiveSummaryResponseSchemaSchema = S.schema(s => ({
  available_capital: s.m(S.option(S.float)),
  frozen_capital: s.m(S.option(S.float)),
  borrowed_capital: s.m(S.option(S.float)),
  gross_profit: s.m(S.option(S.float)),
  gross_margin: s.m(S.option(S.float)),
  contribution_profit: s.m(S.option(S.float)),
  contribution_margin: s.m(S.option(S.float)),
  net_profit: s.m(S.option(S.float)),
  net_margin: s.m(S.option(S.float)),
  opex: s.m(S.option(S.float)),
  roi: s.m(S.option(S.float)),
  cost_of_goods_sold: s.m(S.float),
  amazon_fees: s.m(S.float)
}));

let dailyInventoryMetricsSchema = S.schema(s => ({
  date: s.m(S.string),
  available_stock: s.m(S.float),
  in_transit: s.m(S.float),
  receiving: s.m(S.float),
  safety_stock: s.m(S.float),
  total_available: s.m(S.float),
  total_units_sold_30d: s.m(S.float),
  doi_available: s.m(S.float),
  total_doi: s.m(S.float)
}));

let forecastParamsSchema = S.schema(s => ({
  impressions_what_if: s.m(S.option(S.float)),
  clicks_what_if: s.m(S.option(S.float)),
  orders_what_if: s.m(S.option(S.float)),
  units_sold_what_if: s.m(S.option(S.float)),
  sales_what_if: s.m(S.option(S.float)),
  ad_spend_what_if: s.m(S.option(S.float)),
  ad_impressions_what_if: s.m(S.option(S.float)),
  ad_clicks_what_if: s.m(S.option(S.float)),
  ad_orders_what_if: s.m(S.option(S.float)),
  ad_sales_what_if: s.m(S.option(S.float)),
  ad_units_sold_what_if: s.m(S.option(S.float)),
  ad_ctr_what_if: s.m(S.option(S.float)),
  ad_cvr_what_if: s.m(S.option(S.float)),
  cpc_what_if: s.m(S.option(S.float)),
  cpm_what_if: s.m(S.option(S.float)),
  organic_impressions_what_if: s.m(S.option(S.float)),
  organic_clicks_what_if: s.m(S.option(S.float)),
  organic_orders_what_if: s.m(S.option(S.float)),
  organic_sales_what_if: s.m(S.option(S.float)),
  organic_units_sold_what_if: s.m(S.option(S.float)),
  total_sales_what_if: s.m(S.option(S.float)),
  total_spend_what_if: s.m(S.option(S.float)),
  total_impressions_what_if: s.m(S.option(S.float)),
  total_clicks_what_if: s.m(S.option(S.float)),
  total_orders_what_if: s.m(S.option(S.float)),
  total_units_sold_what_if: s.m(S.option(S.float)),
  lost_sales_what_if: s.m(S.option(S.float)),
  ctr_what_if: s.m(S.option(S.float)),
  cvr_what_if: s.m(S.option(S.float)),
  acos_what_if: s.m(S.option(S.float)),
  tacos_what_if: s.m(S.option(S.float)),
  roas_what_if: s.m(S.option(S.float)),
  mer_what_if: s.m(S.option(S.float)),
  aov_what_if: s.m(S.option(S.float)),
  gross_profit_what_if: s.m(S.option(S.float)),
  gross_margin_what_if: s.m(S.option(S.float)),
  contribution_profit_what_if: s.m(S.option(S.float)),
  contribution_margin_what_if: s.m(S.option(S.float)),
  net_profit_what_if: s.m(S.option(S.float)),
  net_margin_what_if: s.m(S.option(S.float)),
  roi_what_if: s.m(S.option(S.float)),
  available_capital_what_if: s.m(S.option(S.float)),
  frozen_capital_what_if: s.m(S.option(S.float)),
  ebitda_what_if: s.m(S.option(S.float)),
  cogs_what_if: s.m(S.option(S.float)),
  cost_of_goods_sold_what_if: s.m(S.option(S.float)),
  amazon_fees_what_if: s.m(S.option(S.float)),
  opex_what_if: s.m(S.option(S.float)),
  discount_what_if: s.m(S.option(S.float)),
  coupon_what_if: s.m(S.option(S.float)),
  subscribe_save_what_if: s.m(S.option(S.float)),
  text_score_what_if: s.m(S.option(S.float)),
  image_score_what_if: s.m(S.option(S.float)),
  video_score_what_if: s.m(S.option(S.float)),
  a_plus_score_what_if: s.m(S.option(S.float)),
  fba_in_stock_rate_what_if: s.m(S.option(S.float)),
  inventory_turnover_what_if: s.m(S.option(S.float)),
  safety_stock_what_if: s.m(S.option(S.float)),
  storage_costs_what_if: s.m(S.option(S.float)),
  shipping_costs_what_if: s.m(S.option(S.float)),
  market_total_sales_what_if: s.m(S.option(S.float)),
  brand_market_share_what_if: s.m(S.option(S.float)),
  market_average_price_what_if: s.m(S.option(S.float)),
  attribution_sales_what_if: s.m(S.option(S.float)),
  attribution_spend_what_if: s.m(S.option(S.float)),
  attribution_impressions_what_if: s.m(S.option(S.float)),
  attribution_clicks_what_if: s.m(S.option(S.float)),
  attribution_orders_what_if: s.m(S.option(S.float)),
  attribution_units_sold_what_if: s.m(S.option(S.float)),
  attribution_ctr_what_if: s.m(S.option(S.float)),
  attribution_cvr_what_if: s.m(S.option(S.float)),
  attribution_acos_what_if: s.m(S.option(S.float)),
  attribution_roas_what_if: s.m(S.option(S.float)),
  attribution_cpc_what_if: s.m(S.option(S.float)),
  attribution_cpm_what_if: s.m(S.option(S.float))
}));

let insightResponseSchema = S.schema(s => ({
  summary: s.m(S.string),
  date_start: s.m(S.string),
  date_end: s.m(S.string),
  asin: s.m(S.option(S.string)),
  agent: s.m(S.string)
}));

let inventoryExecutiveSummaryResponseSchemaSchema = S.schema(s => ({
  fba_in_stock_rate: s.m(S.option(S.float)),
  fbt_in_stock_rate: s.m(S.option(S.float)),
  three_pl_in_stock_rate: s.m(S.option(S.float)),
  storage_costs: s.m(S.option(S.float)),
  shipping_costs: s.m(S.option(S.float)),
  forecasting_accuracy: s.m(S.option(S.float)),
  inventory_turnover: s.m(S.option(S.float)),
  safety_stock: s.m(S.option(S.float)),
  doi_available: s.m(S.option(S.float)),
  total_doi: s.m(S.option(S.float)),
  estimated_stock_out_date: s.m(S.option(S.string))
}));

let marketIntelligenceExecutiveSummaryResponseSchemaSchema = S.schema(s => ({
  market_total_sales: s.m(S.option(S.float)),
  brand_market_share: s.m(S.option(S.float)),
  market_average_price: s.m(S.option(S.float)),
  market_total_units_sold: s.m(S.option(S.float)),
  market_asin_count: s.m(S.option(S.int)),
  market_promotion_value: s.m(S.option(S.float)),
  market_promotion_count: s.m(S.option(S.int)),
  market_review_score: s.m(S.option(S.float)),
  market_pos: s.m(S.option(S.float)),
  market_ad_spend: s.m(S.option(S.float))
}));

let organicExecutiveSummaryResponseSchemaSchema = S.schema(s => ({
  organic_sales: s.m(S.float),
  organic_impressions: s.m(S.option(S.float)),
  organic_ctr: s.m(S.option(S.float)),
  organic_clicks: s.m(S.float),
  organic_cvr: s.m(S.float),
  organic_orders: s.m(S.float),
  organic_units_sold: s.m(S.float)
}));

let strategicPlanResponseSchema = S.schema(s => ({
  plan: s.m(S.string),
  forecast_period: s.m(S.string),
  projected_total_sales: s.m(S.float),
  projected_net_profit: s.m(S.float),
  projected_gross_profit: s.m(S.float),
  projected_roi: s.m(S.float),
  total_sales_diff_pct: s.m(S.option(S.float)),
  net_profit_diff_pct: s.m(S.option(S.float)),
  gross_profit_diff_pct: s.m(S.option(S.float)),
  roi_diff_pct: s.m(S.option(S.float)),
  goals: s.m(S.option(S.array(S.dict(S.string)))),
  asin: s.m(S.option(S.string))
}));

let totalExecutiveSummaryResponseSchemaSchema = S.schema(s => ({
  total_sales: s.m(S.option(S.float)),
  total_spend: s.m(S.option(S.float)),
  total_impressions: s.m(S.option(S.float)),
  ctr: s.m(S.option(S.float)),
  total_clicks: s.m(S.option(S.float)),
  cvr: s.m(S.option(S.float)),
  total_orders: s.m(S.option(S.float)),
  total_units_sold: s.m(S.option(S.float)),
  total_ntb_orders: s.m(S.option(S.float)),
  tacos: s.m(S.option(S.float)),
  mer: s.m(S.option(S.float)),
  lost_sales: s.m(S.option(S.float))
}));

let totalInventoryMetricsSchema = S.schema(s => ({
  available_stock: s.m(S.float),
  in_transit: s.m(S.float),
  receiving: s.m(S.float),
  safety_stock: s.m(S.float),
  total_available: s.m(S.float),
  total_units_sold_30d: s.m(S.float),
  doi_available: s.m(S.float),
  total_doi: s.m(S.float)
}));

let whatifAppliedEntrySchema = S.schema(s => ({
  current_value: s.m(S.option(S.float)),
  percentage_change: s.m(S.float),
  target_value: s.m(S.option(S.float))
}));

let whatifModelInfoSchema = S.schema(s => ({
  metrics_count: s.m(S.int),
  correlations_count: s.m(S.int),
  data_points: s.m(S.int)
}));

let timelineDataPoint_dict_Schema = S.schema(s => ({
  period_start: s.m(S.string),
  period_end: s.m(S.string),
  is_forecast: s.m(S.bool),
  value: s.m(S.dict(S.string)),
  compare_value: s.m(S.option(S.dict(S.string))),
  compare_diff: s.m(S.option(S.dict(S.string))),
  compare_percent_diff: s.m(S.option(floatOrDictSchema))
}));

let validationErrorSchema = S.schema(s => ({
  loc: s.m(S.array(stringOrIntSchema)),
  msg: s.m(S.string),
  type: s.m(S.string)
}));

let adsExecutiveSummaryWithForecastBreakdownSchema = S.schema(s => ({
  ad_sales: s.m(S.float),
  ad_spend: s.m(S.float),
  ad_impressions: s.m(S.float),
  ad_ctr: s.m(S.option(S.float)),
  ad_clicks: s.m(S.float),
  ad_cvr: s.m(S.option(S.float)),
  ad_orders: s.m(S.float),
  ad_units_sold: s.m(S.float),
  acos: s.m(S.option(S.float)),
  roas: s.m(S.option(S.float)),
  cpc: s.m(S.option(S.float)),
  cpm: s.m(S.option(S.float)),
  time_in_budget: s.m(S.option(S.float)),
  ad_tos_is: s.m(S.option(S.float)),
  ads_non_optimal_spend: s.m(S.option(S.float)),
  real: s.m(adsExecutiveSummaryResponseSchemaSchema),
  forecasted: s.m(adsExecutiveSummaryResponseSchemaSchema)
}));

let timelineDataPoint_AdsExecutiveSummaryResponseSchema_Schema = S.schema(s => ({
  period_start: s.m(S.string),
  period_end: s.m(S.string),
  is_forecast: s.m(S.bool),
  value: s.m(adsExecutiveSummaryResponseSchemaSchema),
  compare_value: s.m(S.option(adsExecutiveSummaryResponseSchemaSchema)),
  compare_diff: s.m(S.option(adsExecutiveSummaryResponseSchemaSchema)),
  compare_percent_diff: s.m(S.option(floatOrDictSchema))
}));

let whatifTimelineDataPoint_AdsExecutiveSummaryResponseSchema_Schema = S.schema(s => ({
  period_start: s.m(S.string),
  period_end: s.m(S.string),
  is_forecast: s.m(S.bool),
  baseline: s.m(adsExecutiveSummaryResponseSchemaSchema),
  projected: s.m(S.option(adsExecutiveSummaryResponseSchemaSchema)),
  diff: s.m(S.option(adsExecutiveSummaryResponseSchemaSchema)),
  percent_diff: s.m(S.option(floatOrDictSchema)),
  compare_value: s.m(S.option(adsExecutiveSummaryResponseSchemaSchema)),
  compare_diff: s.m(S.option(adsExecutiveSummaryResponseSchemaSchema)),
  compare_percent_diff: s.m(S.option(floatOrDictSchema))
}));

let attributionExecutiveSummaryWithForecastBreakdownSchema = S.schema(s => ({
  attribution_sales: s.m(S.option(S.float)),
  attribution_spend: s.m(S.option(S.float)),
  attribution_impressions: s.m(S.option(S.float)),
  attribution_ctr: s.m(S.option(S.float)),
  attribution_clicks: s.m(S.option(S.float)),
  attribution_cvr: s.m(S.option(S.float)),
  attribution_orders: s.m(S.option(S.float)),
  attribution_units_sold: s.m(S.option(S.float)),
  attribution_acos: s.m(S.option(S.float)),
  attribution_roas: s.m(S.option(S.float)),
  attribution_cpc: s.m(S.option(S.float)),
  attribution_cpm: s.m(S.option(S.float)),
  real: s.m(attributionExecutiveSummaryResponseSchemaSchema),
  forecasted: s.m(attributionExecutiveSummaryResponseSchemaSchema)
}));

let timelineDataPoint_AttributionExecutiveSummaryResponseSchema_Schema = S.schema(s => ({
  period_start: s.m(S.string),
  period_end: s.m(S.string),
  is_forecast: s.m(S.bool),
  value: s.m(attributionExecutiveSummaryResponseSchemaSchema),
  compare_value: s.m(S.option(attributionExecutiveSummaryResponseSchemaSchema)),
  compare_diff: s.m(S.option(attributionExecutiveSummaryResponseSchemaSchema)),
  compare_percent_diff: s.m(S.option(floatOrDictSchema))
}));

let whatifTimelineDataPoint_AttributionExecutiveSummaryResponseSchema_Schema = S.schema(s => ({
  period_start: s.m(S.string),
  period_end: s.m(S.string),
  is_forecast: s.m(S.bool),
  baseline: s.m(attributionExecutiveSummaryResponseSchemaSchema),
  projected: s.m(S.option(attributionExecutiveSummaryResponseSchemaSchema)),
  diff: s.m(S.option(attributionExecutiveSummaryResponseSchemaSchema)),
  percent_diff: s.m(S.option(floatOrDictSchema)),
  compare_value: s.m(S.option(attributionExecutiveSummaryResponseSchemaSchema)),
  compare_diff: s.m(S.option(attributionExecutiveSummaryResponseSchemaSchema)),
  compare_percent_diff: s.m(S.option(floatOrDictSchema))
}));

let cFOExecutiveSummaryWithForecastBreakdownSchema = S.schema(s => ({
  available_capital: s.m(S.option(S.float)),
  frozen_capital: s.m(S.option(S.float)),
  borrowed_capital: s.m(S.option(S.float)),
  gross_profit: s.m(S.option(S.float)),
  gross_margin: s.m(S.option(S.float)),
  contribution_profit: s.m(S.option(S.float)),
  contribution_margin: s.m(S.option(S.float)),
  net_profit: s.m(S.option(S.float)),
  net_margin: s.m(S.option(S.float)),
  opex: s.m(S.option(S.float)),
  roi: s.m(S.option(S.float)),
  cost_of_goods_sold: s.m(S.float),
  amazon_fees: s.m(S.float),
  real: s.m(cFOExecutiveSummaryResponseSchemaSchema),
  forecasted: s.m(cFOExecutiveSummaryResponseSchemaSchema)
}));

let timelineDataPoint_CFOExecutiveSummaryResponseSchema_Schema = S.schema(s => ({
  period_start: s.m(S.string),
  period_end: s.m(S.string),
  is_forecast: s.m(S.bool),
  value: s.m(cFOExecutiveSummaryResponseSchemaSchema),
  compare_value: s.m(S.option(cFOExecutiveSummaryResponseSchemaSchema)),
  compare_diff: s.m(S.option(cFOExecutiveSummaryResponseSchemaSchema)),
  compare_percent_diff: s.m(S.option(floatOrDictSchema))
}));

let whatifTimelineDataPoint_CFOExecutiveSummaryResponseSchema_Schema = S.schema(s => ({
  period_start: s.m(S.string),
  period_end: s.m(S.string),
  is_forecast: s.m(S.bool),
  baseline: s.m(cFOExecutiveSummaryResponseSchemaSchema),
  projected: s.m(S.option(cFOExecutiveSummaryResponseSchemaSchema)),
  diff: s.m(S.option(cFOExecutiveSummaryResponseSchemaSchema)),
  percent_diff: s.m(S.option(floatOrDictSchema)),
  compare_value: s.m(S.option(cFOExecutiveSummaryResponseSchemaSchema)),
  compare_diff: s.m(S.option(cFOExecutiveSummaryResponseSchemaSchema)),
  compare_percent_diff: s.m(S.option(floatOrDictSchema))
}));

let tierLevelForecastParamsSchema = S.schema(s => ({
  impressions_what_if: s.m(S.option(S.float)),
  clicks_what_if: s.m(S.option(S.float)),
  orders_what_if: s.m(S.option(S.float)),
  units_sold_what_if: s.m(S.option(S.float)),
  sales_what_if: s.m(S.option(S.float)),
  ad_spend_what_if: s.m(S.option(S.float)),
  ad_impressions_what_if: s.m(S.option(S.float)),
  ad_clicks_what_if: s.m(S.option(S.float)),
  ad_orders_what_if: s.m(S.option(S.float)),
  ad_sales_what_if: s.m(S.option(S.float)),
  ad_units_sold_what_if: s.m(S.option(S.float)),
  ad_ctr_what_if: s.m(S.option(S.float)),
  ad_cvr_what_if: s.m(S.option(S.float)),
  cpc_what_if: s.m(S.option(S.float)),
  cpm_what_if: s.m(S.option(S.float)),
  organic_impressions_what_if: s.m(S.option(S.float)),
  organic_clicks_what_if: s.m(S.option(S.float)),
  organic_orders_what_if: s.m(S.option(S.float)),
  organic_sales_what_if: s.m(S.option(S.float)),
  organic_units_sold_what_if: s.m(S.option(S.float)),
  total_sales_what_if: s.m(S.option(S.float)),
  total_spend_what_if: s.m(S.option(S.float)),
  total_impressions_what_if: s.m(S.option(S.float)),
  total_clicks_what_if: s.m(S.option(S.float)),
  total_orders_what_if: s.m(S.option(S.float)),
  total_units_sold_what_if: s.m(S.option(S.float)),
  lost_sales_what_if: s.m(S.option(S.float)),
  ctr_what_if: s.m(S.option(S.float)),
  cvr_what_if: s.m(S.option(S.float)),
  acos_what_if: s.m(S.option(S.float)),
  tacos_what_if: s.m(S.option(S.float)),
  roas_what_if: s.m(S.option(S.float)),
  mer_what_if: s.m(S.option(S.float)),
  aov_what_if: s.m(S.option(S.float)),
  gross_profit_what_if: s.m(S.option(S.float)),
  gross_margin_what_if: s.m(S.option(S.float)),
  contribution_profit_what_if: s.m(S.option(S.float)),
  contribution_margin_what_if: s.m(S.option(S.float)),
  net_profit_what_if: s.m(S.option(S.float)),
  net_margin_what_if: s.m(S.option(S.float)),
  roi_what_if: s.m(S.option(S.float)),
  available_capital_what_if: s.m(S.option(S.float)),
  frozen_capital_what_if: s.m(S.option(S.float)),
  ebitda_what_if: s.m(S.option(S.float)),
  cogs_what_if: s.m(S.option(S.float)),
  cost_of_goods_sold_what_if: s.m(S.option(S.float)),
  amazon_fees_what_if: s.m(S.option(S.float)),
  opex_what_if: s.m(S.option(S.float)),
  discount_what_if: s.m(S.option(S.float)),
  coupon_what_if: s.m(S.option(S.float)),
  subscribe_save_what_if: s.m(S.option(S.float)),
  text_score_what_if: s.m(S.option(S.float)),
  image_score_what_if: s.m(S.option(S.float)),
  video_score_what_if: s.m(S.option(S.float)),
  a_plus_score_what_if: s.m(S.option(S.float)),
  fba_in_stock_rate_what_if: s.m(S.option(S.float)),
  inventory_turnover_what_if: s.m(S.option(S.float)),
  safety_stock_what_if: s.m(S.option(S.float)),
  storage_costs_what_if: s.m(S.option(S.float)),
  shipping_costs_what_if: s.m(S.option(S.float)),
  market_total_sales_what_if: s.m(S.option(S.float)),
  brand_market_share_what_if: s.m(S.option(S.float)),
  market_average_price_what_if: s.m(S.option(S.float)),
  attribution_sales_what_if: s.m(S.option(S.float)),
  attribution_spend_what_if: s.m(S.option(S.float)),
  attribution_impressions_what_if: s.m(S.option(S.float)),
  attribution_clicks_what_if: s.m(S.option(S.float)),
  attribution_orders_what_if: s.m(S.option(S.float)),
  attribution_units_sold_what_if: s.m(S.option(S.float)),
  attribution_ctr_what_if: s.m(S.option(S.float)),
  attribution_cvr_what_if: s.m(S.option(S.float)),
  attribution_acos_what_if: s.m(S.option(S.float)),
  attribution_roas_what_if: s.m(S.option(S.float)),
  attribution_cpc_what_if: s.m(S.option(S.float)),
  attribution_cpm_what_if: s.m(S.option(S.float)),
  no_sales: s.m(S.option(forecastParamsSchema)),
  poor: s.m(S.option(forecastParamsSchema)),
  mid: s.m(S.option(forecastParamsSchema)),
  good: s.m(S.option(forecastParamsSchema))
}));

let inventoryExecutiveSummaryWithForecastBreakdownSchema = S.schema(s => ({
  fba_in_stock_rate: s.m(S.option(S.float)),
  fbt_in_stock_rate: s.m(S.option(S.float)),
  three_pl_in_stock_rate: s.m(S.option(S.float)),
  storage_costs: s.m(S.option(S.float)),
  shipping_costs: s.m(S.option(S.float)),
  forecasting_accuracy: s.m(S.option(S.float)),
  inventory_turnover: s.m(S.option(S.float)),
  safety_stock: s.m(S.option(S.float)),
  doi_available: s.m(S.option(S.float)),
  total_doi: s.m(S.option(S.float)),
  estimated_stock_out_date: s.m(S.option(S.string)),
  real: s.m(inventoryExecutiveSummaryResponseSchemaSchema),
  forecasted: s.m(inventoryExecutiveSummaryResponseSchemaSchema)
}));

let timelineDataPoint_InventoryExecutiveSummaryResponseSchema_Schema = S.schema(s => ({
  period_start: s.m(S.string),
  period_end: s.m(S.string),
  is_forecast: s.m(S.bool),
  value: s.m(inventoryExecutiveSummaryResponseSchemaSchema),
  compare_value: s.m(S.option(inventoryExecutiveSummaryResponseSchemaSchema)),
  compare_diff: s.m(S.option(inventoryExecutiveSummaryResponseSchemaSchema)),
  compare_percent_diff: s.m(S.option(floatOrDictSchema))
}));

let whatifTimelineDataPoint_InventoryExecutiveSummaryResponseSchema_Schema = S.schema(s => ({
  period_start: s.m(S.string),
  period_end: s.m(S.string),
  is_forecast: s.m(S.bool),
  baseline: s.m(inventoryExecutiveSummaryResponseSchemaSchema),
  projected: s.m(S.option(inventoryExecutiveSummaryResponseSchemaSchema)),
  diff: s.m(S.option(inventoryExecutiveSummaryResponseSchemaSchema)),
  percent_diff: s.m(S.option(floatOrDictSchema)),
  compare_value: s.m(S.option(inventoryExecutiveSummaryResponseSchemaSchema)),
  compare_diff: s.m(S.option(inventoryExecutiveSummaryResponseSchemaSchema)),
  compare_percent_diff: s.m(S.option(floatOrDictSchema))
}));

let marketIntelligenceExecutiveSummaryWithForecastBreakdownSchema = S.schema(s => ({
  market_total_sales: s.m(S.option(S.float)),
  brand_market_share: s.m(S.option(S.float)),
  market_average_price: s.m(S.option(S.float)),
  market_total_units_sold: s.m(S.option(S.float)),
  market_asin_count: s.m(S.option(S.int)),
  market_promotion_value: s.m(S.option(S.float)),
  market_promotion_count: s.m(S.option(S.int)),
  market_review_score: s.m(S.option(S.float)),
  market_pos: s.m(S.option(S.float)),
  market_ad_spend: s.m(S.option(S.float)),
  real: s.m(marketIntelligenceExecutiveSummaryResponseSchemaSchema),
  forecasted: s.m(marketIntelligenceExecutiveSummaryResponseSchemaSchema)
}));

let timelineDataPoint_MarketIntelligenceExecutiveSummaryResponseSchema_Schema = S.schema(s => ({
  period_start: s.m(S.string),
  period_end: s.m(S.string),
  is_forecast: s.m(S.bool),
  value: s.m(marketIntelligenceExecutiveSummaryResponseSchemaSchema),
  compare_value: s.m(S.option(marketIntelligenceExecutiveSummaryResponseSchemaSchema)),
  compare_diff: s.m(S.option(marketIntelligenceExecutiveSummaryResponseSchemaSchema)),
  compare_percent_diff: s.m(S.option(floatOrDictSchema))
}));

let whatifTimelineDataPoint_MarketIntelligenceExecutiveSummaryResponseSchema_Schema = S.schema(s => ({
  period_start: s.m(S.string),
  period_end: s.m(S.string),
  is_forecast: s.m(S.bool),
  baseline: s.m(marketIntelligenceExecutiveSummaryResponseSchemaSchema),
  projected: s.m(S.option(marketIntelligenceExecutiveSummaryResponseSchemaSchema)),
  diff: s.m(S.option(marketIntelligenceExecutiveSummaryResponseSchemaSchema)),
  percent_diff: s.m(S.option(floatOrDictSchema)),
  compare_value: s.m(S.option(marketIntelligenceExecutiveSummaryResponseSchemaSchema)),
  compare_diff: s.m(S.option(marketIntelligenceExecutiveSummaryResponseSchemaSchema)),
  compare_percent_diff: s.m(S.option(floatOrDictSchema))
}));

let organicExecutiveSummaryWithForecastBreakdownSchema = S.schema(s => ({
  organic_sales: s.m(S.float),
  organic_impressions: s.m(S.option(S.float)),
  organic_ctr: s.m(S.option(S.float)),
  organic_clicks: s.m(S.float),
  organic_cvr: s.m(S.float),
  organic_orders: s.m(S.float),
  organic_units_sold: s.m(S.float),
  real: s.m(organicExecutiveSummaryResponseSchemaSchema),
  forecasted: s.m(organicExecutiveSummaryResponseSchemaSchema)
}));

let whatifTimelineDataPoint_OrganicExecutiveSummaryResponseSchema_Schema = S.schema(s => ({
  period_start: s.m(S.string),
  period_end: s.m(S.string),
  is_forecast: s.m(S.bool),
  baseline: s.m(organicExecutiveSummaryResponseSchemaSchema),
  projected: s.m(S.option(organicExecutiveSummaryResponseSchemaSchema)),
  diff: s.m(S.option(organicExecutiveSummaryResponseSchemaSchema)),
  percent_diff: s.m(S.option(floatOrDictSchema)),
  compare_value: s.m(S.option(organicExecutiveSummaryResponseSchemaSchema)),
  compare_diff: s.m(S.option(organicExecutiveSummaryResponseSchemaSchema)),
  compare_percent_diff: s.m(S.option(floatOrDictSchema))
}));

let timelineDataPoint_TotalExecutiveSummaryResponseSchema_Schema = S.schema(s => ({
  period_start: s.m(S.string),
  period_end: s.m(S.string),
  is_forecast: s.m(S.bool),
  value: s.m(totalExecutiveSummaryResponseSchemaSchema),
  compare_value: s.m(S.option(totalExecutiveSummaryResponseSchemaSchema)),
  compare_diff: s.m(S.option(totalExecutiveSummaryResponseSchemaSchema)),
  compare_percent_diff: s.m(S.option(floatOrDictSchema))
}));

let totalExecutiveSummaryWithForecastBreakdownSchema = S.schema(s => ({
  total_sales: s.m(S.option(S.float)),
  total_spend: s.m(S.option(S.float)),
  total_impressions: s.m(S.option(S.float)),
  ctr: s.m(S.option(S.float)),
  total_clicks: s.m(S.option(S.float)),
  cvr: s.m(S.option(S.float)),
  total_orders: s.m(S.option(S.float)),
  total_units_sold: s.m(S.option(S.float)),
  total_ntb_orders: s.m(S.option(S.float)),
  tacos: s.m(S.option(S.float)),
  mer: s.m(S.option(S.float)),
  lost_sales: s.m(S.option(S.float)),
  real: s.m(totalExecutiveSummaryResponseSchemaSchema),
  forecasted: s.m(totalExecutiveSummaryResponseSchemaSchema)
}));

let whatifTimelineDataPoint_TotalExecutiveSummaryResponseSchema_Schema = S.schema(s => ({
  period_start: s.m(S.string),
  period_end: s.m(S.string),
  is_forecast: s.m(S.bool),
  baseline: s.m(totalExecutiveSummaryResponseSchemaSchema),
  projected: s.m(S.option(totalExecutiveSummaryResponseSchemaSchema)),
  diff: s.m(S.option(totalExecutiveSummaryResponseSchemaSchema)),
  percent_diff: s.m(S.option(floatOrDictSchema)),
  compare_value: s.m(S.option(totalExecutiveSummaryResponseSchemaSchema)),
  compare_diff: s.m(S.option(totalExecutiveSummaryResponseSchemaSchema)),
  compare_percent_diff: s.m(S.option(floatOrDictSchema))
}));

let inventoryMetricsResponseSchema = S.schema(s => ({
  daily_metrics: s.m(S.array(dailyInventoryMetricsSchema)),
  total_metrics: s.m(totalInventoryMetricsSchema)
}));

let whatifAppliedEntryOrDictSchema = S.union([
  S.schema(s => ({
    _tag: "WhatifAppliedEntry",
    _0: s.m(whatifAppliedEntrySchema)
  })),
  S.schema(s => ({
    _tag: "Dict",
    _0: s.m(S.dict(S.string))
  }))
]);

let whatifModelInfoOrDictSchema = S.union([
  S.schema(s => ({
    _tag: "WhatifModelInfo",
    _0: s.m(whatifModelInfoSchema)
  })),
  S.schema(s => ({
    _tag: "Dict",
    _0: s.m(S.dict(S.string))
  }))
]);

let timelineResponse_dict_Schema = S.schema(s => ({
  data: s.m(S.array(timelineDataPoint_dict_Schema)),
  period_start: s.m(S.string),
  period_end: s.m(S.string),
  period: s.m(S.option(S.string))
}));

let hTTPValidationErrorSchema = S.schema(s => ({
  detail: s.m(S.option(S.array(validationErrorSchema)))
}));

let timelineResponse_AdsExecutiveSummaryResponseSchema_Schema = S.schema(s => ({
  data: s.m(S.array(timelineDataPoint_AdsExecutiveSummaryResponseSchema_Schema)),
  period_start: s.m(S.string),
  period_end: s.m(S.string),
  period: s.m(S.option(S.string))
}));

let whatifTimelineResponse_AdsExecutiveSummaryResponseSchema_Schema = S.schema(s => ({
  data: s.m(S.array(whatifTimelineDataPoint_AdsExecutiveSummaryResponseSchema_Schema)),
  period_start: s.m(S.string),
  period_end: s.m(S.string),
  period: s.m(S.option(S.string))
}));

let timelineResponse_AttributionExecutiveSummaryResponseSchema_Schema = S.schema(s => ({
  data: s.m(S.array(timelineDataPoint_AttributionExecutiveSummaryResponseSchema_Schema)),
  period_start: s.m(S.string),
  period_end: s.m(S.string),
  period: s.m(S.option(S.string))
}));

let whatifTimelineResponse_AttributionExecutiveSummaryResponseSchema_Schema = S.schema(s => ({
  data: s.m(S.array(whatifTimelineDataPoint_AttributionExecutiveSummaryResponseSchema_Schema)),
  period_start: s.m(S.string),
  period_end: s.m(S.string),
  period: s.m(S.option(S.string))
}));

let timelineResponse_CFOExecutiveSummaryResponseSchema_Schema = S.schema(s => ({
  data: s.m(S.array(timelineDataPoint_CFOExecutiveSummaryResponseSchema_Schema)),
  period_start: s.m(S.string),
  period_end: s.m(S.string),
  period: s.m(S.option(S.string))
}));

let whatifTimelineResponse_CFOExecutiveSummaryResponseSchema_Schema = S.schema(s => ({
  data: s.m(S.array(whatifTimelineDataPoint_CFOExecutiveSummaryResponseSchema_Schema)),
  period_start: s.m(S.string),
  period_end: s.m(S.string),
  period: s.m(S.option(S.string))
}));

let timelineResponse_InventoryExecutiveSummaryResponseSchema_Schema = S.schema(s => ({
  data: s.m(S.array(timelineDataPoint_InventoryExecutiveSummaryResponseSchema_Schema)),
  period_start: s.m(S.string),
  period_end: s.m(S.string),
  period: s.m(S.option(S.string))
}));

let whatifTimelineResponse_InventoryExecutiveSummaryResponseSchema_Schema = S.schema(s => ({
  data: s.m(S.array(whatifTimelineDataPoint_InventoryExecutiveSummaryResponseSchema_Schema)),
  period_start: s.m(S.string),
  period_end: s.m(S.string),
  period: s.m(S.option(S.string))
}));

let timelineResponse_MarketIntelligenceExecutiveSummaryResponseSchema_Schema = S.schema(s => ({
  data: s.m(S.array(timelineDataPoint_MarketIntelligenceExecutiveSummaryResponseSchema_Schema)),
  period_start: s.m(S.string),
  period_end: s.m(S.string),
  period: s.m(S.option(S.string))
}));

let whatifTimelineResponse_MarketIntelligenceExecutiveSummaryResponseSchema_Schema = S.schema(s => ({
  data: s.m(S.array(whatifTimelineDataPoint_MarketIntelligenceExecutiveSummaryResponseSchema_Schema)),
  period_start: s.m(S.string),
  period_end: s.m(S.string),
  period: s.m(S.option(S.string))
}));

let whatifTimelineResponse_OrganicExecutiveSummaryResponseSchema_Schema = S.schema(s => ({
  data: s.m(S.array(whatifTimelineDataPoint_OrganicExecutiveSummaryResponseSchema_Schema)),
  period_start: s.m(S.string),
  period_end: s.m(S.string),
  period: s.m(S.option(S.string))
}));

let timelineResponse_TotalExecutiveSummaryResponseSchema_Schema = S.schema(s => ({
  data: s.m(S.array(timelineDataPoint_TotalExecutiveSummaryResponseSchema_Schema)),
  period_start: s.m(S.string),
  period_end: s.m(S.string),
  period: s.m(S.option(S.string))
}));

let whatifTimelineResponse_TotalExecutiveSummaryResponseSchema_Schema = S.schema(s => ({
  data: s.m(S.array(whatifTimelineDataPoint_TotalExecutiveSummaryResponseSchema_Schema)),
  period_start: s.m(S.string),
  period_end: s.m(S.string),
  period: s.m(S.option(S.string))
}));

let whatifResponse_AdsExecutiveSummaryResponseSchema_Schema = S.schema(s => ({
  baseline: s.m(adsExecutiveSummaryResponseSchemaSchema),
  projected: s.m(adsExecutiveSummaryResponseSchemaSchema),
  diff: s.m(S.dict(S.option(S.float))),
  percent_diff: s.m(S.dict(S.option(S.float))),
  whatif_applied: s.m(S.dict(whatifAppliedEntryOrDictSchema)),
  model_info: s.m(whatifModelInfoOrDictSchema),
  warnings: s.m(S.option(S.array(S.string)))
}));

let whatifResponse_AttributionExecutiveSummaryResponseSchema_Schema = S.schema(s => ({
  baseline: s.m(attributionExecutiveSummaryResponseSchemaSchema),
  projected: s.m(attributionExecutiveSummaryResponseSchemaSchema),
  diff: s.m(S.dict(S.option(S.float))),
  percent_diff: s.m(S.dict(S.option(S.float))),
  whatif_applied: s.m(S.dict(whatifAppliedEntryOrDictSchema)),
  model_info: s.m(whatifModelInfoOrDictSchema),
  warnings: s.m(S.option(S.array(S.string)))
}));

let whatifResponse_CFOExecutiveSummaryResponseSchema_Schema = S.schema(s => ({
  baseline: s.m(cFOExecutiveSummaryResponseSchemaSchema),
  projected: s.m(cFOExecutiveSummaryResponseSchemaSchema),
  diff: s.m(S.dict(S.option(S.float))),
  percent_diff: s.m(S.dict(S.option(S.float))),
  whatif_applied: s.m(S.dict(whatifAppliedEntryOrDictSchema)),
  model_info: s.m(whatifModelInfoOrDictSchema),
  warnings: s.m(S.option(S.array(S.string)))
}));

let whatifResponse_InventoryExecutiveSummaryResponseSchema_Schema = S.schema(s => ({
  baseline: s.m(inventoryExecutiveSummaryResponseSchemaSchema),
  projected: s.m(inventoryExecutiveSummaryResponseSchemaSchema),
  diff: s.m(S.dict(S.option(S.float))),
  percent_diff: s.m(S.dict(S.option(S.float))),
  whatif_applied: s.m(S.dict(whatifAppliedEntryOrDictSchema)),
  model_info: s.m(whatifModelInfoOrDictSchema),
  warnings: s.m(S.option(S.array(S.string)))
}));

let whatifResponse_MarketIntelligenceExecutiveSummaryResponseSchema_Schema = S.schema(s => ({
  baseline: s.m(marketIntelligenceExecutiveSummaryResponseSchemaSchema),
  projected: s.m(marketIntelligenceExecutiveSummaryResponseSchemaSchema),
  diff: s.m(S.dict(S.option(S.float))),
  percent_diff: s.m(S.dict(S.option(S.float))),
  whatif_applied: s.m(S.dict(whatifAppliedEntryOrDictSchema)),
  model_info: s.m(whatifModelInfoOrDictSchema),
  warnings: s.m(S.option(S.array(S.string)))
}));

let whatifResponse_OrganicExecutiveSummaryResponseSchema_Schema = S.schema(s => ({
  baseline: s.m(organicExecutiveSummaryResponseSchemaSchema),
  projected: s.m(organicExecutiveSummaryResponseSchemaSchema),
  diff: s.m(S.dict(S.option(S.float))),
  percent_diff: s.m(S.dict(S.option(S.float))),
  whatif_applied: s.m(S.dict(whatifAppliedEntryOrDictSchema)),
  model_info: s.m(whatifModelInfoOrDictSchema),
  warnings: s.m(S.option(S.array(S.string)))
}));

let whatifResponse_TotalExecutiveSummaryResponseSchema_Schema = S.schema(s => ({
  baseline: s.m(totalExecutiveSummaryResponseSchemaSchema),
  projected: s.m(totalExecutiveSummaryResponseSchemaSchema),
  diff: s.m(S.dict(S.option(S.float))),
  percent_diff: s.m(S.dict(S.option(S.float))),
  whatif_applied: s.m(S.dict(whatifAppliedEntryOrDictSchema)),
  model_info: s.m(whatifModelInfoOrDictSchema),
  warnings: s.m(S.option(S.array(S.string)))
}));

export {
  floatOrDictSchema,
  stringOrIntSchema,
  adsExecutiveSummaryResponseSchemaSchema,
  attributionExecutiveSummaryResponseSchemaSchema,
  cFOExecutiveSummaryResponseSchemaSchema,
  dailyInventoryMetricsSchema,
  forecastParamsSchema,
  insightResponseSchema,
  inventoryExecutiveSummaryResponseSchemaSchema,
  marketIntelligenceExecutiveSummaryResponseSchemaSchema,
  organicExecutiveSummaryResponseSchemaSchema,
  strategicPlanResponseSchema,
  totalExecutiveSummaryResponseSchemaSchema,
  totalInventoryMetricsSchema,
  whatifAppliedEntrySchema,
  whatifModelInfoSchema,
  timelineDataPoint_dict_Schema,
  validationErrorSchema,
  adsExecutiveSummaryWithForecastBreakdownSchema,
  timelineDataPoint_AdsExecutiveSummaryResponseSchema_Schema,
  whatifTimelineDataPoint_AdsExecutiveSummaryResponseSchema_Schema,
  attributionExecutiveSummaryWithForecastBreakdownSchema,
  timelineDataPoint_AttributionExecutiveSummaryResponseSchema_Schema,
  whatifTimelineDataPoint_AttributionExecutiveSummaryResponseSchema_Schema,
  cFOExecutiveSummaryWithForecastBreakdownSchema,
  timelineDataPoint_CFOExecutiveSummaryResponseSchema_Schema,
  whatifTimelineDataPoint_CFOExecutiveSummaryResponseSchema_Schema,
  tierLevelForecastParamsSchema,
  inventoryExecutiveSummaryWithForecastBreakdownSchema,
  timelineDataPoint_InventoryExecutiveSummaryResponseSchema_Schema,
  whatifTimelineDataPoint_InventoryExecutiveSummaryResponseSchema_Schema,
  marketIntelligenceExecutiveSummaryWithForecastBreakdownSchema,
  timelineDataPoint_MarketIntelligenceExecutiveSummaryResponseSchema_Schema,
  whatifTimelineDataPoint_MarketIntelligenceExecutiveSummaryResponseSchema_Schema,
  organicExecutiveSummaryWithForecastBreakdownSchema,
  whatifTimelineDataPoint_OrganicExecutiveSummaryResponseSchema_Schema,
  timelineDataPoint_TotalExecutiveSummaryResponseSchema_Schema,
  totalExecutiveSummaryWithForecastBreakdownSchema,
  whatifTimelineDataPoint_TotalExecutiveSummaryResponseSchema_Schema,
  inventoryMetricsResponseSchema,
  whatifAppliedEntryOrDictSchema,
  whatifModelInfoOrDictSchema,
  timelineResponse_dict_Schema,
  hTTPValidationErrorSchema,
  timelineResponse_AdsExecutiveSummaryResponseSchema_Schema,
  whatifTimelineResponse_AdsExecutiveSummaryResponseSchema_Schema,
  timelineResponse_AttributionExecutiveSummaryResponseSchema_Schema,
  whatifTimelineResponse_AttributionExecutiveSummaryResponseSchema_Schema,
  timelineResponse_CFOExecutiveSummaryResponseSchema_Schema,
  whatifTimelineResponse_CFOExecutiveSummaryResponseSchema_Schema,
  timelineResponse_InventoryExecutiveSummaryResponseSchema_Schema,
  whatifTimelineResponse_InventoryExecutiveSummaryResponseSchema_Schema,
  timelineResponse_MarketIntelligenceExecutiveSummaryResponseSchema_Schema,
  whatifTimelineResponse_MarketIntelligenceExecutiveSummaryResponseSchema_Schema,
  whatifTimelineResponse_OrganicExecutiveSummaryResponseSchema_Schema,
  timelineResponse_TotalExecutiveSummaryResponseSchema_Schema,
  whatifTimelineResponse_TotalExecutiveSummaryResponseSchema_Schema,
  whatifResponse_AdsExecutiveSummaryResponseSchema_Schema,
  whatifResponse_AttributionExecutiveSummaryResponseSchema_Schema,
  whatifResponse_CFOExecutiveSummaryResponseSchema_Schema,
  whatifResponse_InventoryExecutiveSummaryResponseSchema_Schema,
  whatifResponse_MarketIntelligenceExecutiveSummaryResponseSchema_Schema,
  whatifResponse_OrganicExecutiveSummaryResponseSchema_Schema,
  whatifResponse_TotalExecutiveSummaryResponseSchema_Schema,
}
/* floatOrDictSchema Not a pure module */
