// Generated by osury. Do not edit.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StringOrInt {
    String(String),
    Int(i64),
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StringOrArrayBool {
    String(String),
    ArrayBool(Vec<bool>),
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum InlineEnum {
    #[serde(rename = "on")]
    On,
    #[serde(rename = "off")]
    Off,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum LiteralUnion {
    #[serde(rename = "yes")]
    Yes,
    #[serde(rename = "no")]
    No,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum IssueLoopKind {
    #[serde(rename = "loop_found")]
    LoopFound,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum IssueBrokenLinkKind {
    #[serde(rename = "broken_link")]
    BrokenLink,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum Order {
    #[serde(rename = "asc")]
    Asc,
    #[serde(rename = "desc")]
    Desc,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Scalars {
    pub s: String,
    pub f: f64,
    pub i: i64,
    pub b: bool,
    pub nothing: (),
    pub anything: serde_json::Value,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub opt: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub with_default: Option<i64>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Refined {
    pub id: String,
    pub email: String,
    pub site: String,
    pub created_at: String,
    pub slug: String,
    pub ratio: f64,
    pub count: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Containers {
    pub tags: Vec<String>,
    pub matrix: Vec<Vec<i64>>,
    pub by_key: std::collections::HashMap<String, f64>,
    pub free_form: std::collections::HashMap<String, serde_json::Value>,
    pub nested: serde_json::Value,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Keywords {
    #[serde(rename = "type")]
    pub type_: String,
    pub module: String,
    pub and: bool,
    pub external: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum Size {
    #[serde(rename = "small")]
    Small,
    #[serde(rename = "medium")]
    Medium,
    #[serde(rename = "large")]
    Large,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(into = "Vec<String>", try_from = "Vec<String>")]
pub enum Phase {
    Draft,
    Done,
}

impl From<Phase> for Vec<String> {
    fn from(v: Phase) -> Self {
        vec![match v {
            Phase::Draft => "Draft",
            Phase::Done => "Done",
        }
        .to_string()]
    }
}

impl TryFrom<Vec<String>> for Phase {
    type Error = String;
    fn try_from(v: Vec<String>) -> Result<Self, Self::Error> {
        match v.as_slice() {
            [s] => match s.as_str() {
                "Draft" => Ok(Phase::Draft),
                "Done" => Ok(Phase::Done),
                other => Err(format!("Phase: unknown variant: {other}")),
            },
            _ => Err("Phase: expected single-element list".to_string()),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Measure {
    pub value: f64,
    pub unit: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Base {
    pub id: String,
    pub created_at: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Node {
    pub name: String,
    pub children: Vec<Node>,
    pub parent: Option<Node>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EventCreated {
    pub at: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EventDeleted {
    pub reason: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum Mark {
    Shine {
        target: String,
    },
    Tint {
        level: i64,
    },
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GetV1Widgets_widget_idParams {
    pub widget_id: String,
}

pub type MixedAlias = Vec<StringOrArrayBool>;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IssueLoop {
    pub kind: IssueLoopKind,
    pub path: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IssueBrokenLink {
    pub kind: IssueBrokenLinkKind,
    pub from: String,
    pub to: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GetV1WidgetsParams {
    pub limit: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub order: Option<Order>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Nullables {
    pub maybe_text: Option<String>,
    pub maybe_size: Option<Size>,
    pub maybe_list: Option<Vec<String>>,
    pub only_one: String,
    pub inline_enum: InlineEnum,
    pub literal_union: LiteralUnion,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Widget {
    pub id: String,
    pub created_at: String,
    pub size: Size,
    pub weight: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum MeasureOrFloat {
    Measure(Measure),
    Float(f64),
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "_tag")]
pub enum Event {
    EventCreated {
        at: String,
    },
    EventDeleted {
        reason: String,
    },
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "kind")]
pub enum IssueLoopOrIssueBrokenLink {
    IssueLoop {
        path: Vec<String>,
    },
    IssueBrokenLink {
        from: String,
        to: String,
    },
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "kind")]
pub enum Issue {
    #[serde(rename = "loop_found")]
    LoopFound {
        path: Vec<String>,
    },
    #[serde(rename = "broken_link")]
    BrokenLink {
        from: String,
        to: String,
    },
}

pub type WidgetAlias = Widget;

pub type GetV1WidgetsResponse = Vec<Widget>;

pub type GetV1Widgets_widget_idResponse = Widget;

pub type PostV1Widgets_widget_idResponse = Widget;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ShapeDistinct {
    pub amount: MeasureOrFloat,
    pub mixed_list: Vec<StringOrInt>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Envelope {
    pub payload: IssueLoopOrIssueBrokenLink,
    pub event: Event,
    pub phase: Phase,
    pub mark: Mark,
}
