(* Generated by osury. Do not edit. *)

module Oj = struct
  let ( let* ) = Result.bind

  let type_err name j =
    Error (Printf.sprintf "%s: unexpected %s" name (Yojson.Safe.to_string j))

  let string_ = function `String s -> Ok s | j -> type_err "string" j

  let float_ = function
    | `Float f -> Ok f
    | `Int i -> Ok (float_of_int i)
    | j -> type_err "float" j

  let int_ = function `Int i -> Ok i | j -> type_err "int" j

  (* Validation keyword from the spec: the value decoded fine, but the schema
     says it must also satisfy this. *)
  let check_ name pred = function
    | Ok v when pred v -> Ok v
    | Ok _ -> Error (Printf.sprintf "%s: check failed" name)
    | Error _ as e -> e
  let bool_ = function `Bool b -> Ok b | j -> type_err "bool" j
  let unit_ = function `Null -> Ok () | j -> type_err "unit" j

  let nullable_ dec = function
    | `Null -> Ok None
    | j -> Result.map (fun v -> Some v) (dec j)

  let list_ dec = function
    | `List xs ->
      List.fold_right
        (fun x acc ->
          let* acc = acc in
          let* v = dec x in
          Ok (v :: acc))
        xs (Ok [])
    | j -> type_err "list" j

  let dict_ dec = function
    | `Assoc kvs ->
      List.fold_right
        (fun (k, x) acc ->
          let* acc = acc in
          let* v = dec x in
          Ok ((k, v) :: acc))
        kvs (Ok [])
    | j -> type_err "dict" j

  let req_field name dec j =
    match j with
    | `Assoc kvs -> (
        match List.assoc_opt name kvs with
        | Some v -> dec v
        | None -> Error (Printf.sprintf "missing field %s" name))
    | j -> type_err name j

  let opt_field name dec j =
    match j with
    | `Assoc kvs -> (
        match List.assoc_opt name kvs with
        | Some `Null | None -> Ok None
        | Some v -> Result.map (fun v -> Some v) (dec v))
    | j -> type_err name j
end

type string_or_int =
  | String of string
  | Int of int

type string_or_array_bool =
  | String of string
  | ArrayBool of bool list

type containers_nested = {
  deep : (string * string) list list;
}

type inline_enum =
  | On
  | Off

type literal_union =
  | Yes
  | No

type issue_loop_kind =
  | Loop_found

type issue_broken_link_kind =
  | Broken_link

type order =
  | Asc
  | Desc

type scalars = {
  s : string;
  f : float;
  i : int;
  b : bool;
  nothing : unit;
  anything : Yojson.Safe.t;
  opt : string option;
  with_default : int option;
}

type refined = {
  id : string;
  email : string;
  site : string;
  created_at : string;
  slug : string;
  ratio : float;
  count : int;
}

type keywords = {
  type_ : string;
  module_ : string;
  and_ : bool;
  external_ : int;
}

type size =
  | Small
  | Medium
  | Large

type phase =
  | Draft
  | Done

type measure = {
  value : float;
  unit : string;
}

type base = {
  id : string;
  created_at : string;
}

type node = {
  name : string;
  children : node list;
  parent : node option;
}

type event_created = {
  at : string;
}

type event_deleted = {
  reason : string;
}

type mark =
  | Shine of { target : string }
  | Tint of { level : int }

type post_v1_widgets_response202 = {
  job_id : string;
}

type get_v1_widgets_widget_id_params = {
  widget_id : string;
}

type patch_v1_widgets_widget_id_request = {
  weight : float option;
}

type mixed_alias = string_or_array_bool list

type containers = {
  tags : string list;
  matrix : int list list;
  by_key : (string * float) list;
  free_form : (string * Yojson.Safe.t) list;
  nested : containers_nested;
}

type issue_loop = {
  kind : issue_loop_kind;
  path : string list;
}

type issue_broken_link = {
  kind : issue_broken_link_kind;
  from : string;
  to_ : string;
}

type get_v1_widgets_params = {
  limit : int;
  cursor : string option;
  order : order option;
}

type nullables = {
  maybe_text : string option;
  maybe_size : size option;
  maybe_list : string list option;
  only_one : string;
  inline_enum : inline_enum;
  literal_union : literal_union;
}

type widget = {
  id : string;
  created_at : string;
  size : size;
  weight : float;
}

type measure_or_float =
  | Measure of measure
  | Float of float

type event =
  | EventCreated of { at : string }
  | EventDeleted of { reason : string }

type issue_loop_or_issue_broken_link =
  | IssueLoop of { path : string list }
  | IssueBrokenLink of { from : string; to_ : string }

type issue =
  | LoopFound of { path : string list }
  | BrokenLink of { from : string; to_ : string }

type widget_alias = widget

type get_v1_widgets_response = widget list

type post_v1_widgets_response = widget

type get_v1_widgets_widget_id_response = widget

type post_v1_widgets_widget_id_response = widget

type patch_v1_widgets_widget_id_response = widget

type post_v1_widgets_request = widget

type shape_distinct = {
  amount : measure_or_float;
  mixed_list : string_or_int list;
}

type envelope = {
  payload : issue_loop_or_issue_broken_link;
  event : event;
  phase : phase;
  mark : mark;
}
let rec string_or_int_to_yojson (v : string_or_int) : Yojson.Safe.t =
  match v with
  | String v -> `String v
  | Int v -> `Int v

and string_or_int_of_yojson (j : Yojson.Safe.t) : (string_or_int, string) result =
  let open Oj in
  ignore (let* x = Ok () in Ok x);
  (match Oj.string_ j with
     | Ok v -> Ok (String v)
     | Error _ -> (match Oj.int_ j with
     | Ok v -> Ok (Int v)
     | Error _ -> Error ("string_or_int: no variant matched")))

and string_or_array_bool_to_yojson (v : string_or_array_bool) : Yojson.Safe.t =
  match v with
  | String v -> `String v
  | ArrayBool v -> `List (List.map (fun x -> `Bool x) v)

and string_or_array_bool_of_yojson (j : Yojson.Safe.t) : (string_or_array_bool, string) result =
  let open Oj in
  ignore (let* x = Ok () in Ok x);
  (match Oj.string_ j with
     | Ok v -> Ok (String v)
     | Error _ -> (match Oj.list_ (fun j -> Oj.bool_ j) j with
     | Ok v -> Ok (ArrayBool v)
     | Error _ -> Error ("string_or_array_bool: no variant matched")))

and containers_nested_to_yojson (x : containers_nested) : Yojson.Safe.t =
  `Assoc
    (List.concat
    [
      [ ("deep", `List (List.map (fun x -> `Assoc (List.map (fun (k, x) -> (k, `String x)) x)) x.deep)) ];
    ])

and containers_nested_of_yojson (j : Yojson.Safe.t) : (containers_nested, string) result =
  let open Oj in
  let* deep = Oj.req_field "deep" (fun j -> Oj.list_ (fun j -> Oj.dict_ (fun j -> Oj.string_ j) j) j) j in
  Ok ({ deep } : containers_nested)

and inline_enum_to_yojson (v : inline_enum) : Yojson.Safe.t =
  match v with
  | On -> `String "on"
  | Off -> `String "off"

and inline_enum_of_yojson (j : Yojson.Safe.t) : (inline_enum, string) result =
  match j with
  | `String "on" -> Ok On
  | `String "off" -> Ok Off
  | j -> Error ("inline_enum: unexpected " ^ Yojson.Safe.to_string j)

and literal_union_to_yojson (v : literal_union) : Yojson.Safe.t =
  match v with
  | Yes -> `String "yes"
  | No -> `String "no"

and literal_union_of_yojson (j : Yojson.Safe.t) : (literal_union, string) result =
  match j with
  | `String "yes" -> Ok Yes
  | `String "no" -> Ok No
  | j -> Error ("literal_union: unexpected " ^ Yojson.Safe.to_string j)

and issue_loop_kind_to_yojson (v : issue_loop_kind) : Yojson.Safe.t =
  match v with
  | Loop_found -> `String "loop_found"

and issue_loop_kind_of_yojson (j : Yojson.Safe.t) : (issue_loop_kind, string) result =
  match j with
  | `String "loop_found" -> Ok Loop_found
  | j -> Error ("issue_loop_kind: unexpected " ^ Yojson.Safe.to_string j)

and issue_broken_link_kind_to_yojson (v : issue_broken_link_kind) : Yojson.Safe.t =
  match v with
  | Broken_link -> `String "broken_link"

and issue_broken_link_kind_of_yojson (j : Yojson.Safe.t) : (issue_broken_link_kind, string) result =
  match j with
  | `String "broken_link" -> Ok Broken_link
  | j -> Error ("issue_broken_link_kind: unexpected " ^ Yojson.Safe.to_string j)

and order_to_yojson (v : order) : Yojson.Safe.t =
  match v with
  | Asc -> `String "asc"
  | Desc -> `String "desc"

and order_of_yojson (j : Yojson.Safe.t) : (order, string) result =
  match j with
  | `String "asc" -> Ok Asc
  | `String "desc" -> Ok Desc
  | j -> Error ("order: unexpected " ^ Yojson.Safe.to_string j)

and scalars_to_yojson (x : scalars) : Yojson.Safe.t =
  `Assoc
    (List.concat
    [
      [ ("s", `String x.s) ];
      [ ("f", `Float x.f) ];
      [ ("i", `Int x.i) ];
      [ ("b", `Bool x.b) ];
      [ ("nothing", `Null) ];
      [ ("anything", x.anything) ];
      (match x.opt with Some v -> [ ("opt", `String v) ] | None -> []);
      (match x.with_default with Some v -> [ ("with_default", `Int v) ] | None -> []);
    ])

and scalars_of_yojson (j : Yojson.Safe.t) : (scalars, string) result =
  let open Oj in
  let* s = Oj.req_field "s" (fun j -> Oj.string_ j) j in
  let* f = Oj.req_field "f" (fun j -> Oj.float_ j) j in
  let* i = Oj.req_field "i" (fun j -> Oj.int_ j) j in
  let* b = Oj.req_field "b" (fun j -> Oj.bool_ j) j in
  let* nothing = Oj.req_field "nothing" (fun j -> Oj.unit_ j) j in
  let* anything = Oj.req_field "anything" (fun j -> Ok j) j in
  let* opt = Oj.opt_field "opt" (fun j -> Oj.string_ j) j in
  let* with_default = Oj.opt_field "with_default" (fun j -> Oj.int_ j) j in
  Ok ({ s; f; i; b; nothing; anything; opt; with_default } : scalars)

and refined_to_yojson (x : refined) : Yojson.Safe.t =
  `Assoc
    (List.concat
    [
      [ ("id", `String x.id) ];
      [ ("email", `String x.email) ];
      [ ("site", `String x.site) ];
      [ ("created_at", `String x.created_at) ];
      [ ("slug", `String x.slug) ];
      [ ("ratio", `Float x.ratio) ];
      [ ("count", `Int x.count) ];
    ])

and refined_of_yojson (j : Yojson.Safe.t) : (refined, string) result =
  let open Oj in
  let* id = Oj.req_field "id" (fun j -> Oj.string_ j) j in
  let* email = Oj.req_field "email" (fun j -> Oj.string_ j) j in
  let* site = Oj.req_field "site" (fun j -> Oj.string_ j) j in
  let* created_at = Oj.req_field "created_at" (fun j -> Oj.string_ j) j in
  let* slug = Oj.req_field "slug" (fun j -> Oj.check_ "maxLength=32" (fun v -> String.length v <= 32) (Oj.check_ "minLength=3" (fun v -> String.length v >= 3) (Oj.string_ j))) j in
  let* ratio = Oj.req_field "ratio" (fun j -> Oj.check_ "maximum=1" (fun v -> v <= 1.) (Oj.check_ "minimum=0" (fun v -> v >= 0.) (Oj.float_ j))) j in
  let* count = Oj.req_field "count" (fun j -> Oj.check_ "multipleOf=5" (fun v -> v mod 5 = 0) (Oj.check_ "exclusiveMinimum=0" (fun v -> v > 0) (Oj.int_ j))) j in
  Ok ({ id; email; site; created_at; slug; ratio; count } : refined)

and keywords_to_yojson (x : keywords) : Yojson.Safe.t =
  `Assoc
    (List.concat
    [
      [ ("type", `String x.type_) ];
      [ ("module", `String x.module_) ];
      [ ("and", `Bool x.and_) ];
      [ ("external", `Int x.external_) ];
    ])

and keywords_of_yojson (j : Yojson.Safe.t) : (keywords, string) result =
  let open Oj in
  let* type_ = Oj.req_field "type" (fun j -> Oj.string_ j) j in
  let* module_ = Oj.req_field "module" (fun j -> Oj.string_ j) j in
  let* and_ = Oj.req_field "and" (fun j -> Oj.bool_ j) j in
  let* external_ = Oj.req_field "external" (fun j -> Oj.int_ j) j in
  Ok ({ type_; module_; and_; external_ } : keywords)

and size_to_yojson (v : size) : Yojson.Safe.t =
  match v with
  | Small -> `String "small"
  | Medium -> `String "medium"
  | Large -> `String "large"

and size_of_yojson (j : Yojson.Safe.t) : (size, string) result =
  match j with
  | `String "small" -> Ok Small
  | `String "medium" -> Ok Medium
  | `String "large" -> Ok Large
  | j -> Error ("size: unexpected " ^ Yojson.Safe.to_string j)

and phase_to_yojson (v : phase) : Yojson.Safe.t =
  match v with
  | Draft -> `List [ `String "Draft" ]
  | Done -> `List [ `String "Done" ]

and phase_of_yojson (j : Yojson.Safe.t) : (phase, string) result =
  match j with
  | `List [ `String "Draft" ] -> Ok Draft
  | `List [ `String "Done" ] -> Ok Done
  | j -> Error ("phase: unexpected " ^ Yojson.Safe.to_string j)

and measure_to_yojson (x : measure) : Yojson.Safe.t =
  `Assoc
    (List.concat
    [
      [ ("value", `Float x.value) ];
      [ ("unit", `String x.unit) ];
    ])

and measure_of_yojson (j : Yojson.Safe.t) : (measure, string) result =
  let open Oj in
  let* value = Oj.req_field "value" (fun j -> Oj.float_ j) j in
  let* unit = Oj.req_field "unit" (fun j -> Oj.string_ j) j in
  Ok ({ value; unit } : measure)

and base_to_yojson (x : base) : Yojson.Safe.t =
  `Assoc
    (List.concat
    [
      [ ("id", `String x.id) ];
      [ ("created_at", `String x.created_at) ];
    ])

and base_of_yojson (j : Yojson.Safe.t) : (base, string) result =
  let open Oj in
  let* id = Oj.req_field "id" (fun j -> Oj.string_ j) j in
  let* created_at = Oj.req_field "created_at" (fun j -> Oj.string_ j) j in
  Ok ({ id; created_at } : base)

and node_to_yojson (x : node) : Yojson.Safe.t =
  `Assoc
    (List.concat
    [
      [ ("name", `String x.name) ];
      [ ("children", `List (List.map (fun x -> node_to_yojson x) x.children)) ];
      [ ("parent", (match x.parent with Some x -> node_to_yojson x | None -> `Null)) ];
    ])

and node_of_yojson (j : Yojson.Safe.t) : (node, string) result =
  let open Oj in
  let* name = Oj.req_field "name" (fun j -> Oj.string_ j) j in
  let* children = Oj.req_field "children" (fun j -> Oj.list_ (fun j -> node_of_yojson j) j) j in
  let* parent = Oj.req_field "parent" (fun j -> Oj.nullable_ (fun j -> node_of_yojson j) j) j in
  Ok ({ name; children; parent } : node)

and event_created_to_yojson (x : event_created) : Yojson.Safe.t =
  `Assoc
    (List.concat
    [
      [ ("at", `String x.at) ];
    ])

and event_created_of_yojson (j : Yojson.Safe.t) : (event_created, string) result =
  let open Oj in
  let* at = Oj.req_field "at" (fun j -> Oj.string_ j) j in
  Ok ({ at } : event_created)

and event_deleted_to_yojson (x : event_deleted) : Yojson.Safe.t =
  `Assoc
    (List.concat
    [
      [ ("reason", `String x.reason) ];
    ])

and event_deleted_of_yojson (j : Yojson.Safe.t) : (event_deleted, string) result =
  let open Oj in
  let* reason = Oj.req_field "reason" (fun j -> Oj.string_ j) j in
  Ok ({ reason } : event_deleted)

and mark_to_yojson (v : mark) : Yojson.Safe.t =
  match v with
  | Shine { target } ->
    `Assoc
      [
        ( "Shine",
          `Assoc
            (List.concat
        [
          [ ("target", `String target) ];
        ]) );
      ]
  | Tint { level } ->
    `Assoc
      [
        ( "Tint",
          `Assoc
            (List.concat
        [
          [ ("level", `Int level) ];
        ]) );
      ]

and mark_of_yojson (j : Yojson.Safe.t) : (mark, string) result =
  let open Oj in
  match j with
  | `Assoc [ (tag, payload) ] ->
    (match tag, payload with
     | "Shine", j ->
       let* target = Oj.req_field "target" (fun j -> Oj.string_ j) j in
       Ok (Shine { target })
     | "Tint", j ->
       let* level = Oj.req_field "level" (fun j -> Oj.int_ j) j in
       Ok (Tint { level })
     | other, _ -> Error ("mark: unknown variant: " ^ other))
  | `String s ->
    (match s with

     | other -> Error ("mark: unknown variant: " ^ other))
  | _ -> Error ("mark: expected single-key object")

and post_v1_widgets_response202_to_yojson (x : post_v1_widgets_response202) : Yojson.Safe.t =
  `Assoc
    (List.concat
    [
      [ ("job_id", `String x.job_id) ];
    ])

and post_v1_widgets_response202_of_yojson (j : Yojson.Safe.t) : (post_v1_widgets_response202, string) result =
  let open Oj in
  let* job_id = Oj.req_field "job_id" (fun j -> Oj.string_ j) j in
  Ok ({ job_id } : post_v1_widgets_response202)

and get_v1_widgets_widget_id_params_to_yojson (x : get_v1_widgets_widget_id_params) : Yojson.Safe.t =
  `Assoc
    (List.concat
    [
      [ ("widget_id", `String x.widget_id) ];
    ])

and get_v1_widgets_widget_id_params_of_yojson (j : Yojson.Safe.t) : (get_v1_widgets_widget_id_params, string) result =
  let open Oj in
  let* widget_id = Oj.req_field "widget_id" (fun j -> Oj.string_ j) j in
  Ok ({ widget_id } : get_v1_widgets_widget_id_params)

and patch_v1_widgets_widget_id_request_to_yojson (x : patch_v1_widgets_widget_id_request) : Yojson.Safe.t =
  `Assoc
    (List.concat
    [
      (match x.weight with Some v -> [ ("weight", `Float v) ] | None -> []);
    ])

and patch_v1_widgets_widget_id_request_of_yojson (j : Yojson.Safe.t) : (patch_v1_widgets_widget_id_request, string) result =
  let open Oj in
  let* weight = Oj.opt_field "weight" (fun j -> Oj.float_ j) j in
  Ok ({ weight } : patch_v1_widgets_widget_id_request)

and mixed_alias_to_yojson (v : mixed_alias) : Yojson.Safe.t = `List (List.map (fun x -> string_or_array_bool_to_yojson x) v)

and mixed_alias_of_yojson (j : Yojson.Safe.t) : (mixed_alias, string) result = Oj.list_ (fun j -> string_or_array_bool_of_yojson j) j

and containers_to_yojson (x : containers) : Yojson.Safe.t =
  `Assoc
    (List.concat
    [
      [ ("tags", `List (List.map (fun x -> `String x) x.tags)) ];
      [ ("matrix", `List (List.map (fun x -> `List (List.map (fun x -> `Int x) x)) x.matrix)) ];
      [ ("by_key", `Assoc (List.map (fun (k, x) -> (k, `Float x)) x.by_key)) ];
      [ ("free_form", `Assoc (List.map (fun (k, x) -> (k, x)) x.free_form)) ];
      [ ("nested", containers_nested_to_yojson x.nested) ];
    ])

and containers_of_yojson (j : Yojson.Safe.t) : (containers, string) result =
  let open Oj in
  let* tags = Oj.req_field "tags" (fun j -> Oj.list_ (fun j -> Oj.string_ j) j) j in
  let* matrix = Oj.req_field "matrix" (fun j -> Oj.list_ (fun j -> Oj.list_ (fun j -> Oj.int_ j) j) j) j in
  let* by_key = Oj.req_field "by_key" (fun j -> Oj.dict_ (fun j -> Oj.float_ j) j) j in
  let* free_form = Oj.req_field "free_form" (fun j -> Oj.dict_ (fun j -> Ok j) j) j in
  let* nested = Oj.req_field "nested" (fun j -> containers_nested_of_yojson j) j in
  Ok ({ tags; matrix; by_key; free_form; nested } : containers)

and issue_loop_to_yojson (x : issue_loop) : Yojson.Safe.t =
  `Assoc
    (List.concat
    [
      [ ("kind", issue_loop_kind_to_yojson x.kind) ];
      [ ("path", `List (List.map (fun x -> `String x) x.path)) ];
    ])

and issue_loop_of_yojson (j : Yojson.Safe.t) : (issue_loop, string) result =
  let open Oj in
  let* kind = Oj.req_field "kind" (fun j -> issue_loop_kind_of_yojson j) j in
  let* path = Oj.req_field "path" (fun j -> Oj.list_ (fun j -> Oj.string_ j) j) j in
  Ok ({ kind; path } : issue_loop)

and issue_broken_link_to_yojson (x : issue_broken_link) : Yojson.Safe.t =
  `Assoc
    (List.concat
    [
      [ ("kind", issue_broken_link_kind_to_yojson x.kind) ];
      [ ("from", `String x.from) ];
      [ ("to", `String x.to_) ];
    ])

and issue_broken_link_of_yojson (j : Yojson.Safe.t) : (issue_broken_link, string) result =
  let open Oj in
  let* kind = Oj.req_field "kind" (fun j -> issue_broken_link_kind_of_yojson j) j in
  let* from = Oj.req_field "from" (fun j -> Oj.string_ j) j in
  let* to_ = Oj.req_field "to" (fun j -> Oj.string_ j) j in
  Ok ({ kind; from; to_ } : issue_broken_link)

and get_v1_widgets_params_to_yojson (x : get_v1_widgets_params) : Yojson.Safe.t =
  `Assoc
    (List.concat
    [
      [ ("limit", `Int x.limit) ];
      (match x.cursor with Some v -> [ ("cursor", `String v) ] | None -> []);
      (match x.order with Some v -> [ ("order", order_to_yojson v) ] | None -> []);
    ])

and get_v1_widgets_params_of_yojson (j : Yojson.Safe.t) : (get_v1_widgets_params, string) result =
  let open Oj in
  let* limit = Oj.req_field "limit" (fun j -> Oj.check_ "maximum=100" (fun v -> v <= 100) (Oj.check_ "minimum=1" (fun v -> v >= 1) (Oj.int_ j))) j in
  let* cursor = Oj.opt_field "cursor" (fun j -> Oj.string_ j) j in
  let* order = Oj.opt_field "order" (fun j -> order_of_yojson j) j in
  Ok ({ limit; cursor; order } : get_v1_widgets_params)

and nullables_to_yojson (x : nullables) : Yojson.Safe.t =
  `Assoc
    (List.concat
    [
      [ ("maybe_text", (match x.maybe_text with Some x -> `String x | None -> `Null)) ];
      [ ("maybe_size", (match x.maybe_size with Some x -> size_to_yojson x | None -> `Null)) ];
      [ ("maybe_list", (match x.maybe_list with Some x -> `List (List.map (fun x -> `String x) x) | None -> `Null)) ];
      [ ("only_one", `String x.only_one) ];
      [ ("inline_enum", inline_enum_to_yojson x.inline_enum) ];
      [ ("literal_union", literal_union_to_yojson x.literal_union) ];
    ])

and nullables_of_yojson (j : Yojson.Safe.t) : (nullables, string) result =
  let open Oj in
  let* maybe_text = Oj.req_field "maybe_text" (fun j -> Oj.nullable_ (fun j -> Oj.string_ j) j) j in
  let* maybe_size = Oj.req_field "maybe_size" (fun j -> Oj.nullable_ (fun j -> size_of_yojson j) j) j in
  let* maybe_list = Oj.req_field "maybe_list" (fun j -> Oj.nullable_ (fun j -> Oj.list_ (fun j -> Oj.string_ j) j) j) j in
  let* only_one = Oj.req_field "only_one" (fun j -> Oj.string_ j) j in
  let* inline_enum = Oj.req_field "inline_enum" (fun j -> inline_enum_of_yojson j) j in
  let* literal_union = Oj.req_field "literal_union" (fun j -> literal_union_of_yojson j) j in
  Ok ({ maybe_text; maybe_size; maybe_list; only_one; inline_enum; literal_union } : nullables)

and widget_to_yojson (x : widget) : Yojson.Safe.t =
  `Assoc
    (List.concat
    [
      [ ("id", `String x.id) ];
      [ ("created_at", `String x.created_at) ];
      [ ("size", size_to_yojson x.size) ];
      [ ("weight", `Float x.weight) ];
    ])

and widget_of_yojson (j : Yojson.Safe.t) : (widget, string) result =
  let open Oj in
  let* id = Oj.req_field "id" (fun j -> Oj.string_ j) j in
  let* created_at = Oj.req_field "created_at" (fun j -> Oj.string_ j) j in
  let* size = Oj.req_field "size" (fun j -> size_of_yojson j) j in
  let* weight = Oj.req_field "weight" (fun j -> Oj.float_ j) j in
  Ok ({ id; created_at; size; weight } : widget)

and measure_or_float_to_yojson (v : measure_or_float) : Yojson.Safe.t =
  match v with
  | Measure v -> measure_to_yojson v
  | Float v -> `Float v

and measure_or_float_of_yojson (j : Yojson.Safe.t) : (measure_or_float, string) result =
  let open Oj in
  ignore (let* x = Ok () in Ok x);
  (match measure_of_yojson j with
     | Ok v -> Ok (Measure v)
     | Error _ -> (match Oj.float_ j with
     | Ok v -> Ok (Float v)
     | Error _ -> Error ("measure_or_float: no variant matched")))

and event_to_yojson (v : event) : Yojson.Safe.t =
  match v with
  | EventCreated { at } ->
    `Assoc
      (("_tag", `String "EventCreated")
       :: (List.concat
      [
        [ ("at", `String at) ];
      ]))
  | EventDeleted { reason } ->
    `Assoc
      (("_tag", `String "EventDeleted")
       :: (List.concat
      [
        [ ("reason", `String reason) ];
      ]))

and event_of_yojson (j : Yojson.Safe.t) : (event, string) result =
  let open Oj in
  let* tag = Oj.req_field "_tag" Oj.string_ j in
  match tag with
  | "EventCreated" ->
    let* at = Oj.req_field "at" (fun j -> Oj.string_ j) j in
    Ok (EventCreated { at })
  | "EventDeleted" ->
    let* reason = Oj.req_field "reason" (fun j -> Oj.string_ j) j in
    Ok (EventDeleted { reason })
  | other -> Error ("event: unknown _tag: " ^ other)

and issue_loop_or_issue_broken_link_to_yojson (v : issue_loop_or_issue_broken_link) : Yojson.Safe.t =
  match v with
  | IssueLoop { path } ->
    `Assoc
      (("kind", `String "IssueLoop")
       :: (List.concat
      [
        [ ("path", `List (List.map (fun x -> `String x) path)) ];
      ]))
  | IssueBrokenLink { from; to_ } ->
    `Assoc
      (("kind", `String "IssueBrokenLink")
       :: (List.concat
      [
        [ ("from", `String from) ];
        [ ("to", `String to_) ];
      ]))

and issue_loop_or_issue_broken_link_of_yojson (j : Yojson.Safe.t) : (issue_loop_or_issue_broken_link, string) result =
  let open Oj in
  let* tag = Oj.req_field "kind" Oj.string_ j in
  match tag with
  | "IssueLoop" ->
    let* path = Oj.req_field "path" (fun j -> Oj.list_ (fun j -> Oj.string_ j) j) j in
    Ok (IssueLoop { path })
  | "IssueBrokenLink" ->
    let* from = Oj.req_field "from" (fun j -> Oj.string_ j) j in
    let* to_ = Oj.req_field "to" (fun j -> Oj.string_ j) j in
    Ok (IssueBrokenLink { from; to_ })
  | other -> Error ("issue_loop_or_issue_broken_link: unknown kind: " ^ other)

and issue_to_yojson (v : issue) : Yojson.Safe.t =
  match v with
  | LoopFound { path } ->
    `Assoc
      (("kind", `String "loop_found")
       :: (List.concat
      [
        [ ("path", `List (List.map (fun x -> `String x) path)) ];
      ]))
  | BrokenLink { from; to_ } ->
    `Assoc
      (("kind", `String "broken_link")
       :: (List.concat
      [
        [ ("from", `String from) ];
        [ ("to", `String to_) ];
      ]))

and issue_of_yojson (j : Yojson.Safe.t) : (issue, string) result =
  let open Oj in
  let* tag = Oj.req_field "kind" Oj.string_ j in
  match tag with
  | "loop_found" ->
    let* path = Oj.req_field "path" (fun j -> Oj.list_ (fun j -> Oj.string_ j) j) j in
    Ok (LoopFound { path })
  | "broken_link" ->
    let* from = Oj.req_field "from" (fun j -> Oj.string_ j) j in
    let* to_ = Oj.req_field "to" (fun j -> Oj.string_ j) j in
    Ok (BrokenLink { from; to_ })
  | other -> Error ("issue: unknown kind: " ^ other)

and widget_alias_to_yojson (v : widget_alias) : Yojson.Safe.t = widget_to_yojson v

and widget_alias_of_yojson (j : Yojson.Safe.t) : (widget_alias, string) result = widget_of_yojson j

and get_v1_widgets_response_to_yojson (v : get_v1_widgets_response) : Yojson.Safe.t = `List (List.map (fun x -> widget_to_yojson x) v)

and get_v1_widgets_response_of_yojson (j : Yojson.Safe.t) : (get_v1_widgets_response, string) result = Oj.list_ (fun j -> widget_of_yojson j) j

and post_v1_widgets_response_to_yojson (v : post_v1_widgets_response) : Yojson.Safe.t = widget_to_yojson v

and post_v1_widgets_response_of_yojson (j : Yojson.Safe.t) : (post_v1_widgets_response, string) result = widget_of_yojson j

and get_v1_widgets_widget_id_response_to_yojson (v : get_v1_widgets_widget_id_response) : Yojson.Safe.t = widget_to_yojson v

and get_v1_widgets_widget_id_response_of_yojson (j : Yojson.Safe.t) : (get_v1_widgets_widget_id_response, string) result = widget_of_yojson j

and post_v1_widgets_widget_id_response_to_yojson (v : post_v1_widgets_widget_id_response) : Yojson.Safe.t = widget_to_yojson v

and post_v1_widgets_widget_id_response_of_yojson (j : Yojson.Safe.t) : (post_v1_widgets_widget_id_response, string) result = widget_of_yojson j

and patch_v1_widgets_widget_id_response_to_yojson (v : patch_v1_widgets_widget_id_response) : Yojson.Safe.t = widget_to_yojson v

and patch_v1_widgets_widget_id_response_of_yojson (j : Yojson.Safe.t) : (patch_v1_widgets_widget_id_response, string) result = widget_of_yojson j

and post_v1_widgets_request_to_yojson (v : post_v1_widgets_request) : Yojson.Safe.t = widget_to_yojson v

and post_v1_widgets_request_of_yojson (j : Yojson.Safe.t) : (post_v1_widgets_request, string) result = widget_of_yojson j

and shape_distinct_to_yojson (x : shape_distinct) : Yojson.Safe.t =
  `Assoc
    (List.concat
    [
      [ ("amount", measure_or_float_to_yojson x.amount) ];
      [ ("mixed_list", `List (List.map (fun x -> string_or_int_to_yojson x) x.mixed_list)) ];
    ])

and shape_distinct_of_yojson (j : Yojson.Safe.t) : (shape_distinct, string) result =
  let open Oj in
  let* amount = Oj.req_field "amount" (fun j -> measure_or_float_of_yojson j) j in
  let* mixed_list = Oj.req_field "mixed_list" (fun j -> Oj.list_ (fun j -> string_or_int_of_yojson j) j) j in
  Ok ({ amount; mixed_list } : shape_distinct)

and envelope_to_yojson (x : envelope) : Yojson.Safe.t =
  `Assoc
    (List.concat
    [
      [ ("payload", issue_loop_or_issue_broken_link_to_yojson x.payload) ];
      [ ("event", event_to_yojson x.event) ];
      [ ("phase", phase_to_yojson x.phase) ];
      [ ("mark", mark_to_yojson x.mark) ];
    ])

and envelope_of_yojson (j : Yojson.Safe.t) : (envelope, string) result =
  let open Oj in
  let* payload = Oj.req_field "payload" (fun j -> issue_loop_or_issue_broken_link_of_yojson j) j in
  let* event = Oj.req_field "event" (fun j -> event_of_yojson j) j in
  let* phase = Oj.req_field "phase" (fun j -> phase_of_yojson j) j in
  let* mark = Oj.req_field "mark" (fun j -> mark_of_yojson j) j in
  Ok ({ payload; event; phase; mark } : envelope)