// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";

function printPrimitive(p) {
  switch (p) {
    case "PString" :
      return "string";
    case "PFloat" :
      return "float";
    case "PInt" :
      return "int";
    case "PBool" :
      return "bool";
    case "PUnit" :
      return "unit";
  }
}

function printType(t) {
  switch (t.TAG) {
    case "Primitive" :
      return printPrimitive(t._0);
    case "Option" :
      return `option<` + printType(t._0) + `>`;
    case "Nullable" :
      return `Nullable.t<` + printType(t._0) + `>`;
    case "Array" :
      return `array<` + printType(t._0) + `>`;
    case "Dict" :
      return `Dict.t<` + printType(t._0) + `>`;
    case "Named" :
      return t._0;
    case "Enum" :
      let variants = t._0.map(v => `#` + v).join(" | ");
      return `[` + variants + `]`;
    case "InlineRecord" :
      return printRecord(t._0);
    case "InlineVariant" :
      return printVariantCases(t._0);
  }
}

function printField(field) {
  let typeStr = printType(field.type_);
  let fieldType = Core__Array.reduce(field.annotations, typeStr, (acc, ann) => {
    if (typeof ann !== "object" && ann === "SNull") {
      return `@s.null ` + acc;
    } else {
      return acc;
    }
  });
  let asAttr = Core__Option.getOr(Core__Array.findMap(field.annotations, ann => {
    if (typeof ann !== "object" || ann.TAG !== "As") {
      return;
    } else {
      return `@as("` + ann._0 + `") `;
    }
  }), "");
  return asAttr + field.name + `: ` + fieldType;
}

function printRecord(fields) {
  if (fields.length === 0) {
    return "{}";
  }
  let fieldStrs = fields.map(printField);
  return `{\n  ` + fieldStrs.join(",\n  ") + `\n}`;
}

function printVariantCase(c) {
  let payloadStr = printType(c.payload);
  return c.tag + `(` + payloadStr + `)`;
}

function printVariantCases(cases) {
  let caseStrs = cases.map(printVariantCase);
  return `[` + caseStrs.map(c => `#` + c).join(" | ") + `]`;
}

function printAnnotation(ann) {
  if (typeof ann === "object") {
    if (ann.TAG === "Tag") {
      return `@tag("` + ann._0 + `")`;
    } else {
      return;
    }
  }
  switch (ann) {
    case "GenType" :
      return "@genType";
    case "Schema" :
      return "@schema";
    case "Unboxed" :
      return "@unboxed";
    case "SNull" :
      return;
  }
}

function printAnnotations(annotations) {
  return Core__Array.filterMap(annotations, printAnnotation).join("\n");
}

function printTypeDef(typeDef) {
  let annotations = printAnnotations(typeDef.annotations);
  let fields = typeDef.kind;
  let body;
  switch (fields.TAG) {
    case "RecordDef" :
      body = printRecord(fields._0);
      break;
    case "VariantDef" :
      body = fields._0.map(printVariantCase).join(" | ");
      break;
    case "AliasDef" :
      body = printType(fields._0);
      break;
  }
  return annotations + `\ntype ` + typeDef.name + ` = ` + body;
}

function print(module_) {
  let typeDefs = module_.types.map(printTypeDef).join("\n\n");
  return module_.preamble + "\n\n" + typeDefs;
}

export {
  printPrimitive,
  printType,
  printField,
  printRecord,
  printVariantCase,
  printVariantCases,
  printAnnotation,
  printAnnotations,
  printTypeDef,
  print,
}
/* No side effect */
