// Generated by ReScript, PLEASE EDIT WITH CARE

import * as IR from "./IR.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.mjs";
import * as CodegenHelpers from "./CodegenHelpers.mjs";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";
import * as CodegenTransforms from "./CodegenTransforms.mjs";

let rustKeywords = [
  "as",
  "async",
  "await",
  "break",
  "const",
  "continue",
  "crate",
  "dyn",
  "else",
  "enum",
  "extern",
  "false",
  "fn",
  "for",
  "if",
  "impl",
  "in",
  "let",
  "loop",
  "match",
  "mod",
  "move",
  "mut",
  "pub",
  "ref",
  "return",
  "self",
  "static",
  "struct",
  "super",
  "trait",
  "true",
  "type",
  "union",
  "unsafe",
  "use",
  "where",
  "while",
  "abstract",
  "become",
  "box",
  "do",
  "final",
  "macro",
  "override",
  "priv",
  "try",
  "typeof",
  "unsized",
  "virtual",
  "yield"
];

function isValidIdent(s) {
  if (s !== "") {
    return s.split("").every((c, i) => {
      let code = c.charCodeAt(0);
      let alpha = code >= 97.0 && code <= 122.0 || code >= 65.0 && code <= 90.0 || code === 95.0;
      let digit = code >= 48.0 && code <= 57.0;
      if (i === 0) {
        return alpha;
      } else if (alpha) {
        return true;
      } else {
        return digit;
      }
    });
  } else {
    return false;
  }
}

function rustFieldName(wire) {
  let sanitized = isValidIdent(wire) ? wire : wire.replace(/[^A-Za-z0-9_]/g, "_");
  if (rustKeywords.includes(sanitized)) {
    return sanitized + "_";
  } else {
    return sanitized;
  }
}

let typeName = CodegenHelpers.ucFirst;

function variantName(value) {
  let sanitized = isValidIdent(value) ? value : value.replace(/[^A-Za-z0-9_]/g, "_");
  return CodegenHelpers.ucFirst(CodegenTransforms.camelize(sanitized));
}

function wireName(field) {
  return Core__Option.getOr(Core__Array.findMap(field.annotations, ann => {
    if (typeof ann !== "object" || ann.TAG !== "As") {
      return;
    } else {
      return ann._0;
    }
  }), field.name);
}

function wireTag(c) {
  return Core__Option.getOr(c.asValue, c.tag);
}

function printType(_t) {
  while (true) {
    let t = _t;
    if (typeof t !== "object") {
      return "serde_json::Value";
    }
    switch (t.TAG) {
      case "Primitive" :
        switch (t._0) {
          case "PString" :
            return "String";
          case "PFloat" :
            return "f64";
          case "PInt" :
            return "i64";
          case "PBool" :
            return "bool";
          case "PUnit" :
            return "()";
        }
      case "Option" :
      case "Nullable" :
        break;
      case "Array" :
        return `Vec<` + printType(t._0) + `>`;
      case "Dict" :
        return `std::collections::HashMap<String, ` + printType(t._0) + `>`;
      case "Named" :
        return CodegenHelpers.ucFirst(t._0);
      case "Enum" :
        return "String";
      case "Refined" :
        _t = t._0;
        continue;
      default:
        return "serde_json::Value";
    }
    return `Option<` + printType(t._0) + `>`;
  };
}

function numLit(v, isInt) {
  if (isInt) {
    return (v | 0).toString();
  } else if (v.toString().includes(".")) {
    return v.toString();
  } else {
    return v.toString() + ".0";
  }
}

function numToken(v, isInt) {
  return numLit(v, isInt).replace(/[.\-]/g, "_");
}

function refinementToken(r, isInt) {
  switch (r._tag) {
    case "MinLength" :
      return `minlen` + r._0.toString();
    case "MaxLength" :
      return `maxlen` + r._0.toString();
    case "Format" :
    case "Pattern" :
      return;
    case "Gte" :
      return `gte` + numToken(r._0, isInt);
    case "Lte" :
      return `lte` + numToken(r._0, isInt);
    case "Gt" :
      return `gt` + numToken(r._0, isInt);
    case "Lt" :
      return `lt` + numToken(r._0, isInt);
    case "MultipleOf" :
      return `mult` + numToken(r._0, isInt);
  }
}

function refinementCond(r, isInt) {
  switch (r._tag) {
    case "MinLength" :
      return `v.chars().count() >= ` + r._0.toString();
    case "MaxLength" :
      return `v.chars().count() <= ` + r._0.toString();
    case "Format" :
    case "Pattern" :
      return;
    case "Gte" :
      return `*v >= ` + numLit(r._0, isInt);
    case "Lte" :
      return `*v <= ` + numLit(r._0, isInt);
    case "Gt" :
      return `*v > ` + numLit(r._0, isInt);
    case "Lt" :
      return `*v < ` + numLit(r._0, isInt);
    case "MultipleOf" :
      let x = r._0;
      return isInt ? `*v % ` + numLit(x, isInt) + ` == 0` : `(*v % ` + numLit(x, isInt) + `).abs() < f64::EPSILON`;
  }
}

function validatorFor(t) {
  let build = (inner, refs, optional) => {
    let isInt = Primitive_object.equal(inner, {
      TAG: "Primitive",
      _0: "PInt"
    });
    let tokens = Core__Array.filterMap(refs, r => refinementToken(r, isInt));
    if (tokens.length === 0) {
      return;
    }
    let base = printType(inner).toLowerCase();
    return {
      fnName: `de_` + (
        optional ? "opt_" : ""
      ) + base + `_` + tokens.join("_"),
      rustType: printType(inner),
      optional: optional,
      isInt: isInt,
      refs: refs
    };
  };
  if (typeof t !== "object") {
    return;
  }
  switch (t.TAG) {
    case "Option" :
      let match = t._0;
      if (typeof match !== "object" || match.TAG !== "Refined") {
        return;
      } else {
        return build(match._0, match._1, true);
      }
    case "Nullable" :
      let match$1 = t._0;
      if (typeof match$1 !== "object" || match$1.TAG !== "Refined") {
        return;
      } else {
        return build(match$1._0, match$1._1, true);
      }
    case "Refined" :
      return build(t._0, t._1, false);
    default:
      return;
  }
}

function printValidator(v) {
  let checks = Core__Array.filterMap(v.refs, r => Core__Option.map(refinementCond(r, v.isInt), cond => [
    cond,
    CodegenHelpers.refinementLabel(r)
  ])).map(param => `    if !(` + param[0] + `) {\n        return Err(serde::de::Error::custom("` + param[1] + `"));\n    }`).join("\n");
  let match = v.optional ? [
      `Option<` + v.rustType + `>`,
      `    let opt = Option::<` + v.rustType + `>::deserialize(deserializer)?;\n    let v = match opt.as_ref() {\n        Some(v) => v,\n        None => return Ok(None),\n    };`,
      "    Ok(opt)"
    ] : [
      v.rustType,
      `    let value = ` + v.rustType + `::deserialize(deserializer)?;\n    let v = &value;`,
      "    Ok(value)"
    ];
  return `fn ` + v.fnName + `<'de, D>(deserializer: D) -> Result<` + match[0] + `, D::Error>\nwhere\n    D: serde::Deserializer<'de>,\n{\n` + match[1] + `\n` + checks + `\n` + match[2] + `\n}`;
}

function printField(f, indent) {
  let wire = wireName(f);
  let name = rustFieldName(wire);
  let attrs = [];
  if (name !== wire) {
    attrs.push(indent + `#[serde(rename = "` + wire + `")]`);
  }
  let v = validatorFor(f.type_);
  if (v !== undefined) {
    attrs.push(indent + `#[serde(deserialize_with = "` + v.fnName + `")]`);
  }
  let match = f.type_;
  if (typeof match === "object" && match.TAG === "Option") {
    attrs.push(indent + `#[serde(default, skip_serializing_if = "Option::is_none")]`);
  }
  let lines = attrs.concat([indent + `pub ` + name + `: ` + printType(f.type_) + `,`]);
  return lines.join("\n");
}

function printCaseField(f, indent) {
  let wire = wireName(f);
  let name = rustFieldName(wire);
  let attrs = name !== wire ? [indent + `#[serde(rename = "` + wire + `")]`] : [];
  let v = validatorFor(f.type_);
  let attrs$1 = v !== undefined ? attrs.concat([indent + `#[serde(deserialize_with = "` + v.fnName + `")]`]) : attrs;
  let match = f.type_;
  if (typeof match === "object" && match.TAG === "Option") {
    return attrs$1.concat([
      indent + `#[serde(default, skip_serializing_if = "Option::is_none")]`,
      indent + name + `: ` + printType(f.type_) + `,`
    ]).join("\n");
  }
  return attrs$1.concat([indent + name + `: ` + printType(f.type_) + `,`]).join("\n");
}

function printVariantCase(c) {
  let renameAttr = wireTag(c) !== c.tag ? [`    #[serde(rename = "` + wireTag(c) + `")]`] : [];
  let fields = c.payload;
  let decl;
  let exit = 0;
  if (typeof fields !== "object") {
    exit = 1;
  } else {
    switch (fields.TAG) {
      case "Primitive" :
        if (fields._0 === "PUnit") {
          decl = `    ` + c.tag + `,`;
        } else {
          exit = 1;
        }
        break;
      case "InlineRecord" :
        let fields$1 = fields._0;
        if (fields$1.length !== 0) {
          let fieldLines = fields$1.map(f => printCaseField(f, "        ")).join("\n");
          decl = `    ` + c.tag + ` {\n` + fieldLines + `\n    },`;
        } else {
          decl = `    ` + c.tag + `,`;
        }
        break;
      default:
        exit = 1;
    }
  }
  if (exit === 1) {
    decl = `    ` + c.tag + `(` + printType(fields) + `),`;
  }
  return renameAttr.concat([decl]).join("\n");
}

let derive = "#[derive(Debug, Clone, Serialize, Deserialize)]";

function printTypeDef(typeDef) {
  let name = CodegenHelpers.ucFirst(typeDef.name);
  let listEncoded = typeDef.annotations.includes("ListEncoded");
  let fields = typeDef.kind;
  switch (fields.TAG) {
    case "RecordDef" :
      let fieldLines = fields._0.map(f => printField(f, "    ")).join("\n");
      return derive + `\npub struct ` + name + ` {\n` + fieldLines + `\n}`;
    case "VariantDef" :
      let repr = fields._1;
      let unboxed = typeDef.annotations.includes("Unboxed");
      let reprAttr = unboxed ? ["#[serde(untagged)]"] : (
          typeof repr !== "object" ? [] : [`#[serde(tag = "` + repr._0 + `")]`]
        );
      let caseLines = fields._0.map(printVariantCase).join("\n");
      return [derive].concat(reprAttr).concat([`pub enum ` + name + ` {\n` + caseLines + `\n}`]).join("\n");
    case "AliasDef" :
      let values = fields._0;
      if (typeof values === "object" && values.TAG === "Enum") {
        let values$1 = values._0;
        if (listEncoded) {
          let variants = values$1.map(v => `    ` + variantName(v) + `,`).join("\n");
          let intoArms = values$1.map(v => `            ` + name + `::` + variantName(v) + ` => "` + v + `",`).join("\n");
          let fromArms = values$1.map(v => `                "` + v + `" => Ok(` + name + `::` + variantName(v) + `),`).join("\n");
          return derive + `
#[serde(into = "Vec<String>", try_from = "Vec<String>")]
pub enum ` + name + ` {
` + variants + `
}

impl From<` + name + `> for Vec<String> {
    fn from(v: ` + name + `) -> Self {
        vec![match v {
` + intoArms + `
        }
        .to_string()]
    }
}

impl TryFrom<Vec<String>> for ` + name + ` {
    type Error = String;
    fn try_from(v: Vec<String>) -> Result<Self, Self::Error> {
        match v.as_slice() {
            [s] => match s.as_str() {
` + fromArms + `
                other => Err(format!("` + name + `: unknown variant: {other}")),
            },
            _ => Err("` + name + `: expected single-element list".to_string()),
        }
    }
}`;
        }
        let variants$1 = values$1.map(v => {
          let ctor = variantName(v);
          let rename = ctor !== v ? [`    #[serde(rename = "` + v + `")]`] : [];
          return rename.concat([`    ` + ctor + `,`]).join("\n");
        });
        return derive + `\npub enum ` + name + ` {\n` + variants$1.join("\n") + `\n}`;
      }
      return `pub type ` + name + ` = ` + printType(values) + `;`;
  }
}

function collectValidators(module_) {
  let seen = {};
  let result = [];
  let claim = t => {
    let v = validatorFor(t);
    if (v !== undefined && Core__Option.isNone(seen[v.fnName])) {
      seen[v.fnName] = true;
      result.push(v);
      return;
    }
  };
  module_.types.forEach(def => {
    let fields = def.kind;
    switch (fields.TAG) {
      case "RecordDef" :
        fields._0.forEach(f => claim(f.type_));
        return;
      case "VariantDef" :
        fields._0.forEach(c => {
          let fields = c.payload;
          if (typeof fields !== "object") {
            return claim(fields);
          }
          if (fields.TAG !== "InlineRecord") {
            return claim(fields);
          }
          fields._0.forEach(f => claim(f.type_));
        });
        return;
      case "AliasDef" :
        return claim(fields._0);
    }
  });
  return result;
}

function print(module_) {
  let body = module_.types.map(printTypeDef).join("\n\n");
  let validators = collectValidators(module_);
  let validatorBlock = validators.length === 0 ? "" : "\n\n" + validators.map(printValidator).join("\n\n");
  return `// Generated by osury. Do not edit.

use serde::{Deserialize, Serialize};

` + body + validatorBlock + `
`;
}

function droppedRefinements(m) {
  return IR.droppedRefinementWarnings(m, "Rust", r => {
    switch (r._tag) {
      case "Format" :
      case "Pattern" :
        return false;
      default:
        return true;
    }
  });
}

export {
  rustKeywords,
  isValidIdent,
  rustFieldName,
  typeName,
  variantName,
  wireName,
  wireTag,
  printType,
  numLit,
  numToken,
  refinementToken,
  refinementCond,
  validatorFor,
  printValidator,
  printField,
  printCaseField,
  printVariantCase,
  derive,
  printTypeDef,
  collectValidators,
  print,
  droppedRefinements,
}
/* No side effect */
