// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Array from "@rescript/core/src/Core__Array.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.mjs";
import * as CodegenHelpers from "./CodegenHelpers.mjs";

function toSnake(s) {
  return s.split("").map(c => {
    let code = c.charCodeAt(0);
    if (code >= 65.0 && code <= 90.0) {
      return "_" + c.toLowerCase();
    } else {
      return c;
    }
  }).join("").replace(/^_/, "").replace(/_+/g, "_");
}

let ocamlKeywords = [
  "and",
  "as",
  "assert",
  "asr",
  "begin",
  "class",
  "constraint",
  "do",
  "done",
  "downto",
  "effect",
  "else",
  "end",
  "exception",
  "external",
  "false",
  "for",
  "fun",
  "function",
  "functor",
  "if",
  "in",
  "include",
  "inherit",
  "initializer",
  "land",
  "lazy",
  "let",
  "lor",
  "lsl",
  "lsr",
  "lxor",
  "match",
  "method",
  "mod",
  "module",
  "mutable",
  "new",
  "nonrec",
  "object",
  "of",
  "open",
  "or",
  "private",
  "rec",
  "sig",
  "struct",
  "then",
  "to",
  "true",
  "try",
  "type",
  "val",
  "virtual",
  "when",
  "while",
  "with"
];

function escapeKeyword(name) {
  if (ocamlKeywords.includes(name)) {
    return name + "_";
  } else {
    return name;
  }
}

function wireName(field) {
  return Core__Option.getOr(Core__Array.findMap(field.annotations, ann => {
    if (typeof ann !== "object" || ann.TAG !== "As") {
      return;
    } else {
      return ann._0;
    }
  }), field.name);
}

function fieldName(field) {
  return escapeKeyword(wireName(field));
}

function typeName(name) {
  return escapeKeyword(toSnake(name));
}

function enumConstructor(value) {
  let sanitized = CodegenHelpers.ucFirst(value.replace(/[^A-Za-z0-9_]/g, "_"));
  if (sanitized === "" || sanitized.charCodeAt(0) >= 48.0 && sanitized.charCodeAt(0) <= 57.0) {
    return "V" + sanitized;
  } else {
    return sanitized;
  }
}

function printType(_t) {
  while (true) {
    let t = _t;
    if (typeof t !== "object") {
      return "Yojson.Safe.t";
    }
    switch (t.TAG) {
      case "Primitive" :
        switch (t._0) {
          case "PString" :
            return "string";
          case "PFloat" :
            return "float";
          case "PInt" :
            return "int";
          case "PBool" :
            return "bool";
          case "PUnit" :
            return "unit";
        }
      case "Option" :
      case "Nullable" :
        break;
      case "Array" :
        return printType(t._0) + ` list`;
      case "Dict" :
        return `(string * ` + printType(t._0) + `) list`;
      case "Named" :
        return escapeKeyword(toSnake(t._0));
      case "Enum" :
        return "string";
      case "Refined" :
        _t = t._0;
        continue;
      default:
        return "Yojson.Safe.t";
    }
    return printType(t._0) + ` option`;
  };
}

function printRecordFields(fields) {
  return fields.map(f => `  ` + escapeKeyword(wireName(f)) + ` : ` + printType(f.type_) + `;`).join("\n");
}

function printVariantCaseDecl(c) {
  let fields = c.payload;
  if (typeof fields === "object") {
    switch (fields.TAG) {
      case "Primitive" :
        if (fields._0 === "PUnit") {
          return `  | ` + c.tag;
        }
        break;
      case "InlineRecord" :
        let fields$1 = fields._0;
        if (fields$1.length === 0) {
          return `  | ` + c.tag;
        }
        let fieldDecls = fields$1.map(f => escapeKeyword(wireName(f)) + ` : ` + printType(f.type_)).join("; ");
        return `  | ` + c.tag + ` of { ` + fieldDecls + ` }`;
    }
  }
  return `  | ` + c.tag + ` of ` + printType(fields);
}

function printTypeDecl(typeDef) {
  let name = escapeKeyword(toSnake(typeDef.name));
  let fields = typeDef.kind;
  switch (fields.TAG) {
    case "RecordDef" :
      return `type ` + name + ` = {\n` + printRecordFields(fields._0) + `\n}`;
    case "VariantDef" :
      return `type ` + name + ` =\n` + fields._0.map(printVariantCaseDecl).join("\n");
    case "AliasDef" :
      let values = fields._0;
      if (typeof values === "object" && values.TAG === "Enum") {
        return `type ` + name + ` =\n` + values._0.map(v => `  | ` + enumConstructor(v)).join("\n");
      }
      return `type ` + name + ` = ` + printType(values);
  }
}

function encExpr(_t, v) {
  while (true) {
    let t = _t;
    if (typeof t !== "object") {
      return v;
    }
    switch (t.TAG) {
      case "Primitive" :
        switch (t._0) {
          case "PString" :
            return `\`String ` + v;
          case "PFloat" :
            return `\`Float ` + v;
          case "PInt" :
            return `\`Int ` + v;
          case "PBool" :
            return `\`Bool ` + v;
          case "PUnit" :
            return `\`Null`;
        }
      case "Option" :
      case "Nullable" :
        break;
      case "Array" :
        return `\`List (List.map (fun x -> ` + encExpr(t._0, "x") + `) ` + v + `)`;
      case "Dict" :
        return `\`Assoc (List.map (fun (k, x) -> (k, ` + encExpr(t._0, "x") + `)) ` + v + `)`;
      case "Named" :
        return escapeKeyword(toSnake(t._0)) + `_to_yojson ` + v;
      case "Enum" :
        return `\`String ` + v;
      case "Refined" :
        _t = t._0;
        continue;
      default:
        return v;
    }
    return `(match ` + v + ` with Some x -> ` + encExpr(t._0, "x") + ` | None -> \`Null)`;
  };
}

function encField(f, prefix) {
  return `("` + wireName(f) + `", ` + encExpr(f.type_, prefix + escapeKeyword(wireName(f))) + `)`;
}

function encFieldEntry(f, prefix) {
  let inner = f.type_;
  if (typeof inner === "object" && inner.TAG === "Option") {
    return `(match ` + prefix + escapeKeyword(wireName(f)) + ` with Some v -> [ ("` + wireName(f) + `", ` + encExpr(inner._0, "v") + `) ] | None -> [])`;
  }
  return `[ ` + encField(f, prefix) + ` ]`;
}

function encFieldEntries(fields, prefix, indent) {
  let entries = fields.map(f => indent + `  ` + encFieldEntry(f, prefix) + `;`).join("\n");
  return `(List.concat\n` + indent + `[\n` + entries + `\n` + indent + `])`;
}

function decExpr(_t, j) {
  while (true) {
    let t = _t;
    if (typeof t !== "object") {
      return `Ok ` + j;
    }
    switch (t.TAG) {
      case "Primitive" :
        switch (t._0) {
          case "PString" :
            return `Oj.string_ ` + j;
          case "PFloat" :
            return `Oj.float_ ` + j;
          case "PInt" :
            return `Oj.int_ ` + j;
          case "PBool" :
            return `Oj.bool_ ` + j;
          case "PUnit" :
            return `Oj.unit_ ` + j;
        }
      case "Option" :
      case "Nullable" :
        break;
      case "Array" :
        return `Oj.list_ (fun j -> ` + decExpr(t._0, "j") + `) ` + j;
      case "Dict" :
        return `Oj.dict_ (fun j -> ` + decExpr(t._0, "j") + `) ` + j;
      case "Named" :
        return escapeKeyword(toSnake(t._0)) + `_of_yojson ` + j;
      case "Enum" :
        return `Oj.string_ ` + j;
      case "Refined" :
        _t = t._0;
        continue;
      default:
        return `Ok ` + j;
    }
    return `Oj.nullable_ (fun j -> ` + decExpr(t._0, "j") + `) ` + j;
  };
}

function decFieldBinding(f, j) {
  let name = escapeKeyword(wireName(f));
  let wire = wireName(f);
  let inner = f.type_;
  if (typeof inner === "object") {
    switch (inner.TAG) {
      case "Option" :
        return `  let* ` + name + ` = Oj.opt_field "` + wire + `" (fun j -> ` + decExpr(inner._0, "j") + `) ` + j + ` in`;
      case "Nullable" :
        return `  let* ` + name + ` = Oj.req_field "` + wire + `" (fun j -> Oj.nullable_ (fun j -> ` + decExpr(inner._0, "j") + `) j) ` + j + ` in`;
    }
  }
  return `  let* ` + name + ` = Oj.req_field "` + wire + `" (fun j -> ` + decExpr(inner, "j") + `) ` + j + ` in`;
}

function recordToYojson(name, fields) {
  return name + `_to_yojson (x : ` + name + `) : Yojson.Safe.t =
  \`Assoc
    ` + encFieldEntries(fields, "x.", "    ");
}

function recordOfYojson(name, fields) {
  let bindings = fields.map(f => decFieldBinding(f, "j")).join("\n");
  let names = fields.map(fieldName).join("; ");
  return name + `_of_yojson (j : Yojson.Safe.t) : (` + name + `, string) result =
  let open Oj in
` + bindings + `
  Ok ({ ` + names + ` } : ` + name + `)`;
}

function wireTag(c) {
  return Core__Option.getOr(c.asValue, c.tag);
}

function variantToYojson(name, cases, repr, unboxed) {
  let arms = cases.map(c => {
    let match = c.payload;
    if (unboxed) {
      return `  | ` + c.tag + ` v -> ` + encExpr(match, "v");
    }
    if (typeof match === "object") {
      switch (match.TAG) {
        case "Primitive" :
          if (match._0 === "PUnit") {
            if (typeof repr !== "object") {
              return `  | ` + c.tag + ` -> \`String "` + wireTag(c) + `"`;
            } else {
              return `  | ` + c.tag + ` -> \`Assoc [ ("` + repr._0 + `", \`String "` + wireTag(c) + `") ]`;
            }
          }
          break;
        case "InlineRecord" :
          let fields = match._0;
          if (fields.length === 0) {
            if (typeof repr !== "object") {
              return `  | ` + c.tag + ` -> \`Assoc [ ("` + wireTag(c) + `", \`Assoc []) ]`;
            } else {
              return `  | ` + c.tag + ` -> \`Assoc [ ("` + repr._0 + `", \`String "` + wireTag(c) + `") ]`;
            }
          }
          if (typeof repr !== "object") {
            let fieldNames = fields.map(fieldName).join("; ");
            let entries = encFieldEntries(fields, "", "        ");
            return `  | ` + c.tag + ` { ` + fieldNames + ` } ->
    \`Assoc
      [
        ( "` + wireTag(c) + `",
          \`Assoc
            ` + entries + ` );
      ]`;
          }
          let fieldNames$1 = fields.map(fieldName).join("; ");
          let entries$1 = encFieldEntries(fields, "", "      ");
          return `  | ` + c.tag + ` { ` + fieldNames$1 + ` } ->
    \`Assoc
      (("` + repr._0 + `", \`String "` + wireTag(c) + `")
       :: ` + entries$1 + `)`;
      }
    }
    if (typeof repr !== "object") {
      return `  | ` + c.tag + ` v -> \`Assoc [ ("` + wireTag(c) + `", ` + encExpr(match, "v") + `) ]`;
    } else {
      return `  | ` + c.tag + ` v ->
    (match ` + encExpr(match, "v") + ` with
     | \`Assoc kvs -> \`Assoc (("` + repr._0 + `", \`String "` + wireTag(c) + `") :: kvs)
     | other -> other)`;
    }
  });
  return name + `_to_yojson (v : ` + name + `) : Yojson.Safe.t =
  match v with
` + arms.join("\n");
}

function decCasePayload(c, j) {
  let fields = c.payload;
  if (typeof fields === "object") {
    switch (fields.TAG) {
      case "Primitive" :
        if (fields._0 === "PUnit") {
          return `    Ok ` + c.tag;
        }
        break;
      case "InlineRecord" :
        let fields$1 = fields._0;
        let bindings = fields$1.map(f => "  " + decFieldBinding(f, j)).join("\n");
        let names = fields$1.map(fieldName).join("; ");
        let construct = fields$1.length === 0 ? `Ok ` + c.tag : `Ok (` + c.tag + ` { ` + names + ` })`;
        return bindings + `
    ` + construct;
    }
  }
  return `    let* v = ` + decExpr(fields, j) + ` in
    Ok (` + c.tag + ` v)`;
}

function variantOfYojson(name, cases, repr, unboxed) {
  if (unboxed) {
    let attempts = Core__Array.reduceRight(cases, `Error ("` + name + `: no variant matched")`, (acc, c) => `(match ` + decExpr(c.payload, "j") + ` with
     | Ok v -> Ok (` + c.tag + ` v)
     | Error _ -> ` + acc + `)`);
    return name + `_of_yojson (j : Yojson.Safe.t) : (` + name + `, string) result =
  let open Oj in
  ignore (let* x = Ok () in Ok x);
  ` + attempts;
  }
  if (typeof repr !== "object") {
    let arms = cases.map(c => {
      let match = c.payload;
      if (typeof match === "object" && match.TAG === "Primitive" && match._0 === "PUnit") {
        return `     | "` + wireTag(c) + `", _ -> Ok ` + c.tag;
      }
      return `     | "` + wireTag(c) + `", j ->
` + decCasePayload(c, "j").split("\n").map(l => "   " + l).join("\n");
    });
    return name + `_of_yojson (j : Yojson.Safe.t) : (` + name + `, string) result =
  let open Oj in
  match j with
  | \`Assoc [ (tag, payload) ] ->
    (match tag, payload with
` + arms.join("\n") + `
     | other, _ -> Error ("` + name + `: unknown variant: " ^ other))
  | \`String s ->
    (match s with
` + Core__Array.filterMap(cases, c => {
      let match = c.payload;
      if (typeof match !== "object" || match.TAG !== "Primitive" || match._0 !== "PUnit") {
        return;
      } else {
        return `     | "` + wireTag(c) + `" -> Ok ` + c.tag;
      }
    }).join("\n") + `
     | other -> Error ("` + name + `: unknown variant: " ^ other))
  | _ -> Error ("` + name + `: expected single-key object")`;
  }
  let tagField = repr._0;
  let arms$1 = cases.map(c => `  | "` + wireTag(c) + `" ->
` + decCasePayload(c, "j"));
  return name + `_of_yojson (j : Yojson.Safe.t) : (` + name + `, string) result =
  let open Oj in
  let* tag = Oj.req_field "` + tagField + `" Oj.string_ j in
  match tag with
` + arms$1.join("\n") + `
  | other -> Error ("` + name + `: unknown ` + tagField + `: " ^ other)`;
}

function enumToYojson(name, values, listEncoded) {
  let wireForm = v => {
    if (listEncoded) {
      return `\`List [ \`String "` + v + `" ]`;
    } else {
      return `\`String "` + v + `"`;
    }
  };
  let arms = values.map(v => `  | ` + enumConstructor(v) + ` -> ` + wireForm(v)).join("\n");
  return name + `_to_yojson (v : ` + name + `) : Yojson.Safe.t =
  match v with
` + arms;
}

function enumOfYojson(name, values, listEncoded) {
  let wirePattern = v => {
    if (listEncoded) {
      return `\`List [ \`String "` + v + `" ]`;
    } else {
      return `\`String "` + v + `"`;
    }
  };
  let arms = values.map(v => `  | ` + wirePattern(v) + ` -> Ok ` + enumConstructor(v)).join("\n");
  return name + `_of_yojson (j : Yojson.Safe.t) : (` + name + `, string) result =
  match j with
` + arms + `
  | j -> Error ("` + name + `: unexpected " ^ Yojson.Safe.to_string j)`;
}

function aliasToYojson(name, t) {
  return name + `_to_yojson (v : ` + name + `) : Yojson.Safe.t = ` + encExpr(t, "v");
}

function aliasOfYojson(name, t) {
  return name + `_of_yojson (j : Yojson.Safe.t) : (` + name + `, string) result = ` + decExpr(t, "j");
}

function printCodecs(typeDef) {
  let name = escapeKeyword(toSnake(typeDef.name));
  let unboxed = typeDef.annotations.includes("Unboxed");
  let listEncoded = typeDef.annotations.includes("ListEncoded");
  let fields = typeDef.kind;
  switch (fields.TAG) {
    case "RecordDef" :
      let fields$1 = fields._0;
      return [
        recordToYojson(name, fields$1),
        recordOfYojson(name, fields$1)
      ];
    case "VariantDef" :
      let repr = fields._1;
      let cases = fields._0;
      return [
        variantToYojson(name, cases, repr, unboxed),
        variantOfYojson(name, cases, repr, unboxed)
      ];
    case "AliasDef" :
      let values = fields._0;
      if (typeof values === "object" && values.TAG === "Enum") {
        let values$1 = values._0;
        return [
          enumToYojson(name, values$1, listEncoded),
          enumOfYojson(name, values$1, listEncoded)
        ];
      }
      return [
        aliasToYojson(name, values),
        aliasOfYojson(name, values)
      ];
  }
}

let prelude = `(* Generated by osury. Do not edit. *)

module Oj = struct
  let ( let* ) = Result.bind

  let type_err name j =
    Error (Printf.sprintf "%s: unexpected %s" name (Yojson.Safe.to_string j))

  let string_ = function \`String s -> Ok s | j -> type_err "string" j

  let float_ = function
    | \`Float f -> Ok f
    | \`Int i -> Ok (float_of_int i)
    | j -> type_err "float" j

  let int_ = function \`Int i -> Ok i | j -> type_err "int" j
  let bool_ = function \`Bool b -> Ok b | j -> type_err "bool" j
  let unit_ = function \`Null -> Ok () | j -> type_err "unit" j

  let nullable_ dec = function
    | \`Null -> Ok None
    | j -> Result.map (fun v -> Some v) (dec j)

  let list_ dec = function
    | \`List xs ->
      List.fold_right
        (fun x acc ->
          let* acc = acc in
          let* v = dec x in
          Ok (v :: acc))
        xs (Ok [])
    | j -> type_err "list" j

  let dict_ dec = function
    | \`Assoc kvs ->
      List.fold_right
        (fun (k, x) acc ->
          let* acc = acc in
          let* v = dec x in
          Ok ((k, v) :: acc))
        kvs (Ok [])
    | j -> type_err "dict" j

  let req_field name dec j =
    match j with
    | \`Assoc kvs -> (
        match List.assoc_opt name kvs with
        | Some v -> dec v
        | None -> Error (Printf.sprintf "missing field %s" name))
    | j -> type_err name j

  let opt_field name dec j =
    match j with
    | \`Assoc kvs -> (
        match List.assoc_opt name kvs with
        | Some \`Null | None -> Ok None
        | Some v -> Result.map (fun v -> Some v) (dec v))
    | j -> type_err name j
end
`;

function print(module_) {
  let typeDecls = module_.types.map(printTypeDecl).join("\n\n");
  let allCodecs = module_.types.flatMap(printCodecs);
  let first = allCodecs[0];
  let codecChain;
  if (first !== undefined) {
    let rest = allCodecs.slice(1).map(c => `and ` + c);
    codecChain = [`let rec ` + first].concat(rest).join("\n\n");
  } else {
    codecChain = "";
  }
  return [
    prelude,
    typeDecls,
    codecChain
  ].join("\n");
}

export {
  toSnake,
  ocamlKeywords,
  escapeKeyword,
  wireName,
  fieldName,
  typeName,
  enumConstructor,
  printType,
  printRecordFields,
  printVariantCaseDecl,
  printTypeDecl,
  encExpr,
  encField,
  encFieldEntry,
  encFieldEntries,
  decExpr,
  decFieldBinding,
  recordToYojson,
  recordOfYojson,
  wireTag,
  variantToYojson,
  decCasePayload,
  variantOfYojson,
  enumToYojson,
  enumOfYojson,
  aliasToYojson,
  aliasOfYojson,
  printCodecs,
  prelude,
  print,
}
/* No side effect */
