// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Array from "@rescript/core/src/Core__Array.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.mjs";
import * as CodegenHelpers from "./CodegenHelpers.mjs";

let reservedTsNames = [
  "Effect",
  "Schema",
  "SchemaGetter"
];

function tsName(name) {
  let n = CodegenHelpers.ucFirst(name);
  if (reservedTsNames.includes(n)) {
    return n + "_";
  } else {
    return n;
  }
}

function isValidIdent(s) {
  if (s !== "") {
    return s.split("").every((c, i) => {
      let code = c.charCodeAt(0);
      let alpha = code >= 97.0 && code <= 122.0 || code >= 65.0 && code <= 90.0 || code === 95.0 || code === 36.0;
      let digit = code >= 48.0 && code <= 57.0;
      if (i === 0) {
        return alpha;
      } else if (alpha) {
        return true;
      } else {
        return digit;
      }
    });
  } else {
    return false;
  }
}

function quoteKey(k) {
  if (isValidIdent(k)) {
    return k;
  } else {
    return `'` + k + `'`;
  }
}

function wireName(field) {
  return Core__Option.getOr(Core__Array.findMap(field.annotations, ann => {
    if (typeof ann !== "object" || ann.TAG !== "As") {
      return;
    } else {
      return ann._0;
    }
  }), field.name);
}

function wireTag(c) {
  return Core__Option.getOr(c.asValue, c.tag);
}

function schemaExpr(_t, indent) {
  while (true) {
    let t = _t;
    if (typeof t !== "object") {
      return "Schema.Unknown";
    }
    switch (t.TAG) {
      case "Primitive" :
        switch (t._0) {
          case "PString" :
            return "Schema.String";
          case "PFloat" :
            return "Schema.Number";
          case "PInt" :
            return "Schema.Int";
          case "PBool" :
            return "Schema.Boolean";
          case "PUnit" :
            return "Schema.Null";
        }
      case "Option" :
        return `Schema.optionalKey(Schema.NullOr(` + schemaExpr(t._0, indent) + `))`;
      case "Nullable" :
        return `Schema.NullOr(` + schemaExpr(t._0, indent) + `)`;
      case "Array" :
        return `Schema.Array(` + schemaExpr(t._0, indent) + `)`;
      case "Dict" :
        return `Schema.Record(Schema.String, ` + schemaExpr(t._0, indent) + `)`;
      case "Named" :
        return tsName(t._0);
      case "Enum" :
        return `Schema.Literals([` + t._0.map(v => `'` + v + `'`).join(", ") + `])`;
      case "InlineRecord" :
        return structExpr(t._0, indent);
      case "InlineVariant" :
        return "Schema.Unknown";
      case "Refined" :
        _t = t._0;
        continue;
    }
  };
}

function structFields(fields, indent) {
  return fields.map(f => indent + `  ` + quoteKey(wireName(f)) + `: ` + schemaExpr(f.type_, indent + "  ") + `,`).join("\n");
}

function structExpr(fields, indent) {
  return `Schema.Struct({\n` + structFields(fields, indent) + `\n` + indent + `})`;
}

function memoryStructBody(c, indent) {
  let tagLine = indent + `  _tag: Schema.Literal('` + c.tag + `'),`;
  let fields = c.payload;
  if (typeof fields === "object") {
    switch (fields.TAG) {
      case "Primitive" :
        if (fields._0 === "PUnit") {
          return `Schema.Struct({\n` + tagLine + `\n` + indent + `})`;
        }
        break;
      case "InlineRecord" :
        let fields$1 = fields._0;
        if (fields$1.length === 0) {
          return `Schema.Struct({\n` + tagLine + `\n` + indent + `})`;
        } else {
          return `Schema.Struct({\n` + tagLine + `\n` + structFields(fields$1, indent) + `\n` + indent + `})`;
        }
    }
  }
  return `Schema.Struct({\n` + tagLine + `\n` + indent + `  value: ` + schemaExpr(fields, indent + "  ") + `,\n` + indent + `})`;
}

function externalCase(constName, c) {
  let wire = wireTag(c);
  let wireKey = quoteKey(wire);
  let payloadExpr = schemaExpr(c.payload, "  ");
  let memory = memoryStructBody(c, "    ");
  let match = c.payload;
  let match$1;
  let exit = 0;
  if (typeof match !== "object" || match.TAG !== "InlineRecord") {
    exit = 1;
  } else {
    match$1 = isValidIdent(wire) ? [
        `({ ` + wire + ` }) => ({ _tag: '` + c.tag + `' as const, ...` + wire + ` })`,
        `({ _tag: _t, ...rest }) => ({ ` + wire + `: rest })`
      ] : [
        `({ ` + wireKey + `: p }) => ({ _tag: '` + c.tag + `' as const, ...p })`,
        `({ _tag: _t, ...rest }) => ({ ` + wireKey + `: rest })`
      ];
  }
  if (exit === 1) {
    match$1 = [
      `({ ` + wireKey + `: p }) => ({ _tag: '` + c.tag + `' as const, value: p })`,
      `({ _tag: _t, value }) => ({ ` + wireKey + `: value })`
    ];
  }
  return `const ` + constName + ` = Schema.Struct({
  ` + wireKey + `: ` + payloadExpr + `,
}).pipe(
  Schema.decodeTo(
    ` + memory + `,
    {
      decode: SchemaGetter.transform(` + match$1[0] + `),
      encode: SchemaGetter.transform(` + match$1[1] + `),
    },
  ),
)`;
}

function internalTransformCase(constName, c, tagField) {
  let wire = wireTag(c);
  let tagKey = quoteKey(tagField);
  let fields = c.payload;
  let wireFields;
  if (typeof fields !== "object" || fields.TAG !== "InlineRecord") {
    wireFields = "";
  } else {
    let fields$1 = fields._0;
    wireFields = fields$1.length > 0 ? "\n" + structFields(fields$1, "") : "";
  }
  let memory = memoryStructBody(c, "    ");
  return `const ` + constName + ` = Schema.Struct({
  ` + tagKey + `: Schema.Literal('` + wire + `'),` + wireFields + `
}).pipe(
  Schema.decodeTo(
    ` + memory + `,
    {
      decode: SchemaGetter.transform(({ ` + tagKey + `: _k, ...rest }) => ({ _tag: '` + c.tag + `' as const, ...rest })),
      encode: SchemaGetter.transform(({ _tag: _t, ...rest }) => ({ ` + tagKey + `: '` + wire + `' as const, ...rest })),
    },
  ),
)`;
}

function plainTaggedCase(constName, c) {
  return `const ` + constName + ` = ` + memoryStructBody(c, "");
}

function typeExport(name) {
  return `export type ` + name + ` = Schema.Schema.Type<typeof ` + name + `>`;
}

function printTypeDef(typeDef) {
  let name = tsName(typeDef.name);
  let listEncoded = typeDef.annotations.includes("ListEncoded");
  let fields = typeDef.kind;
  switch (fields.TAG) {
    case "RecordDef" :
      return `export const ` + name + ` = ` + structExpr(fields._0, "") + `\n` + typeExport(name);
    case "VariantDef" :
      let repr = fields._1;
      let cases = fields._0;
      let unboxed = typeDef.annotations.includes("Unboxed");
      if (unboxed) {
        let members = cases.map(c => schemaExpr(c.payload, "")).join(", ");
        return `export const ` + name + ` = Schema.Union([` + members + `])\n` + typeExport(name);
      }
      let constNames = cases.map(c => `_` + name + c.tag);
      let caseDefs;
      if (typeof repr !== "object") {
        caseDefs = cases.map((c, i) => externalCase(constNames[i], c));
      } else {
        let tagField = repr._0;
        let allMatch = tagField === "_tag" && cases.every(c => Core__Option.isNone(c.asValue));
        caseDefs = allMatch ? cases.map((c, i) => plainTaggedCase(constNames[i], c)) : cases.map((c, i) => internalTransformCase(constNames[i], c, tagField));
      }
      let union = `export const ` + name + ` = Schema.Union([` + constNames.join(", ") + `])\n` + typeExport(name);
      return caseDefs.concat([union]).join("\n\n");
    case "AliasDef" :
      let values = fields._0;
      if (typeof values === "object" && values.TAG === "Enum") {
        let values$1 = values._0;
        if (!listEncoded) {
          return `export const ` + name + ` = Schema.Literals([` + values$1.map(v => `'` + v + `'`).join(", ") + `])\n` + typeExport(name);
        }
        let literals = `Schema.Literals([` + values$1.map(v => `'` + v + `'`).join(", ") + `])`;
        return `export const ` + name + ` = Schema.Tuple([` + literals + `]).pipe(
  Schema.decodeTo(
    ` + literals + `,
    {
      decode: SchemaGetter.transform(([s]) => s),
      encode: SchemaGetter.transform((s) => [s] as const),
    },
  ),
)
` + typeExport(name);
      }
      return `export const ` + name + ` = ` + schemaExpr(values, "") + `\n` + typeExport(name);
  }
}

function print(module_) {
  let body = module_.types.map(printTypeDef).join("\n\n");
  let needsGetter = body.includes("SchemaGetter.");
  let needsEffect = body.includes("Effect.succeed");
  let imports = Core__Array.filterMap([
    needsEffect ? "Effect" : undefined,
    "Schema",
    needsGetter ? "SchemaGetter" : undefined
  ], x => x).join(", ");
  return `import { ` + imports + ` } from 'effect'\n\n` + body + `\n`;
}

export {
  reservedTsNames,
  tsName,
  isValidIdent,
  quoteKey,
  wireName,
  wireTag,
  schemaExpr,
  structFields,
  structExpr,
  memoryStructBody,
  externalCase,
  internalTransformCase,
  plainTaggedCase,
  typeExport,
  printTypeDef,
  print,
}
/* No side effect */
