// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Array from "@rescript/core/src/Core__Array.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.mjs";

function quoteTag(tag) {
  let needsQuoting = tag === "" || tag.split("").some(c => {
    let code = c.charCodeAt(0);
    return !(code >= 97.0 && code <= 122.0 || code >= 65.0 && code <= 90.0 || code >= 48.0 && code <= 57.0 || code === 95.0);
  });
  if (needsQuoting) {
    return `"` + tag + `"`;
  } else {
    return tag;
  }
}

function printPrimitive(p) {
  switch (p) {
    case "PString" :
      return "string";
    case "PFloat" :
      return "float";
    case "PInt" :
      return "int";
    case "PBool" :
      return "bool";
    case "PUnit" :
      return "unit";
  }
}

function printType(t) {
  if (typeof t !== "object") {
    return "@s.matches(S.json) JSON.t";
  }
  switch (t.TAG) {
    case "Primitive" :
      return printPrimitive(t._0);
    case "Option" :
      return `option<` + printType(t._0) + `>`;
    case "Nullable" :
      return `Nullable.t<` + printType(t._0) + `>`;
    case "Array" :
      return `array<` + printType(t._0) + `>`;
    case "Dict" :
      return `Dict.t<` + printType(t._0) + `>`;
    case "Named" :
      return t._0;
    case "Enum" :
      let variants = t._0.map(v => `#` + quoteTag(v)).join(" | ");
      return `[` + variants + `]`;
    case "InlineRecord" :
      return printRecord(t._0);
    case "InlineVariant" :
      return printVariantCases(t._0);
  }
}

function printField(field) {
  let typeStr = printType(field.type_);
  let fieldType = Core__Array.reduce(field.annotations, typeStr, (acc, ann) => {
    if (typeof ann !== "object" && ann === "SNull") {
      return `@s.null ` + acc;
    } else {
      return acc;
    }
  });
  let asAttr = Core__Option.getOr(Core__Array.findMap(field.annotations, ann => {
    if (typeof ann !== "object" || ann.TAG !== "As") {
      return;
    } else {
      return `@as("` + ann._0 + `") `;
    }
  }), "");
  return asAttr + field.name + `: ` + fieldType;
}

function printRecord(fields) {
  if (fields.length === 0) {
    return "{}";
  }
  let fieldStrs = fields.map(printField);
  return `{\n  ` + fieldStrs.join(",\n  ") + `\n}`;
}

function printVariantCase(c) {
  let payloadStr = printType(c.payload);
  let wire = c.asValue;
  let asAttr = wire !== undefined ? `@as("` + wire + `") ` : "";
  return asAttr + c.tag + `(` + payloadStr + `)`;
}

function printVariantCases(cases) {
  let caseStrs = cases.map(printVariantCase);
  return `[` + caseStrs.map(c => `#` + quoteTag(c)).join(" | ") + `]`;
}

function printAnnotation(ann) {
  if (typeof ann !== "object") {
    switch (ann) {
      case "GenType" :
        return "@genType";
      case "Schema" :
        return "@schema";
      case "Unboxed" :
        return "@unboxed";
      case "SNull" :
      case "ListEncoded" :
        return;
    }
  } else {
    switch (ann.TAG) {
      case "Tag" :
        return `@tag("` + ann._0 + `")`;
      case "As" :
      case "Recursive" :
        return;
    }
  }
}

function recursiveLabel(annotations) {
  return Core__Array.findMap(annotations, ann => {
    if (typeof ann !== "object" || ann.TAG !== "Recursive") {
      return;
    } else {
      return ann._0;
    }
  });
}

function printSuryExpr(t, selfName) {
  if (typeof t !== "object") {
    return "S.json";
  }
  switch (t.TAG) {
    case "Primitive" :
      switch (t._0) {
        case "PString" :
          return "S.string";
        case "PFloat" :
          return "S.float";
        case "PInt" :
          return "S.int";
        case "PBool" :
          return "S.bool";
        case "PUnit" :
          return "S.unit";
      }
    case "Option" :
      return Core__Option.map(printSuryExpr(t._0, selfName), e => `S.option(` + e + `)`);
    case "Nullable" :
      return Core__Option.map(printSuryExpr(t._0, selfName), e => `S.nullable(` + e + `)`);
    case "Array" :
      return Core__Option.map(printSuryExpr(t._0, selfName), e => `S.array(` + e + `)`);
    case "Dict" :
      return Core__Option.map(printSuryExpr(t._0, selfName), e => `S.dict(` + e + `)`);
    case "Named" :
      let name = t._0;
      return name === selfName ? "self" : name + `Schema`;
    case "Enum" :
      let lits = t._0.map(v => `S.literal("` + v + `")`).join(", ");
      return `S.union([` + lits + `])`;
    case "InlineRecord" :
    case "InlineVariant" :
      return;
  }
}

function printRecursiveSchema(name, label, fields) {
  let fieldExprs = fields.map(f => Core__Option.map(printSuryExpr(f.type_, name), e => `    ` + f.name + `: s.matches(` + e + `),`));
  if (fieldExprs.some(Core__Option.isNone)) {
    return;
  }
  let body = Core__Array.filterMap(fieldExprs, x => x).join("\n");
  return `let ` + name + `Schema = S.recursive("` + label + `", self => S.schema(s => {\n` + body + `\n}))`;
}

function printAnnotations(annotations) {
  return Core__Array.filterMap(annotations, printAnnotation).join("\n");
}

function printTypeDef(typeDef) {
  let annotations = printAnnotations(typeDef.annotations);
  let fields = typeDef.kind;
  let body;
  switch (fields.TAG) {
    case "RecordDef" :
      body = printRecord(fields._0);
      break;
    case "VariantDef" :
      body = fields._0.map(printVariantCase).join(" | ");
      break;
    case "AliasDef" :
      body = printType(fields._0);
      break;
  }
  let label = recursiveLabel(typeDef.annotations);
  if (label === undefined) {
    return annotations + `\ntype ` + typeDef.name + ` = ` + body;
  }
  let typeDecl = annotations + `\ntype rec ` + typeDef.name + ` = ` + body;
  let fields$1 = typeDef.kind;
  switch (fields$1.TAG) {
    case "RecordDef" :
      let schema = printRecursiveSchema(typeDef.name, label, fields$1._0);
      if (schema !== undefined) {
        return typeDecl + `\n` + schema;
      } else {
        return typeDecl;
      }
    case "VariantDef" :
    case "AliasDef" :
      return typeDecl;
  }
}

function print(module_) {
  let typeDefs = module_.types.map(printTypeDef).join("\n\n");
  return module_.preamble + "\n\n" + typeDefs;
}

export {
  quoteTag,
  printPrimitive,
  printType,
  printField,
  printRecord,
  printVariantCase,
  printVariantCases,
  printAnnotation,
  recursiveLabel,
  printSuryExpr,
  printRecursiveSchema,
  printAnnotations,
  printTypeDef,
  print,
}
/* No side effect */
