// CodegenShims.res - TypeScript/ReScript shim generation
// No dependencies on other Codegen modules

/** Generate Dict.gen.ts shim content for @genType */
let generateDictShim = (): string => {
  `// Generated by osury - Dict type shim for @genType
export type t<T> = { [key: string]: T };
`
}

/** Generate Nullable.shim.ts content for @genType.import */
let generateNullableShim = (): string => {
  `/**
 * Type shim for ReScript Nullable.t
 *
 * This file is generated by osury (not by ReScript/genType).
 * It maps ReScript's option<T> to TypeScript's T | null for JSON nullable fields.
 *
 * ReScript side: Nullable.t<T> = option<T> (works with sury's S.null schema)
 * TypeScript side: t<T> = T | null (correct JSON null representation)
 */
export type t<T> = T | null;
`
}

/** Generate JSON.gen.ts shim content for @genType */
let generateJsonShim = (): string => {
  `// Generated by osury - JSON type shim for @genType
export type t = unknown;
`
}

/** Generate Nullable.res module content */
let generateNullableModule = (): string => {
  `// Generated by osury - Nullable type for JSON null values
// This is option<T> internally but maps to T | null in TypeScript via shim
@genType.import(("./Nullable.shim.ts", "t"))
type t<'a> = option<'a>
`
}
