// Generated by ReScript, PLEASE EDIT WITH CARE


let reservedKeywords = [
  "type",
  "let",
  "rec",
  "and",
  "as",
  "open",
  "include",
  "module",
  "sig",
  "struct",
  "exception",
  "external",
  "if",
  "else",
  "switch",
  "while",
  "for",
  "try",
  "catch",
  "when",
  "true",
  "false",
  "assert",
  "lazy",
  "constraint",
  "functor",
  "class",
  "method",
  "object",
  "private",
  "public",
  "virtual",
  "mutable",
  "new",
  "inherit",
  "initializer",
  "val",
  "with",
  "match",
  "of",
  "fun",
  "function",
  "in",
  "do",
  "done",
  "begin",
  "end",
  "then",
  "to",
  "downto",
  "or",
  "land",
  "lor",
  "lxor",
  "lsl",
  "lsr",
  "asr",
  "mod",
  "await",
  "async"
];

function isReservedKeyword(name) {
  return reservedKeywords.includes(name);
}

function lcFirst(s) {
  if (s.length === 0) {
    return s;
  }
  let first = s.charAt(0).toLowerCase();
  let rest = s.slice(1);
  return first + rest;
}

function ucFirst(s) {
  if (s.length === 0) {
    return s;
  }
  let first = s.charAt(0).toUpperCase();
  let rest = s.slice(1);
  return first + rest;
}

function isOptionalType(schema) {
  if (typeof schema !== "object") {
    return false;
  }
  switch (schema._tag) {
    case "Optional" :
    case "Nullable" :
      return true;
    default:
      return false;
  }
}

function isNullableType(schema) {
  if (typeof schema !== "object") {
    return false;
  } else {
    return schema._tag === "Nullable";
  }
}

function getTagForType(_t) {
  while (true) {
    let t = _t;
    if (typeof t !== "object") {
      switch (t) {
        case "String" :
          return "String";
        case "Number" :
          return "Float";
        case "Integer" :
          return "Int";
        case "Boolean" :
          return "Bool";
        case "Null" :
          return "Null";
        case "Unknown" :
          return "Unknown";
      }
    } else {
      switch (t._tag) {
        case "Optional" :
          return `Option` + getTagForType(t._0);
        case "Nullable" :
          return `Null` + getTagForType(t._0);
        case "Object" :
          return "Object";
        case "Array" :
          return `Array` + getTagForType(t._0);
        case "Ref" :
          return ucFirst(t._0);
        case "Enum" :
          return "Enum";
        case "PolyVariant" :
          return "Variant";
        case "Dict" :
          return "Dict";
        case "Union" :
          return "Union";
        case "Refined" :
          _t = t._0;
          continue;
      }
    }
  };
}

function hasUnion(_schema) {
  while (true) {
    let schema = _schema;
    if (typeof schema !== "object") {
      return false;
    }
    switch (schema._tag) {
      case "Object" :
        return schema._0.some(f => hasUnion(f.type));
      case "PolyVariant" :
        return schema._0.some(c => hasUnion(c.payload));
      case "Union" :
        return true;
      case "Optional" :
      case "Nullable" :
      case "Array" :
      case "Dict" :
      case "Refined" :
        _schema = schema._0;
        continue;
      default:
        return false;
    }
  };
}

function hasUnknown(_schema) {
  while (true) {
    let schema = _schema;
    if (typeof schema !== "object") {
      return schema === "Unknown";
    }
    switch (schema._tag) {
      case "Object" :
        return schema._0.some(f => hasUnknown(f.type));
      case "PolyVariant" :
        return schema._0.some(c => hasUnknown(c.payload));
      case "Optional" :
      case "Nullable" :
      case "Array" :
      case "Dict" :
      case "Refined" :
        _schema = schema._0;
        continue;
      default:
        return false;
    }
  };
}

function runtimeShapeOf(_t, resolve, _depthOpt) {
  while (true) {
    let depthOpt = _depthOpt;
    let t = _t;
    let depth = depthOpt !== undefined ? depthOpt : 0;
    if (typeof t !== "object") {
      switch (t) {
        case "String" :
          return "SString";
        case "Number" :
        case "Integer" :
          return "SNumber";
        case "Boolean" :
          return "SBoolean";
        case "Null" :
          return "SNull";
        default:
          return "SOpaque";
      }
    } else {
      switch (t._tag) {
        case "Array" :
          return "SArray";
        case "Ref" :
          if (depth > 8) {
            return "SOpaque";
          }
          let target = resolve(t._0);
          if (target === undefined) {
            return "SOpaque";
          }
          _depthOpt = depth + 1 | 0;
          _t = target;
          continue;
        case "Enum" :
          return "SString";
        case "Object" :
        case "Dict" :
          return "SObject";
        case "Refined" :
          _depthOpt = depth;
          _t = t._0;
          continue;
        default:
          return "SOpaque";
      }
    }
  };
}

function isShapeDistinctUnion(types, resolve) {
  let shapes = types.map(t => runtimeShapeOf(t, resolve, undefined));
  if (shapes.some(sh => sh === "SOpaque")) {
    return false;
  }
  let seen = [];
  return shapes.every(sh => {
    if (seen.includes(sh)) {
      return false;
    } else {
      seen.push(sh);
      return true;
    }
  });
}

function isPrimitiveOnlyUnion(types) {
  let allPrimitive = types.every(t => {
    if (typeof t === "object") {
      return false;
    }
    switch (t) {
      case "String" :
      case "Number" :
      case "Integer" :
      case "Boolean" :
        return true;
      default:
        return false;
    }
  });
  if (!allPrimitive) {
    return false;
  }
  let hasFloat = types.some(t => t === "Number");
  let hasInt = types.some(t => t === "Integer");
  return !(hasFloat && hasInt);
}

export {
  reservedKeywords,
  isReservedKeyword,
  lcFirst,
  ucFirst,
  isOptionalType,
  isNullableType,
  getTagForType,
  hasUnion,
  hasUnknown,
  runtimeShapeOf,
  isShapeDistinctUnion,
  isPrimitiveOnlyUnion,
}
/* No side effect */
