// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Errors from "./Errors.res.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as CodegenHelpers from "./CodegenHelpers.res.mjs";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";

function collectEnumsFromType(parentType, fieldPath, _schema) {
  while (true) {
    let schema = _schema;
    if (typeof schema !== "object") {
      return [];
    }
    switch (schema._tag) {
      case "Object" :
        return schema._0.flatMap(f => collectEnumsFromType(parentType, fieldPath.concat([f.name]), f.type));
      case "Enum" :
        if (fieldPath.length > 0) {
          return [{
              parentType: parentType,
              fieldPath: fieldPath,
              values: schema._0
            }];
        } else {
          return [];
        }
      case "PolyVariant" :
        return schema._0.flatMap(c => collectEnumsFromType(parentType, fieldPath, c.payload));
      case "Optional" :
      case "Nullable" :
      case "Array" :
      case "Dict" :
        break;
      case "Union" :
        return schema._0.flatMap(t => collectEnumsFromType(parentType, fieldPath, t));
      default:
        return [];
    }
    _schema = schema._0;
    continue;
  };
}

function collectInlineEnums(schemas) {
  return schemas.flatMap(s => {
    let match = s.schema;
    if (typeof match !== "object") {
      return collectEnumsFromType(s.name, [], s.schema);
    } else if (match._tag === "Enum") {
      return [];
    } else {
      return collectEnumsFromType(s.name, [], s.schema);
    }
  });
}

function camelize(s) {
  let parts = s.replace(/-/g, "_").split("_").filter(p => p !== "");
  let first = parts[0];
  if (first === undefined) {
    return s;
  }
  let rest = parts.slice(1);
  return CodegenHelpers.lcFirst(first) + rest.map(CodegenHelpers.ucFirst).join("");
}

function occurrenceKey(occ) {
  return occ.parentType + "::" + occ.fieldPath.join("/");
}

function valuesCanonicalKey(values) {
  let cmp = (a, b) => {
    if (Primitive_object.lessthan(a, b)) {
      return -1.0;
    } else if (Primitive_object.greaterthan(a, b)) {
      return 1.0;
    } else {
      return 0.0;
    }
  };
  return values.toSorted(cmp).join("");
}

function leafFieldName(occ) {
  let s = occ.fieldPath[occ.fieldPath.length - 1 | 0];
  if (s !== undefined) {
    return s;
  } else {
    return "unknown";
  }
}

function replaceEnumsInType(parentType, fieldPath, names, schema) {
  if (typeof schema !== "object") {
    return schema;
  }
  switch (schema._tag) {
    case "Optional" :
      return {
        _tag: "Optional",
        _0: replaceEnumsInType(parentType, fieldPath, names, schema._0)
      };
    case "Nullable" :
      return {
        _tag: "Nullable",
        _0: replaceEnumsInType(parentType, fieldPath, names, schema._0)
      };
    case "Object" :
      return {
        _tag: "Object",
        _0: schema._0.map(f => {
          let newType = replaceEnumsInType(parentType, fieldPath.concat([f.name]), names, f.type);
          return {
            name: f.name,
            type: newType,
            required: f.required
          };
        })
      };
    case "Array" :
      return {
        _tag: "Array",
        _0: replaceEnumsInType(parentType, fieldPath, names, schema._0)
      };
    case "Enum" :
      if (fieldPath.length <= 0) {
        return schema;
      }
      let key = parentType + "::" + fieldPath.join("/");
      let name = names[key];
      if (name !== undefined) {
        return {
          _tag: "Ref",
          _0: CodegenHelpers.ucFirst(name)
        };
      } else {
        return schema;
      }
    case "PolyVariant" :
      return {
        _tag: "PolyVariant",
        _0: schema._0.map(c => {
          let payload = replaceEnumsInType(parentType, fieldPath, names, c.payload);
          return {
            _tag: c._tag,
            payload: payload
          };
        })
      };
    case "Dict" :
      return {
        _tag: "Dict",
        _0: replaceEnumsInType(parentType, fieldPath, names, schema._0)
      };
    case "Union" :
      return {
        _tag: "Union",
        _0: schema._0.map(t => replaceEnumsInType(parentType, fieldPath, names, t))
      };
    default:
      return schema;
  }
}

function replaceInlineEnums(schemas, names) {
  return schemas.map(s => {
    let match = s.schema;
    let newSchema;
    let exit = 0;
    if (typeof match !== "object" || match._tag !== "Enum") {
      exit = 1;
    } else {
      newSchema = s.schema;
    }
    if (exit === 1) {
      newSchema = replaceEnumsInType(s.name, [], names, s.schema);
    }
    return {
      name: s.name,
      schema: newSchema,
      discriminatorTag: s.discriminatorTag,
      discriminatorPropertyName: s.discriminatorPropertyName,
      fieldDiscriminators: s.fieldDiscriminators
    };
  });
}

function buildExtractedEnumSchemas(occurrences, names) {
  let seen = {};
  let result = [];
  occurrences.forEach(occ => {
    let key = occurrenceKey(occ);
    let name = names[key];
    if (name === undefined) {
      return;
    }
    let typeName = CodegenHelpers.ucFirst(name);
    if (Core__Option.isNone(seen[typeName])) {
      seen[typeName] = true;
      result.push({
        name: typeName,
        schema: {
          _tag: "Enum",
          _0: occ.values
        },
        discriminatorTag: undefined,
        discriminatorPropertyName: undefined,
        fieldDiscriminators: undefined
      });
      return;
    }
  });
  return result;
}

function resolveEnumNames(occurrences, topLevelNames) {
  let topLevelSet = {};
  topLevelNames.forEach(n => {
    topLevelSet[CodegenHelpers.lcFirst(n)] = true;
  });
  let buckets = {};
  occurrences.forEach(occ => {
    let leaf = leafFieldName(occ);
    let vKey = valuesCanonicalKey(occ.values);
    let set = buckets[leaf];
    if (set !== undefined) {
      set[vKey] = true;
      return;
    }
    let set$1 = {};
    set$1[vKey] = true;
    buckets[leaf] = set$1;
  });
  let result = {};
  occurrences.forEach(occ => {
    let leaf = leafFieldName(occ);
    let camelized = camelize(leaf);
    let distinctSets = Core__Option.mapOr(buckets[leaf], 1, set => Object.keys(set).length);
    let collidesTopLevel = Core__Option.isSome(topLevelSet[camelized]);
    let baseName = distinctSets > 1 || collidesTopLevel ? CodegenHelpers.lcFirst(occ.parentType) + CodegenHelpers.ucFirst(camelized) : camelized;
    let name = CodegenHelpers.isReservedKeyword(baseName) ? baseName + "_" : baseName;
    result[occurrenceKey(occ)] = name;
  });
  return result;
}

function isRefPlusDictUnion(types) {
  if (types.length !== 2) {
    return;
  }
  let hasDict = types.some(t => {
    if (typeof t !== "object") {
      return false;
    }
    if (t._tag !== "Dict") {
      return false;
    }
    let tmp = t._0;
    if (typeof tmp !== "object") {
      return tmp === "String";
    } else {
      return false;
    }
  });
  let refName = Core__Array.findMap(types, t => {
    if (typeof t !== "object" || t._tag !== "Ref") {
      return;
    } else {
      return t._0;
    }
  });
  if (hasDict) {
    return refName;
  }
}

function isPrimitivePlusDictUnion(types) {
  if (types.length !== 2) {
    return;
  }
  let hasDict = types.some(t => {
    if (typeof t !== "object") {
      return false;
    }
    if (t._tag !== "Dict") {
      return false;
    }
    let tmp = t._0;
    if (typeof tmp !== "object") {
      return tmp === "String";
    } else {
      return false;
    }
  });
  let primitiveName = Core__Array.findMap(types, t => {
    if (typeof t === "object") {
      return;
    }
    switch (t) {
      case "String" :
        return "string";
      case "Number" :
        return "float";
      case "Integer" :
        return "int";
      case "Boolean" :
        return "bool";
      default:
        return;
    }
  });
  if (hasDict) {
    return primitiveName;
  }
}

function getUnionName(types) {
  let names = types.map(t => {
    if (typeof t !== "object") {
      switch (t) {
        case "String" :
          return "string";
        case "Number" :
          return "float";
        case "Integer" :
          return "int";
        case "Boolean" :
          return "bool";
        case "Null" :
          return "null";
        default:
          return "unknown";
      }
    } else {
      switch (t._tag) {
        case "Array" :
          return "array";
        case "Ref" :
          return CodegenHelpers.lcFirst(t._0);
        case "Dict" :
          return "dict";
        default:
          return "unknown";
      }
    }
  });
  if (names.length === 0) {
    return "emptyUnion";
  }
  let first = Core__Option.getOr(names[0], "unknown");
  let rest = names.slice(1);
  return first + rest.map(n => "Or" + CodegenHelpers.ucFirst(n)).join("");
}

function getPolyVariantName(cases) {
  return getUnionName(cases.map(c => c.payload));
}

function extractUnionsFromType(_schema) {
  while (true) {
    let schema = _schema;
    if (typeof schema !== "object") {
      return [];
    }
    switch (schema._tag) {
      case "Object" :
        return schema._0.flatMap(field => extractUnionsFromType(field.type));
      case "PolyVariant" :
        let name = getPolyVariantName(schema._0);
        return [{
            name: name,
            schema: schema
          }];
      case "Optional" :
      case "Nullable" :
      case "Array" :
      case "Dict" :
        _schema = schema._0;
        continue;
      case "Union" :
        let types = schema._0;
        let match = isRefPlusDictUnion(types);
        if (match !== undefined) {
          return [];
        }
        let name$1 = getUnionName(types);
        return [{
            name: name$1,
            schema: schema
          }];
      default:
        return [];
    }
  };
}

function extractUnions(_parentName, schema) {
  if (typeof schema !== "object") {
    return [];
  } else if (schema._tag === "Object") {
    return schema._0.flatMap(field => extractUnionsFromType(field.type));
  } else {
    return [];
  }
}

function replaceUnionInType(schema) {
  if (typeof schema !== "object") {
    return schema;
  }
  switch (schema._tag) {
    case "Optional" :
      return {
        _tag: "Optional",
        _0: replaceUnionInType(schema._0)
      };
    case "Nullable" :
      return {
        _tag: "Nullable",
        _0: replaceUnionInType(schema._0)
      };
    case "Object" :
      let newFields = schema._0.map(field => {
        let newType = replaceUnionInType(field.type);
        return {
          name: field.name,
          type: newType,
          required: field.required
        };
      });
      return {
        _tag: "Object",
        _0: newFields
      };
    case "Array" :
      return {
        _tag: "Array",
        _0: replaceUnionInType(schema._0)
      };
    case "PolyVariant" :
      return {
        _tag: "Ref",
        _0: getPolyVariantName(schema._0)
      };
    case "Dict" :
      return {
        _tag: "Dict",
        _0: replaceUnionInType(schema._0)
      };
    case "Union" :
      let types = schema._0;
      let refName = isRefPlusDictUnion(types);
      if (refName !== undefined) {
        return {
          _tag: "Ref",
          _0: refName
        };
      } else {
        return {
          _tag: "Ref",
          _0: getUnionName(types)
        };
      }
    default:
      return schema;
  }
}

function replaceUnions(_parentName, schema) {
  if (typeof schema !== "object") {
    return schema;
  }
  if (schema._tag !== "Object") {
    return schema;
  }
  let newFields = schema._0.map(field => {
    let newType = replaceUnionInType(field.type);
    return {
      name: field.name,
      type: newType,
      required: field.required
    };
  });
  return {
    _tag: "Object",
    _0: newFields
  };
}

function getDependencies(_schema) {
  while (true) {
    let schema = _schema;
    if (typeof schema !== "object") {
      return [];
    }
    switch (schema._tag) {
      case "Object" :
        return schema._0.flatMap(f => getDependencies(f.type));
      case "Ref" :
        return [schema._0];
      case "Enum" :
        return [];
      case "PolyVariant" :
        return schema._0.flatMap(c => getDependencies(c.payload));
      case "Optional" :
      case "Nullable" :
      case "Array" :
      case "Dict" :
        _schema = schema._0;
        continue;
      case "Union" :
        return schema._0.flatMap(getDependencies);
    }
  };
}

function topologicalSort(schemas) {
  let schemaMap = {};
  schemas.forEach(s => {
    schemaMap[s.name] = s;
  });
  let deps = {};
  schemas.forEach(s => {
    let refNames = getDependencies(s.schema);
    let validRefs = refNames.filter(name => Core__Option.isSome(schemaMap[name]));
    deps[s.name] = validRefs;
  });
  let outDegree = {};
  schemas.forEach(s => {
    let myDeps = Core__Option.getOr(deps[s.name], []);
    outDegree[s.name] = myDeps.length;
  });
  let reverseDeps = {};
  schemas.forEach(s => {
    reverseDeps[s.name] = [];
  });
  Object.entries(deps).forEach(param => {
    let name = param[0];
    param[1].forEach(refName => {
      let arr = reverseDeps[refName];
      if (arr !== undefined) {
        arr.push(name);
        return;
      }
    });
  });
  let queue = schemas.filter(s => Core__Option.getOr(outDegree[s.name], 0) === 0).map(s => s.name);
  let result = [];
  let visited = {};
  let process = () => {
    while (true) {
      let name = queue.shift();
      if (name === undefined) {
        return;
      }
      if (Core__Option.isNone(visited[name])) {
        visited[name] = true;
        let schema = schemaMap[name];
        if (schema !== undefined) {
          result.push(schema);
        }
        let dependents = reverseDeps[name];
        if (dependents !== undefined) {
          dependents.forEach(depName => {
            let current = Core__Option.getOr(outDegree[depName], 0);
            outDegree[depName] = current - 1 | 0;
            if ((current - 1 | 0) === 0) {
              queue.push(depName);
              return;
            }
          });
        }
      }
      continue;
    };
  };
  process();
  schemas.forEach(s => {
    if (Core__Option.isNone(visited[s.name])) {
      result.push(s);
      return;
    }
  });
  return result;
}

function buildSkipSchemaSet(schemas) {
  let skipSet = {};
  schemas.forEach(s => {
    let types = s.schema;
    let hasInlineProblem;
    if (typeof types !== "object") {
      hasInlineProblem = CodegenHelpers.hasUnion(s.schema);
    } else {
      switch (types._tag) {
        case "PolyVariant" :
          hasInlineProblem = types._0.some(c => CodegenHelpers.hasUnion(c.payload));
          break;
        case "Union" :
          hasInlineProblem = types._0.some(CodegenHelpers.hasUnion);
          break;
        default:
          hasInlineProblem = CodegenHelpers.hasUnion(s.schema);
      }
    }
    if (hasInlineProblem) {
      skipSet[s.name] = true;
      return;
    }
  });
  let changed = {
    contents: true
  };
  while (changed.contents) {
    changed.contents = false;
    schemas.forEach(s => {
      if (!Core__Option.isNone(skipSet[s.name])) {
        return;
      }
      let refs = getDependencies(s.schema);
      let refsSkipSchema = refs.some(refName => Core__Option.isSome(skipSet[refName]));
      if (refsSkipSchema) {
        skipSet[s.name] = true;
        changed.contents = true;
        return;
      }
    });
  };
  return skipSet;
}

function collectUnionWarnings(schemas) {
  let seen = {};
  let warnings = [];
  let findUnions = _schema => {
    while (true) {
      let schema = _schema;
      if (typeof schema !== "object") {
        return [];
      }
      switch (schema._tag) {
        case "Object" :
          return schema._0.flatMap(f => findUnions(f.type));
        case "Optional" :
        case "Nullable" :
        case "Array" :
        case "Dict" :
          _schema = schema._0;
          continue;
        case "Union" :
          return [schema._0];
        default:
          return [];
      }
    };
  };
  schemas.forEach(s => {
    let unions = findUnions(s.schema);
    unions.forEach(types => {
      let unionName = getUnionName(types);
      if (!Core__Option.isNone(seen[unionName])) {
        return;
      }
      seen[unionName] = true;
      let refName = isRefPlusDictUnion(types);
      if (refName !== undefined) {
        warnings.push(`⚠ ` + unionName + `: anyOf without discriminator, simplified to ` + CodegenHelpers.lcFirst(refName));
        return;
      }
      let primName = isPrimitivePlusDictUnion(types);
      if (primName !== undefined) {
        warnings.push(`⚠ ` + unionName + `: anyOf [` + primName + `, Dict] without discriminator, @tag("_tag") may not work at runtime`);
        return;
      }
    });
  });
  return warnings;
}

function validateUnionDiscriminators(schemas) {
  let seen = {};
  let errors = [];
  let schemasDict = {};
  schemas.forEach(s => {
    schemasDict[s.name] = s.schema;
  });
  let tagsDict = {};
  schemas.forEach(s => {
    let tag = s.discriminatorTag;
    if (tag !== undefined) {
      tagsDict[s.name] = tag;
      return;
    }
  });
  let fieldDiscsDict = {};
  schemas.forEach(s => {
    let dict = s.fieldDiscriminators;
    if (dict !== undefined) {
      Object.entries(dict).forEach(param => {
        fieldDiscsDict[param[0]] = param[1];
      });
      return;
    }
  });
  let findUnions = _schema => {
    while (true) {
      let schema = _schema;
      if (typeof schema !== "object") {
        return [];
      }
      switch (schema._tag) {
        case "Object" :
          return schema._0.flatMap(f => findUnions(f.type));
        case "Optional" :
        case "Nullable" :
        case "Array" :
        case "Dict" :
          _schema = schema._0;
          continue;
        case "Union" :
          return [schema._0];
        default:
          return [];
      }
    };
  };
  schemas.forEach(s => {
    let unions = findUnions(s.schema);
    unions.forEach(types => {
      let unionName = getUnionName(types);
      if (!Core__Option.isNone(seen[unionName])) {
        return;
      }
      seen[unionName] = true;
      if (CodegenHelpers.isPrimitiveOnlyUnion(types)) {
        return;
      }
      let match = isRefPlusDictUnion(types);
      if (match !== undefined) {
        return;
      }
      let match$1 = isPrimitivePlusDictUnion(types);
      if (match$1 !== undefined) {
        return;
      }
      if (!Core__Option.isNone(fieldDiscsDict[unionName])) {
        return;
      }
      let allRefsHaveTags = types.every(t => {
        if (typeof t !== "object" || t._tag !== "Ref") {
          return true;
        } else {
          return Core__Option.isSome(tagsDict[t._0]);
        }
      });
      if (!allRefsHaveTags) {
        errors.push(Errors.makeError({
          TAG: "MissingDiscriminator",
          _0: unionName
        }, undefined, "Add discriminator: { propertyName: \"type\" } to the anyOf/oneOf schema, or use the _tag convention with const values", undefined));
        return;
      }
    });
  });
  return errors;
}

export {
  collectEnumsFromType,
  collectInlineEnums,
  camelize,
  occurrenceKey,
  valuesCanonicalKey,
  leafFieldName,
  replaceEnumsInType,
  replaceInlineEnums,
  buildExtractedEnumSchemas,
  resolveEnumNames,
  isRefPlusDictUnion,
  isPrimitivePlusDictUnion,
  getUnionName,
  getPolyVariantName,
  extractUnions,
  extractUnionsFromType,
  replaceUnions,
  replaceUnionInType,
  getDependencies,
  topologicalSort,
  buildSkipSchemaSet,
  collectUnionWarnings,
  validateUnionDiscriminators,
}
/* No side effect */
