// Generated by ReScript, PLEASE EDIT WITH CARE


let reservedKeywords = [
  "type",
  "let",
  "rec",
  "and",
  "as",
  "open",
  "include",
  "module",
  "sig",
  "struct",
  "exception",
  "external",
  "if",
  "else",
  "switch",
  "while",
  "for",
  "try",
  "catch",
  "when",
  "true",
  "false",
  "assert",
  "lazy",
  "constraint",
  "functor",
  "class",
  "method",
  "object",
  "private",
  "public",
  "virtual",
  "mutable",
  "new",
  "inherit",
  "initializer",
  "val",
  "with",
  "match",
  "of",
  "fun",
  "function",
  "in",
  "do",
  "done",
  "begin",
  "end",
  "then",
  "to",
  "downto",
  "or",
  "land",
  "lor",
  "lxor",
  "lsl",
  "lsr",
  "asr",
  "mod",
  "await",
  "async"
];

function isReservedKeyword(name) {
  return reservedKeywords.includes(name);
}

function lcFirst(s) {
  if (s.length === 0) {
    return s;
  }
  let first = s.charAt(0).toLowerCase();
  let rest = s.slice(1);
  return first + rest;
}

function ucFirst(s) {
  if (s.length === 0) {
    return s;
  }
  let first = s.charAt(0).toUpperCase();
  let rest = s.slice(1);
  return first + rest;
}

function isOptionalType(schema) {
  if (typeof schema !== "object") {
    return false;
  }
  switch (schema._tag) {
    case "Optional" :
    case "Nullable" :
      return true;
    default:
      return false;
  }
}

function isNullableType(schema) {
  if (typeof schema !== "object") {
    return false;
  } else {
    return schema._tag === "Nullable";
  }
}

function getTagForType(t) {
  if (typeof t !== "object") {
    switch (t) {
      case "String" :
        return "String";
      case "Number" :
        return "Float";
      case "Integer" :
        return "Int";
      case "Boolean" :
        return "Bool";
      case "Null" :
        return "Null";
      case "Unknown" :
        return "Unknown";
    }
  } else {
    switch (t._tag) {
      case "Optional" :
        return `Option` + getTagForType(t._0);
      case "Nullable" :
        return `Null` + getTagForType(t._0);
      case "Object" :
        return "Object";
      case "Array" :
        return `Array` + getTagForType(t._0);
      case "Ref" :
        return ucFirst(t._0);
      case "Enum" :
        return "Enum";
      case "PolyVariant" :
        return "Variant";
      case "Dict" :
        return "Dict";
      case "Union" :
        return "Union";
    }
  }
}

function hasUnion(_schema) {
  while (true) {
    let schema = _schema;
    if (typeof schema !== "object") {
      return false;
    }
    switch (schema._tag) {
      case "Object" :
        return schema._0.some(f => hasUnion(f.type));
      case "PolyVariant" :
        return schema._0.some(c => hasUnion(c.payload));
      case "Optional" :
      case "Nullable" :
      case "Array" :
      case "Dict" :
        _schema = schema._0;
        continue;
      case "Union" :
        return true;
      default:
        return false;
    }
  };
}

function hasUnknown(_schema) {
  while (true) {
    let schema = _schema;
    if (typeof schema !== "object") {
      return schema === "Unknown";
    }
    switch (schema._tag) {
      case "Object" :
        return schema._0.some(f => hasUnknown(f.type));
      case "PolyVariant" :
        return schema._0.some(c => hasUnknown(c.payload));
      case "Optional" :
      case "Nullable" :
      case "Array" :
      case "Dict" :
        _schema = schema._0;
        continue;
      default:
        return false;
    }
  };
}

function isPrimitiveOnlyUnion(types) {
  return types.every(t => {
    if (typeof t === "object") {
      return false;
    }
    switch (t) {
      case "String" :
      case "Number" :
      case "Integer" :
      case "Boolean" :
        return true;
      default:
        return false;
    }
  });
}

export {
  reservedKeywords,
  isReservedKeyword,
  lcFirst,
  ucFirst,
  isOptionalType,
  isNullableType,
  getTagForType,
  hasUnion,
  hasUnknown,
  isPrimitiveOnlyUnion,
}
/* No side effect */
