// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as CodegenHelpers from "./CodegenHelpers.res.mjs";

function generateType(schema) {
  if (typeof schema !== "object") {
    switch (schema) {
      case "String" :
        return "string";
      case "Number" :
        return "float";
      case "Integer" :
        return "int";
      case "Boolean" :
        return "bool";
      case "Null" :
        return "unit";
    }
  } else {
    switch (schema._tag) {
      case "Optional" :
        return `option<` + generateType(schema._0) + `>`;
      case "Nullable" :
        return `Nullable.t<` + generateType(schema._0) + `>`;
      case "Object" :
        return generateRecord(schema._0);
      case "Array" :
        return `array<` + generateType(schema._0) + `>`;
      case "Ref" :
        return CodegenHelpers.lcFirst(schema._0);
      case "Enum" :
        let variants = schema._0.map(v => `#` + v).join(" | ");
        return `[` + variants + `]`;
      case "PolyVariant" :
        return generatePolyVariant(schema._0);
      case "Dict" :
        return `Dict.t<` + generateType(schema._0) + `>`;
      case "Union" :
        return generateUnion(schema._0);
    }
  }
}

function generateRecord(fields) {
  if (fields.length === 0) {
    return "{}";
  }
  let fieldStrs = fields.map(field => {
    let typeStr = generateType(field.type);
    let optionalType = field.required || CodegenHelpers.isOptionalType(field.type) ? typeStr : `option<` + typeStr + `>`;
    let finalType = CodegenHelpers.isNullableType(field.type) ? `@s.null ` + optionalType : optionalType;
    let asAttr = CodegenHelpers.isReservedKeyword(field.name) ? `@as("` + field.name + `") ` : "";
    let fieldName = CodegenHelpers.isReservedKeyword(field.name) ? field.name + `_` : field.name;
    return asAttr + fieldName + `: ` + finalType;
  });
  return `{\n  ` + fieldStrs.join(",\n  ") + `\n}`;
}

function generatePolyVariant(cases) {
  let caseStrs = cases.map(c => {
    let payloadStr = generateType(c.payload);
    return `#` + c._tag + `(` + payloadStr + `)`;
  });
  return `[` + caseStrs.join(" | ") + `]`;
}

function generateUnion(types) {
  let caseStrs = types.map(t => {
    let tag = CodegenHelpers.getTagForType(t);
    let payload = generateType(t);
    return `#` + tag + `(` + payload + `)`;
  });
  return `[` + caseStrs.join(" | ") + `]`;
}

function generateInlineRecord(refName, schemasDict) {
  let other = schemasDict[refName];
  if (other !== undefined) {
    if (typeof other !== "object" || other._tag !== "Object") {
      return generateType(other);
    } else {
      return generateRecord(other._0);
    }
  } else {
    return CodegenHelpers.lcFirst(refName);
  }
}

function generateInlineVariantBody(types, schemasDict, tagsDict) {
  return types.map(t => {
    if (typeof t === "object" && t._tag === "Ref") {
      let name = t._0;
      let tagValue = tagsDict[name];
      let tag = tagValue !== undefined ? CodegenHelpers.ucFirst(tagValue) : CodegenHelpers.ucFirst(name);
      let inlineRecord = generateInlineRecord(name, schemasDict);
      return tag + `(` + inlineRecord + `)`;
    }
    let tag$1 = CodegenHelpers.getTagForType(t);
    let payload = generateType(t);
    return tag$1 + `(` + payload + `)`;
  }).join(" | ");
}

function generateVariantBody(types) {
  return types.map(t => {
    let tag = CodegenHelpers.getTagForType(t);
    let payload = generateType(t);
    return tag + `(` + payload + `)`;
  }).join(" | ");
}

function generateTypeDefWithSkipSet(namedSchema, _skipSet, schemasDict, tagsDict) {
  let typeName = CodegenHelpers.lcFirst(namedSchema.name);
  let tagName = Core__Option.getOr(namedSchema.discriminatorPropertyName, "_tag");
  let cases = namedSchema.schema;
  if (typeof cases === "object") {
    switch (cases._tag) {
      case "PolyVariant" :
        let variantBody = cases._0.map(c => {
          let refName = c.payload;
          if (typeof refName === "object" && refName._tag === "Ref") {
            let inlineRecord = generateInlineRecord(refName._0, schemasDict);
            return CodegenHelpers.ucFirst(c._tag) + `(` + inlineRecord + `)`;
          }
          let payloadStr = generateType(c.payload);
          return CodegenHelpers.ucFirst(c._tag) + `(` + payloadStr + `)`;
        }).join(" | ");
        return `@genType
@tag("` + tagName + `")
@schema
type ` + typeName + ` = ` + variantBody;
      case "Union" :
        let types = cases._0;
        if (CodegenHelpers.isPrimitiveOnlyUnion(types)) {
          let variantBody$1 = generateVariantBody(types);
          return `@genType
@tag("` + tagName + `")
@unboxed
@schema
type ` + typeName + ` = ` + variantBody$1;
        }
        let variantBody$2 = generateInlineVariantBody(types, schemasDict, tagsDict);
        return `@genType
@tag("` + tagName + `")
@schema
type ` + typeName + ` = ` + variantBody$2;
    }
  }
  let typeBody = generateType(namedSchema.schema);
  return `@genType
@schema
type ` + typeName + ` = ` + typeBody;
}

function generateTypeDef(namedSchema) {
  let typeName = CodegenHelpers.lcFirst(namedSchema.name);
  let tagName = Core__Option.getOr(namedSchema.discriminatorPropertyName, "_tag");
  let types = namedSchema.schema;
  if (typeof types === "object" && types._tag === "Union") {
    let variantBody = generateVariantBody(types._0);
    return `@genType
@tag("` + tagName + `")
@unboxed
@schema
type ` + typeName + ` = ` + variantBody;
  }
  let annotations = CodegenHelpers.hasUnion(namedSchema.schema) ? "@genType" : "@genType\n@schema";
  let typeBody = generateType(namedSchema.schema);
  return annotations + `
type ` + typeName + ` = ` + typeBody;
}

export {
  generateType,
  generateRecord,
  generatePolyVariant,
  generateUnion,
  generateInlineRecord,
  generateInlineVariantBody,
  generateVariantBody,
  generateTypeDefWithSkipSet,
  generateTypeDef,
}
/* No side effect */
