// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Errors from "./Errors.res.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as CodegenHelpers from "./CodegenHelpers.res.mjs";

function isRefPlusDictUnion(types) {
  if (types.length !== 2) {
    return;
  }
  let hasDict = types.some(t => {
    if (typeof t !== "object") {
      return false;
    }
    if (t._tag !== "Dict") {
      return false;
    }
    let tmp = t._0;
    if (typeof tmp !== "object") {
      return tmp === "String";
    } else {
      return false;
    }
  });
  let refName = Core__Array.findMap(types, t => {
    if (typeof t !== "object" || t._tag !== "Ref") {
      return;
    } else {
      return t._0;
    }
  });
  if (hasDict) {
    return refName;
  }
}

function isPrimitivePlusDictUnion(types) {
  if (types.length !== 2) {
    return;
  }
  let hasDict = types.some(t => {
    if (typeof t !== "object") {
      return false;
    }
    if (t._tag !== "Dict") {
      return false;
    }
    let tmp = t._0;
    if (typeof tmp !== "object") {
      return tmp === "String";
    } else {
      return false;
    }
  });
  let primitiveName = Core__Array.findMap(types, t => {
    if (typeof t === "object") {
      return;
    }
    switch (t) {
      case "String" :
        return "string";
      case "Number" :
        return "float";
      case "Integer" :
        return "int";
      case "Boolean" :
        return "bool";
      default:
        return;
    }
  });
  if (hasDict) {
    return primitiveName;
  }
}

function getUnionName(types) {
  let names = types.map(t => {
    if (typeof t !== "object") {
      switch (t) {
        case "String" :
          return "string";
        case "Number" :
          return "float";
        case "Integer" :
          return "int";
        case "Boolean" :
          return "bool";
        case "Null" :
          return "null";
        default:
          return "unknown";
      }
    } else {
      switch (t._tag) {
        case "Array" :
          return "array";
        case "Ref" :
          return CodegenHelpers.lcFirst(t._0);
        case "Dict" :
          return "dict";
        default:
          return "unknown";
      }
    }
  });
  if (names.length === 0) {
    return "emptyUnion";
  }
  let first = Core__Option.getOr(names[0], "unknown");
  let rest = names.slice(1);
  return first + rest.map(n => "Or" + CodegenHelpers.ucFirst(n)).join("");
}

function extractUnionsFromType(_schema) {
  while (true) {
    let schema = _schema;
    if (typeof schema !== "object") {
      return [];
    }
    switch (schema._tag) {
      case "Object" :
        return schema._0.flatMap(field => extractUnionsFromType(field.type));
      case "Optional" :
      case "Nullable" :
      case "Array" :
      case "Dict" :
        _schema = schema._0;
        continue;
      case "Union" :
        let types = schema._0;
        let match = isRefPlusDictUnion(types);
        if (match !== undefined) {
          return [];
        }
        let name = getUnionName(types);
        return [{
            name: name,
            schema: schema
          }];
      default:
        return [];
    }
  };
}

function extractUnions(_parentName, schema) {
  if (typeof schema !== "object") {
    return [];
  } else if (schema._tag === "Object") {
    return schema._0.flatMap(field => extractUnionsFromType(field.type));
  } else {
    return [];
  }
}

function replaceUnionInType(schema) {
  if (typeof schema !== "object") {
    return schema;
  }
  switch (schema._tag) {
    case "Optional" :
      return {
        _tag: "Optional",
        _0: replaceUnionInType(schema._0)
      };
    case "Nullable" :
      return {
        _tag: "Nullable",
        _0: replaceUnionInType(schema._0)
      };
    case "Object" :
      let newFields = schema._0.map(field => {
        let newType = replaceUnionInType(field.type);
        return {
          name: field.name,
          type: newType,
          required: field.required
        };
      });
      return {
        _tag: "Object",
        _0: newFields
      };
    case "Array" :
      return {
        _tag: "Array",
        _0: replaceUnionInType(schema._0)
      };
    case "Dict" :
      return {
        _tag: "Dict",
        _0: replaceUnionInType(schema._0)
      };
    case "Union" :
      let types = schema._0;
      let refName = isRefPlusDictUnion(types);
      if (refName !== undefined) {
        return {
          _tag: "Ref",
          _0: refName
        };
      } else {
        return {
          _tag: "Ref",
          _0: getUnionName(types)
        };
      }
    default:
      return schema;
  }
}

function replaceUnions(_parentName, schema) {
  if (typeof schema !== "object") {
    return schema;
  }
  if (schema._tag !== "Object") {
    return schema;
  }
  let newFields = schema._0.map(field => {
    let newType = replaceUnionInType(field.type);
    return {
      name: field.name,
      type: newType,
      required: field.required
    };
  });
  return {
    _tag: "Object",
    _0: newFields
  };
}

function getDependencies(_schema) {
  while (true) {
    let schema = _schema;
    if (typeof schema !== "object") {
      return [];
    }
    switch (schema._tag) {
      case "Object" :
        return schema._0.flatMap(f => getDependencies(f.type));
      case "Ref" :
        return [schema._0];
      case "Enum" :
        return [];
      case "PolyVariant" :
        return schema._0.flatMap(c => getDependencies(c.payload));
      case "Optional" :
      case "Nullable" :
      case "Array" :
      case "Dict" :
        _schema = schema._0;
        continue;
      case "Union" :
        return schema._0.flatMap(getDependencies);
    }
  };
}

function topologicalSort(schemas) {
  let schemaMap = {};
  schemas.forEach(s => {
    schemaMap[s.name] = s;
  });
  let deps = {};
  schemas.forEach(s => {
    let refNames = getDependencies(s.schema);
    let validRefs = refNames.filter(name => Core__Option.isSome(schemaMap[name]));
    deps[s.name] = validRefs;
  });
  let outDegree = {};
  schemas.forEach(s => {
    let myDeps = Core__Option.getOr(deps[s.name], []);
    outDegree[s.name] = myDeps.length;
  });
  let reverseDeps = {};
  schemas.forEach(s => {
    reverseDeps[s.name] = [];
  });
  Object.entries(deps).forEach(param => {
    let name = param[0];
    param[1].forEach(refName => {
      let arr = reverseDeps[refName];
      if (arr !== undefined) {
        arr.push(name);
        return;
      }
    });
  });
  let queue = schemas.filter(s => Core__Option.getOr(outDegree[s.name], 0) === 0).map(s => s.name);
  let result = [];
  let visited = {};
  let process = () => {
    while (true) {
      let name = queue.shift();
      if (name === undefined) {
        return;
      }
      if (Core__Option.isNone(visited[name])) {
        visited[name] = true;
        let schema = schemaMap[name];
        if (schema !== undefined) {
          result.push(schema);
        }
        let dependents = reverseDeps[name];
        if (dependents !== undefined) {
          dependents.forEach(depName => {
            let current = Core__Option.getOr(outDegree[depName], 0);
            outDegree[depName] = current - 1 | 0;
            if ((current - 1 | 0) === 0) {
              queue.push(depName);
              return;
            }
          });
        }
      }
      continue;
    };
  };
  process();
  schemas.forEach(s => {
    if (Core__Option.isNone(visited[s.name])) {
      result.push(s);
      return;
    }
  });
  return result;
}

function buildSkipSchemaSet(schemas) {
  let skipSet = {};
  schemas.forEach(s => {
    if (CodegenHelpers.hasUnion(s.schema) || CodegenHelpers.hasUnknown(s.schema)) {
      skipSet[s.name] = true;
      return;
    }
  });
  let changed = {
    contents: true
  };
  while (changed.contents) {
    changed.contents = false;
    schemas.forEach(s => {
      if (!Core__Option.isNone(skipSet[s.name])) {
        return;
      }
      let refs = getDependencies(s.schema);
      let refsSkipSchema = refs.some(refName => Core__Option.isSome(skipSet[refName]));
      if (refsSkipSchema) {
        skipSet[s.name] = true;
        changed.contents = true;
        return;
      }
    });
  };
  return skipSet;
}

function collectUnionWarnings(schemas) {
  let seen = {};
  let warnings = [];
  let findUnions = _schema => {
    while (true) {
      let schema = _schema;
      if (typeof schema !== "object") {
        return [];
      }
      switch (schema._tag) {
        case "Object" :
          return schema._0.flatMap(f => findUnions(f.type));
        case "Optional" :
        case "Nullable" :
        case "Array" :
        case "Dict" :
          _schema = schema._0;
          continue;
        case "Union" :
          return [schema._0];
        default:
          return [];
      }
    };
  };
  schemas.forEach(s => {
    let unions = findUnions(s.schema);
    unions.forEach(types => {
      let unionName = getUnionName(types);
      if (!Core__Option.isNone(seen[unionName])) {
        return;
      }
      seen[unionName] = true;
      let refName = isRefPlusDictUnion(types);
      if (refName !== undefined) {
        warnings.push(`⚠ ` + unionName + `: anyOf without discriminator, simplified to ` + CodegenHelpers.lcFirst(refName));
        return;
      }
      let primName = isPrimitivePlusDictUnion(types);
      if (primName !== undefined) {
        warnings.push(`⚠ ` + unionName + `: anyOf [` + primName + `, Dict] without discriminator, @tag("_tag") may not work at runtime`);
        return;
      }
    });
  });
  return warnings;
}

function validateUnionDiscriminators(schemas) {
  let seen = {};
  let errors = [];
  let schemasDict = {};
  schemas.forEach(s => {
    schemasDict[s.name] = s.schema;
  });
  let tagsDict = {};
  schemas.forEach(s => {
    let tag = s.discriminatorTag;
    if (tag !== undefined) {
      tagsDict[s.name] = tag;
      return;
    }
  });
  let fieldDiscsDict = {};
  schemas.forEach(s => {
    let dict = s.fieldDiscriminators;
    if (dict !== undefined) {
      Object.entries(dict).forEach(param => {
        fieldDiscsDict[param[0]] = param[1];
      });
      return;
    }
  });
  let findUnions = _schema => {
    while (true) {
      let schema = _schema;
      if (typeof schema !== "object") {
        return [];
      }
      switch (schema._tag) {
        case "Object" :
          return schema._0.flatMap(f => findUnions(f.type));
        case "Optional" :
        case "Nullable" :
        case "Array" :
        case "Dict" :
          _schema = schema._0;
          continue;
        case "Union" :
          return [schema._0];
        default:
          return [];
      }
    };
  };
  schemas.forEach(s => {
    let unions = findUnions(s.schema);
    unions.forEach(types => {
      let unionName = getUnionName(types);
      if (!Core__Option.isNone(seen[unionName])) {
        return;
      }
      seen[unionName] = true;
      if (CodegenHelpers.isPrimitiveOnlyUnion(types)) {
        return;
      }
      let match = isRefPlusDictUnion(types);
      if (match !== undefined) {
        return;
      }
      let match$1 = isPrimitivePlusDictUnion(types);
      if (match$1 !== undefined) {
        return;
      }
      if (!Core__Option.isNone(fieldDiscsDict[unionName])) {
        return;
      }
      let allRefsHaveTags = types.every(t => {
        if (typeof t !== "object" || t._tag !== "Ref") {
          return true;
        } else {
          return Core__Option.isSome(tagsDict[t._0]);
        }
      });
      if (!allRefsHaveTags) {
        errors.push(Errors.makeError({
          TAG: "MissingDiscriminator",
          _0: unionName
        }, undefined, "Add discriminator: { propertyName: \"type\" } to the anyOf/oneOf schema, or use the _tag convention with const values", undefined));
        return;
      }
    });
  });
  return errors;
}

export {
  isRefPlusDictUnion,
  isPrimitivePlusDictUnion,
  getUnionName,
  extractUnions,
  extractUnionsFromType,
  replaceUnions,
  replaceUnionInType,
  getDependencies,
  topologicalSort,
  buildSkipSchemaSet,
  collectUnionWarnings,
  validateUnionDiscriminators,
}
/* No side effect */
