// Generated by ReScript, PLEASE EDIT WITH CARE

import * as IRGen from "./IRGen.res.mjs";
import * as Errors from "./Errors.res.mjs";
import * as CodegenShims from "./CodegenShims.res.mjs";
import * as CodegenTypes from "./CodegenTypes.res.mjs";
import * as CodegenHelpers from "./CodegenHelpers.res.mjs";
import * as BackendReScript from "./BackendReScript.res.mjs";
import * as CodegenTransforms from "./CodegenTransforms.res.mjs";

function generateModuleWithDiagnostics(schemas) {
  let irModule = IRGen.generate(schemas);
  if (irModule.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: irModule._0
    };
  }
  let irModule$1 = irModule._0;
  let code = BackendReScript.print(irModule$1);
  return {
    TAG: "Ok",
    _0: {
      code: code,
      warnings: irModule$1.warnings
    }
  };
}

function generateModule(schemas) {
  let result = generateModuleWithDiagnostics(schemas);
  if (result.TAG === "Ok") {
    let result$1 = result._0;
    result$1.warnings.forEach(w => {
      console.log(w);
    });
    return result$1.code;
  }
  result._0.forEach(e => {
    console.error(Errors.formatError(e));
  });
  return "";
}

let lcFirst = CodegenHelpers.lcFirst;

let ucFirst = CodegenHelpers.ucFirst;

let reservedKeywords = CodegenHelpers.reservedKeywords;

let isReservedKeyword = CodegenHelpers.isReservedKeyword;

let isOptionalType = CodegenHelpers.isOptionalType;

let isNullableType = CodegenHelpers.isNullableType;

let getTagForType = CodegenHelpers.getTagForType;

let hasUnion = CodegenHelpers.hasUnion;

let isPrimitiveOnlyUnion = CodegenHelpers.isPrimitiveOnlyUnion;

let isRefPlusDictUnion = CodegenTransforms.isRefPlusDictUnion;

let isPrimitivePlusDictUnion = CodegenTransforms.isPrimitivePlusDictUnion;

let getUnionName = CodegenTransforms.getUnionName;

let getPolyVariantName = CodegenTransforms.getPolyVariantName;

let extractUnions = CodegenTransforms.extractUnions;

let extractUnionsFromType = CodegenTransforms.extractUnionsFromType;

let replaceUnions = CodegenTransforms.replaceUnions;

let replaceUnionInType = CodegenTransforms.replaceUnionInType;

let getDependencies = CodegenTransforms.getDependencies;

let topologicalSort = CodegenTransforms.topologicalSort;

let buildSkipSchemaSet = CodegenTransforms.buildSkipSchemaSet;

let collectUnionWarnings = CodegenTransforms.collectUnionWarnings;

let validateUnionDiscriminators = CodegenTransforms.validateUnionDiscriminators;

let generateType = CodegenTypes.generateType;

let generateTypeDef = CodegenTypes.generateTypeDef;

let generateTypeDefWithSkipSet = CodegenTypes.generateTypeDefWithSkipSet;

let generateVariantBody = CodegenTypes.generateVariantBody;

let generateInlineVariantBody = CodegenTypes.generateInlineVariantBody;

let generateInlineRecord = CodegenTypes.generateInlineRecord;

let generateDictShim = CodegenShims.generateDictShim;

let generateNullableShim = CodegenShims.generateNullableShim;

let generateNullableModule = CodegenShims.generateNullableModule;

export {
  lcFirst,
  ucFirst,
  reservedKeywords,
  isReservedKeyword,
  isOptionalType,
  isNullableType,
  getTagForType,
  hasUnion,
  isPrimitiveOnlyUnion,
  isRefPlusDictUnion,
  isPrimitivePlusDictUnion,
  getUnionName,
  getPolyVariantName,
  extractUnions,
  extractUnionsFromType,
  replaceUnions,
  replaceUnionInType,
  getDependencies,
  topologicalSort,
  buildSkipSchemaSet,
  collectUnionWarnings,
  validateUnionDiscriminators,
  generateType,
  generateTypeDef,
  generateTypeDefWithSkipSet,
  generateVariantBody,
  generateInlineVariantBody,
  generateInlineRecord,
  generateDictShim,
  generateNullableShim,
  generateNullableModule,
  generateModuleWithDiagnostics,
  generateModule,
}
/* No side effect */
