// Generated by ReScript, PLEASE EDIT WITH CARE


function generateField(param) {
  let fieldConfig = param[1];
  let name = param[0];
  let mapper = fieldConfig.mapper;
  let mapping;
  if (mapper !== undefined) {
    mapping = {
      TAG: "Mapper",
      _0: mapper
    };
  } else {
    let s = fieldConfig.source;
    let sourceName = s !== undefined ? s : name;
    mapping = {
      TAG: "Passthrough",
      _0: sourceName
    };
  }
  return {
    name: name,
    typeAnnotation: fieldConfig.type_,
    mapping: mapping
  };
}

function generateModule(param, apiModule) {
  let moduleConfig = param[1];
  let name = param[0];
  let o = moduleConfig.output;
  let output = o !== undefined ? o : name + ".gen.res";
  let sourceType = apiModule + "." + moduleConfig.source;
  let fields = moduleConfig.fields.map(generateField);
  return {
    name: name,
    sourceType: sourceType,
    output: output,
    fields: fields
  };
}

function generate(config, apiModule) {
  return config.modules.map(entry => generateModule(entry, apiModule));
}

export {
  generateField,
  generateModule,
  generate,
}
/* No side effect */
