// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Errors from "./Errors.res.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function parseFieldConfig(name, json) {
  if (typeof json === "object" && json !== null && !Array.isArray(json)) {
    let match = json["type"];
    let exit = 0;
    if (match !== undefined) {
      if (typeof match === "string") {
        let match$1 = json["mapper"];
        let mapper = typeof match$1 === "string" ? match$1 : undefined;
        let match$2 = json["source"];
        let source = typeof match$2 === "string" ? match$2 : undefined;
        return {
          TAG: "Ok",
          _0: [
            name,
            {
              type_: match,
              mapper: mapper,
              source: source
            }
          ]
        };
      }
      exit = 2;
    } else {
      exit = 2;
    }
    if (exit === 2) {
      return {
        TAG: "Error",
        _0: [Errors.makeError({
            TAG: "MissingRequiredField",
            _0: "type"
          }, [
            "fields",
            name
          ], Primitive_option.some(`Field "` + name + `" must have a "type" property`), undefined)]
      };
    }
  }
  return {
    TAG: "Error",
    _0: [Errors.makeError({
        TAG: "InvalidJson",
        _0: `field "` + name + `" must be an object`
      }, [
        "fields",
        name
      ], undefined, undefined)]
  };
}

function parseModuleConfig(name, json) {
  if (typeof json === "object" && json !== null && !Array.isArray(json)) {
    let match = json["source"];
    let exit = 0;
    if (typeof match === "string") {
      let match$1 = json["output"];
      let output = typeof match$1 === "string" ? match$1 : undefined;
      let match$2 = json["fields"];
      let exit$1 = 0;
      if (match$2 !== undefined) {
        if (typeof match$2 === "object" && match$2 !== null && !Array.isArray(match$2)) {
          let entries = Object.entries(match$2);
          let results = entries.map(param => parseFieldConfig(param[0], param[1]));
          let errors = Core__Array.filterMap(results, r => {
            if (r.TAG === "Ok") {
              return;
            } else {
              return r._0;
            }
          }).flat();
          if (errors.length > 0) {
            return {
              TAG: "Error",
              _0: errors
            };
          }
          let fields = Core__Array.filterMap(results, r => {
            if (r.TAG === "Ok") {
              return r._0;
            }
          });
          return {
            TAG: "Ok",
            _0: [
              name,
              {
                source: match,
                output: output,
                fields: fields
              }
            ]
          };
        }
        exit$1 = 3;
      } else {
        exit$1 = 3;
      }
      if (exit$1 === 3) {
        return {
          TAG: "Error",
          _0: [Errors.makeError({
              TAG: "MissingRequiredField",
              _0: "fields"
            }, [
              "modules",
              name
            ], Primitive_option.some(`Module "` + name + `" must have a "fields" object`), undefined)]
        };
      }
    } else {
      exit = 2;
    }
    if (exit === 2) {
      return {
        TAG: "Error",
        _0: [Errors.makeError({
            TAG: "MissingRequiredField",
            _0: "source"
          }, [
            "modules",
            name
          ], Primitive_option.some(`Module "` + name + `" must have a "source" property referencing the API type`), undefined)]
      };
    }
  }
  return {
    TAG: "Error",
    _0: [Errors.makeError({
        TAG: "InvalidJson",
        _0: `module "` + name + `" must be an object`
      }, [
        "modules",
        name
      ], undefined, undefined)]
  };
}

function parse(json) {
  if (typeof json === "object" && json !== null && !Array.isArray(json)) {
    let match = json["modules"];
    let exit = 0;
    if (match !== undefined) {
      if (typeof match === "object" && match !== null && !Array.isArray(match)) {
        let entries = Object.entries(match);
        let results = entries.map(param => parseModuleConfig(param[0], param[1]));
        let errors = Core__Array.filterMap(results, r => {
          if (r.TAG === "Ok") {
            return;
          } else {
            return r._0;
          }
        }).flat();
        if (errors.length > 0) {
          return {
            TAG: "Error",
            _0: errors
          };
        }
        let modules = Core__Array.filterMap(results, r => {
          if (r.TAG === "Ok") {
            return r._0;
          }
        });
        return {
          TAG: "Ok",
          _0: {
            modules: modules
          }
        };
      }
      exit = 2;
    } else {
      exit = 2;
    }
    if (exit === 2) {
      return {
        TAG: "Error",
        _0: [Errors.makeError({
            TAG: "MissingRequiredField",
            _0: "modules"
          }, [], `Config must have a "modules" object`, undefined)]
      };
    }
  }
  return {
    TAG: "Error",
    _0: [Errors.makeError({
        TAG: "InvalidJson",
        _0: "config must be an object"
      }, undefined, undefined, undefined)]
  };
}

export {
  parseFieldConfig,
  parseModuleConfig,
  parse,
}
/* No side effect */
