// DomainBackend.res - Pure printer: DomainIR → ReScript code
// No decisions, only formatting.

let printField = (field: DomainIR.irDomainField): string => {
  `  ${field.name}: ${field.typeAnnotation},`
}

let printType = (module_: DomainIR.irDomainModule): string => {
  let fields = module_.fields->Array.map(printField)->Array.join("\n")
  `type t = {\n${fields}\n}`
}

let printMakeField = (field: DomainIR.irDomainField): string => {
  switch field.mapping {
  | Mapper(fn) => `  ${field.name}: ${fn}(raw),`
  | Passthrough(sourceName) => `  ${field.name}: raw.${sourceName},`
  }
}

let printMake = (module_: DomainIR.irDomainModule): string => {
  let fields = module_.fields->Array.map(printMakeField)->Array.join("\n")
  `let make = (raw: ${module_.sourceType}): t => {\n${fields}\n}`
}

let printModule = (module_: DomainIR.irDomainModule): string => {
  let header = `// ${module_.output} (generated by osury — do not edit)`
  let typeBlock = printType(module_)
  let makeBlock = printMake(module_)
  header ++ "\n\n" ++ typeBlock ++ "\n\n" ++ makeBlock ++ "\n"
}
