// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function makeLocation(pathOpt, param) {
  let path = pathOpt !== undefined ? pathOpt : [];
  return {
    path: path
  };
}

function makeError(kind, pathOpt, hintOpt, param) {
  let path = pathOpt !== undefined ? pathOpt : [];
  let hint = hintOpt !== undefined ? Primitive_option.valFromOption(hintOpt) : undefined;
  return {
    kind: kind,
    location: makeLocation(path, undefined),
    hint: hint
  };
}

function unknownType(value, pathOpt, hintOpt, param) {
  let path = pathOpt !== undefined ? pathOpt : [];
  let hint = hintOpt !== undefined ? Primitive_option.valFromOption(hintOpt) : undefined;
  return makeError({
    TAG: "UnknownType",
    _0: value
  }, path, Primitive_option.some(hint), undefined);
}

function missingField(field, pathOpt, hintOpt, param) {
  let path = pathOpt !== undefined ? pathOpt : [];
  let hint = hintOpt !== undefined ? Primitive_option.valFromOption(hintOpt) : undefined;
  return makeError({
    TAG: "MissingRequiredField",
    _0: field
  }, path, Primitive_option.some(hint), undefined);
}

function invalidRef(ref, pathOpt, hintOpt, param) {
  let path = pathOpt !== undefined ? pathOpt : [];
  let hint = hintOpt !== undefined ? Primitive_option.valFromOption(hintOpt) : undefined;
  return makeError({
    TAG: "InvalidRef",
    _0: ref
  }, path, Primitive_option.some(hint), undefined);
}

function formatError(error) {
  let parts = error.location.path;
  let pathStr = parts.length !== 0 ? "#/" + parts.join("/") : "#";
  let value = error.kind;
  let kindStr;
  switch (value.TAG) {
    case "UnknownType" :
      kindStr = `Unknown type "` + value._0 + `"`;
      break;
    case "MissingRequiredField" :
      kindStr = `Missing required field "` + value._0 + `"`;
      break;
    case "InvalidRef" :
      kindStr = `Invalid reference "` + value._0 + `"`;
      break;
    case "UnsupportedFeature" :
      kindStr = `Unsupported feature "` + value._0 + `"`;
      break;
    case "CircularReference" :
      kindStr = `Circular reference detected: "` + value._0 + `"`;
      break;
    case "MissingDiscriminator" :
      kindStr = `Missing discriminator for union "` + value._0 + `"`;
      break;
    case "DuplicateTypeName" :
      kindStr = `Duplicate type name "` + value._0 + `"`;
      break;
    case "DuplicateConstructor" :
      kindStr = `Union "` + value._0 + `" produces the constructor "` + value._1 + `" more than once`;
      break;
    case "ConflictingInlineEnums" :
      kindStr = `Conflicting inline enums at field "` + value._0 + `" (different value sets on the same field path)`;
      break;
    case "InvalidJson" :
      kindStr = `Invalid JSON: ` + value._0;
      break;
  }
  let hint = error.hint;
  let hintStr = hint !== undefined ? `\n  Hint: ` + hint : "";
  return `Error at ` + pathStr + `:\n  ` + kindStr + hintStr;
}

function formatErrors(errors) {
  return errors.map(formatError).join("\n\n");
}

export {
  makeLocation,
  makeError,
  unknownType,
  missingField,
  invalidRef,
  formatError,
  formatErrors,
}
/* No side effect */
