// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function makeLocation(pathOpt, param) {
  let path = pathOpt !== undefined ? pathOpt : [];
  return {
    path: path
  };
}

function makeError(kind, pathOpt, hintOpt, param) {
  let path = pathOpt !== undefined ? pathOpt : [];
  let hint = hintOpt !== undefined ? Primitive_option.valFromOption(hintOpt) : undefined;
  return {
    kind: kind,
    location: makeLocation(path, undefined),
    hint: hint
  };
}

function unknownType(value, pathOpt, hintOpt, param) {
  let path = pathOpt !== undefined ? pathOpt : [];
  let hint = hintOpt !== undefined ? Primitive_option.valFromOption(hintOpt) : undefined;
  return makeError({
    TAG: "UnknownType",
    _0: value
  }, path, Primitive_option.some(hint), undefined);
}

function missingField(field, pathOpt, hintOpt, param) {
  let path = pathOpt !== undefined ? pathOpt : [];
  let hint = hintOpt !== undefined ? Primitive_option.valFromOption(hintOpt) : undefined;
  return makeError({
    TAG: "MissingRequiredField",
    _0: field
  }, path, Primitive_option.some(hint), undefined);
}

function invalidRef(ref, pathOpt, hintOpt, param) {
  let path = pathOpt !== undefined ? pathOpt : [];
  let hint = hintOpt !== undefined ? Primitive_option.valFromOption(hintOpt) : undefined;
  return makeError({
    TAG: "InvalidRef",
    _0: ref
  }, path, Primitive_option.some(hint), undefined);
}

function formatKind(kind) {
  switch (kind.TAG) {
    case "UnknownType" :
      return `Unknown type "` + kind._0 + `"`;
    case "MissingRequiredField" :
      return `Missing required field "` + kind._0 + `"`;
    case "InvalidRef" :
      return `Invalid reference "` + kind._0 + `"`;
    case "UnsupportedFeature" :
      return `Unsupported feature "` + kind._0 + `"`;
    case "CircularReference" :
      return `Circular reference detected: "` + kind._0 + `"`;
    case "MissingDiscriminator" :
      return `Missing discriminator for union "` + kind._0 + `"`;
    case "DuplicateTypeName" :
      return `Duplicate type name "` + kind._0 + `"`;
    case "DuplicateConstructor" :
      return `Union "` + kind._0 + `" produces the constructor "` + kind._1 + `" more than once`;
    case "ConflictingInlineEnums" :
      return `Conflicting inline enums at field "` + kind._0 + `" (different value sets on the same field path)`;
    case "InvalidJson" :
      return `Invalid JSON: ` + kind._0;
  }
}

function formatPath(location) {
  let parts = location.path;
  if (parts.length !== 0) {
    return "#/" + parts.join("/");
  } else {
    return "#";
  }
}

function formatError(error) {
  let pathStr = formatPath(error.location);
  let kindStr = formatKind(error.kind);
  let hint = error.hint;
  let hintStr = hint !== undefined ? `\n  Hint: ` + hint : "";
  return `Error at ` + pathStr + `:\n  ` + kindStr + hintStr;
}

function formatErrors(errors) {
  return errors.map(formatError).join("\n\n");
}

export {
  makeLocation,
  makeError,
  unknownType,
  missingField,
  invalidRef,
  formatKind,
  formatPath,
  formatError,
  formatErrors,
}
/* No side effect */
