// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Errors from "./Errors.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.mjs";
import * as OpenAPIParser from "./OpenAPIParser.mjs";
import * as CodegenHelpers from "./CodegenHelpers.mjs";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as CodegenTransforms from "./CodegenTransforms.mjs";

function mkTaggedCase(wireTag, payload) {
  let ctor = CodegenTransforms.constructorName(wireTag);
  if (ctor === wireTag) {
    return {
      tag: wireTag,
      asValue: undefined,
      payload: payload
    };
  } else {
    return {
      tag: ctor,
      asValue: wireTag,
      payload: payload
    };
  }
}

function convertType(schema) {
  if (typeof schema !== "object") {
    switch (schema) {
      case "String" :
        return {
          TAG: "Primitive",
          _0: "PString"
        };
      case "Number" :
        return {
          TAG: "Primitive",
          _0: "PFloat"
        };
      case "Integer" :
        return {
          TAG: "Primitive",
          _0: "PInt"
        };
      case "Boolean" :
        return {
          TAG: "Primitive",
          _0: "PBool"
        };
      case "Null" :
        return {
          TAG: "Primitive",
          _0: "PUnit"
        };
      case "Unknown" :
        return "JSON";
    }
  } else {
    switch (schema._tag) {
      case "Optional" :
        return {
          TAG: "Option",
          _0: convertType(schema._0)
        };
      case "Nullable" :
        return {
          TAG: "Nullable",
          _0: convertType(schema._0)
        };
      case "Object" :
        let fields = schema._0;
        if (fields.length === 0) {
          return "JSON";
        } else {
          return {
            TAG: "InlineRecord",
            _0: fields.map(convertField)
          };
        }
      case "Array" :
        return {
          TAG: "Array",
          _0: convertType(schema._0)
        };
      case "Ref" :
        return {
          TAG: "Named",
          _0: CodegenHelpers.lcFirst(schema._0)
        };
      case "Enum" :
        return {
          TAG: "Enum",
          _0: schema._0
        };
      case "PolyVariant" :
        return {
          TAG: "InlineVariant",
          _0: schema._0.map(c => {
            let payload = convertType(c.payload);
            return {
              tag: c._tag,
              asValue: undefined,
              payload: payload
            };
          })
        };
      case "Dict" :
        return {
          TAG: "Dict",
          _0: convertType(schema._0)
        };
      case "Union" :
        return {
          TAG: "InlineVariant",
          _0: schema._0.map(t => {
            let tag = CodegenHelpers.getTagForType(t);
            let payload = convertType(t);
            return {
              tag: tag,
              asValue: undefined,
              payload: payload
            };
          })
        };
      case "AllOf" :
        return "JSON";
      case "Refined" :
        return {
          TAG: "Refined",
          _0: convertType(schema._0),
          _1: schema._1
        };
    }
  }
}

function convertField(field) {
  let baseType = convertType(field.type);
  let wrappedType = field.required || CodegenHelpers.isOptionalType(field.type) ? baseType : ({
      TAG: "Option",
      _0: baseType
    });
  let annotations = [];
  if (CodegenHelpers.isNullableType(field.type)) {
    annotations.push("SNull");
  }
  if (CodegenHelpers.isReservedKeyword(field.name)) {
    annotations.push({
      TAG: "As",
      _0: field.name
    });
  }
  let fieldName = CodegenHelpers.isReservedKeyword(field.name) ? field.name + "_" : field.name;
  return {
    name: fieldName,
    annotations: annotations,
    type_: wrappedType
  };
}

function convertToIrTypeDef(namedSchema, schemasDict, tagsDict, skipSchemaSet, recursiveSet) {
  let typeName = CodegenHelpers.lcFirst(namedSchema.name);
  let tagName = Core__Option.getOr(namedSchema.discriminatorPropertyName, "_tag");
  let shouldSkipSchema = Core__Option.isSome(skipSchemaSet[namedSchema.name]);
  let isRecursive = Core__Option.isSome(recursiveSet[namedSchema.name]);
  let cases = namedSchema.schema;
  let tmp;
  let exit = 0;
  if (typeof cases !== "object") {
    exit = 1;
  } else {
    switch (cases._tag) {
      case "PolyVariant" :
        let isExternal = Primitive_object.equal(namedSchema.variantEncoding, "External");
        let irCases = cases._0.map(c => {
          let refName = c.payload;
          let payload;
          if (typeof refName !== "object" || refName._tag !== "Ref") {
            payload = convertType(refName);
          } else {
            let refName$1 = refName._0;
            let other = schemasDict[refName$1];
            if (other !== undefined) {
              if (typeof other !== "object" || other._tag !== "Object") {
                payload = convertType(other);
              } else {
                let fields = other._0;
                let filtered = isExternal ? fields : fields.filter(f => f.name !== tagName);
                payload = {
                  TAG: "InlineRecord",
                  _0: filtered.map(convertField)
                };
              }
            } else {
              payload = {
                TAG: "Named",
                _0: CodegenHelpers.lcFirst(refName$1)
              };
            }
          }
          return mkTaggedCase(c._tag, payload);
        });
        if (isExternal) {
          tmp = {
            name: typeName,
            annotations: ["GenType"],
            kind: {
              TAG: "VariantDef",
              _0: irCases,
              _1: "ExternalTag"
            }
          };
        } else {
          let baseAnnotations = [
            "GenType",
            {
              TAG: "Tag",
              _0: tagName
            }
          ];
          let annotations = shouldSkipSchema ? baseAnnotations : baseAnnotations.concat(["Schema"]);
          tmp = {
            name: typeName,
            annotations: annotations,
            kind: {
              TAG: "VariantDef",
              _0: irCases,
              _1: {
                TAG: "InternalTag",
                _0: tagName
              }
            }
          };
        }
        break;
      case "Union" :
        let types = cases._0;
        let resolve = name => schemasDict[name];
        if (CodegenHelpers.isPrimitiveOnlyUnion(types) || CodegenHelpers.isShapeDistinctUnion(types, resolve)) {
          let irCases$1 = types.map(t => {
            let tag = CodegenHelpers.getTagForType(t);
            let payload = convertType(t);
            return {
              tag: tag,
              asValue: undefined,
              payload: payload
            };
          });
          let baseAnnotations$1 = [
            "GenType",
            {
              TAG: "Tag",
              _0: tagName
            },
            "Unboxed"
          ];
          let annotations$1 = shouldSkipSchema ? baseAnnotations$1 : baseAnnotations$1.concat(["Schema"]);
          tmp = {
            name: typeName,
            annotations: annotations$1,
            kind: {
              TAG: "VariantDef",
              _0: irCases$1,
              _1: {
                TAG: "InternalTag",
                _0: tagName
              }
            }
          };
        } else {
          let irCases$2 = types.map(t => {
            if (typeof t === "object" && t._tag === "Ref") {
              let name = t._0;
              let wireTag = Core__Option.getOr(tagsDict[name], name);
              let other = schemasDict[name];
              let payload;
              if (other !== undefined) {
                if (typeof other !== "object" || other._tag !== "Object") {
                  payload = convertType(other);
                } else {
                  let filtered = other._0.filter(f => f.name !== tagName);
                  payload = {
                    TAG: "InlineRecord",
                    _0: filtered.map(convertField)
                  };
                }
              } else {
                payload = {
                  TAG: "Named",
                  _0: CodegenHelpers.lcFirst(name)
                };
              }
              return mkTaggedCase(wireTag, payload);
            }
            let tag = CodegenHelpers.getTagForType(t);
            let payload$1 = convertType(t);
            return {
              tag: tag,
              asValue: undefined,
              payload: payload$1
            };
          });
          let baseAnnotations$2 = [
            "GenType",
            {
              TAG: "Tag",
              _0: tagName
            }
          ];
          let annotations$2 = shouldSkipSchema ? baseAnnotations$2 : baseAnnotations$2.concat(["Schema"]);
          tmp = {
            name: typeName,
            annotations: annotations$2,
            kind: {
              TAG: "VariantDef",
              _0: irCases$2,
              _1: {
                TAG: "InternalTag",
                _0: tagName
              }
            }
          };
        }
        break;
      default:
        exit = 1;
    }
  }
  if (exit === 1) {
    let fields = namedSchema.schema;
    let kind;
    if (typeof fields !== "object" || fields._tag !== "Object") {
      kind = {
        TAG: "AliasDef",
        _0: convertType(namedSchema.schema)
      };
    } else {
      let fields$1 = fields._0;
      kind = fields$1.length > 0 ? ({
          TAG: "RecordDef",
          _0: fields$1.map(convertField)
        }) : ({
          TAG: "AliasDef",
          _0: convertType(namedSchema.schema)
        });
    }
    let isListEncoded = Primitive_object.equal(namedSchema.variantEncoding, "List");
    let annotations$3 = isListEncoded ? [
        "GenType",
        "ListEncoded"
      ] : (
        shouldSkipSchema ? ["GenType"] : [
            "GenType",
            "Schema"
          ]
      );
    tmp = {
      name: typeName,
      annotations: annotations$3,
      kind: kind
    };
  }
  if (isRecursive) {
    return {
      name: tmp.name,
      annotations: tmp.annotations.concat(["Recursive"]),
      kind: tmp.kind
    };
  } else {
    return tmp;
  }
}

function ok(schemas) {
  return {
    TAG: "Ok",
    _0: schemas
  };
}

function checking(check, schemas) {
  let errors = check(schemas);
  if (errors.length > 0) {
    return {
      TAG: "Error",
      _0: errors
    };
  } else {
    return {
      TAG: "Ok",
      _0: schemas
    };
  }
}

function normalizeStages(refinements) {
  return [
    {
      name: "validateRefs",
      run: extra => checking(CodegenTransforms.validateRefs, extra)
    },
    {
      name: "mergeAllOf",
      run: CodegenTransforms.mergeAllOf
    },
    {
      name: "stripRefinements",
      run: schemas => ({
        TAG: "Ok",
        _0: refinements ? schemas : CodegenTransforms.stripRefinements(schemas)
      })
    },
    {
      name: "dedupeUnions",
      run: schemas => ({
        TAG: "Ok",
        _0: CodegenTransforms.dedupeUnions(schemas)
      })
    },
    {
      name: "collapseLiteralUnions",
      run: schemas => ({
        TAG: "Ok",
        _0: CodegenTransforms.collapseLiteralUnions(schemas)
      })
    },
    {
      name: "validateUnions",
      run: extra => checking(schemas => CodegenTransforms.validateUnionDiscriminators(schemas).concat(CodegenTransforms.validateDistinctConstructors(schemas)), extra)
    }
  ];
}

function promoteInlineEnums(schemas) {
  let occurrences = CodegenTransforms.collectInlineEnums(schemas);
  let conflicts = CodegenTransforms.findConflictingEnumOccurrences(occurrences);
  if (conflicts.length > 0) {
    return {
      TAG: "Error",
      _0: conflicts.map(occ => {
        let fieldPathStr = occ.fieldPath.join("/");
        return Errors.makeError({
          TAG: "ConflictingInlineEnums",
          _0: fieldPathStr
        }, [occ.parentType].concat(occ.fieldPath), "Union arms mix string literals with structural types, and the literal arms have different value sets. Extract the literals into one named enum ($ref), or split the field into separate properties", undefined);
      })
    };
  }
  let names = CodegenTransforms.resolveEnumNames(occurrences, schemas.map(s => s.name));
  return {
    TAG: "Ok",
    _0: CodegenTransforms.buildExtractedEnumSchemas(occurrences, names).concat(CodegenTransforms.replaceInlineEnums(schemas, names))
  };
}

function extractNamedUnions(schemas) {
  let extracted = schemas.flatMap(s => CodegenTransforms.extractUnions(s.name, s.schema).map(extracted => {
    let dict = s.fieldDiscriminators;
    let discriminatorPropertyName = dict !== undefined ? dict[extracted.name] : undefined;
    return OpenAPIParser.make(extracted.name, extracted.schema, undefined, Primitive_option.some(discriminatorPropertyName), undefined, undefined, undefined);
  }));
  let match = CodegenTransforms.resolveExtractedUnionNames(extracted, schemas.map(s => s.name));
  let unionNames = match[1];
  let replaced = schemas.map(s => ({
    name: s.name,
    schema: CodegenTransforms.replaceUnions(unionNames, s.name, s.schema),
    discriminatorTag: s.discriminatorTag,
    discriminatorPropertyName: s.discriminatorPropertyName,
    fieldDiscriminators: s.fieldDiscriminators,
    variantEncoding: s.variantEncoding
  }));
  return {
    TAG: "Ok",
    _0: match[0].concat(replaced)
  };
}

let expandStages = [
  {
    name: "promoteInlineEnums",
    run: promoteInlineEnums
  },
  {
    name: "extractInlineRecords",
    run: CodegenTransforms.extractInlineRecords
  },
  {
    name: "extractNamedUnions",
    run: extractNamedUnions
  }
];

function runStages(schemas, stages) {
  return Core__Array.reduce(stages, {
    TAG: "Ok",
    _0: schemas
  }, (acc, stage) => {
    if (acc.TAG === "Ok") {
      return stage.run(acc._0);
    } else {
      return acc;
    }
  });
}

function stageNames(refinements) {
  return normalizeStages(refinements).concat(expandStages).map(s => s.name);
}

function encodingWarnings(schemas) {
  return Core__Array.filterMap(schemas, s => {
    let match = s.variantEncoding;
    if (match === undefined) {
      return;
    }
    switch (match) {
      case "Internal" :
        return;
      case "External" :
        return CodegenHelpers.lcFirst(s.name) + `: externally-tagged union — @schema skipped (sury-ppx supports internally-tagged only)`;
      case "List" :
        return CodegenHelpers.lcFirst(s.name) + `: list-encoded enum (["A"] wire form) — @schema skipped (sury-ppx can't express it)`;
    }
  });
}

function generate(schemas, refinementsOpt, param) {
  let refinements = refinementsOpt !== undefined ? refinementsOpt : false;
  let errs = runStages(schemas, normalizeStages(refinements));
  if (errs.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: errs._0
    };
  }
  let normalized = errs._0;
  let warnings = CodegenTransforms.collectUnionWarnings(normalized).concat(encodingWarnings(normalized));
  let errs$1 = runStages(normalized, expandStages);
  if (errs$1.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: errs$1._0
    };
  }
  let allSchemas = errs$1._0;
  let schemasDict = {};
  let tagsDict = {};
  allSchemas.forEach(s => {
    schemasDict[s.name] = s.schema;
    let tag = s.discriminatorTag;
    if (tag !== undefined) {
      tagsDict[s.name] = tag;
      return;
    }
  });
  let skipSchemaSet = CodegenTransforms.buildSkipSchemaSet(allSchemas);
  let recursiveSet = CodegenTransforms.recursiveTypeNames(allSchemas);
  let irTypes = CodegenTransforms.topologicalSort(allSchemas).map(s => convertToIrTypeDef(s, schemasDict, tagsDict, skipSchemaSet, recursiveSet));
  return {
    TAG: "Ok",
    _0: {
      preamble: "",
      types: irTypes,
      warnings: warnings
    }
  };
}

export {
  mkTaggedCase,
  convertType,
  convertField,
  convertToIrTypeDef,
  ok,
  checking,
  normalizeStages,
  promoteInlineEnums,
  extractNamedUnions,
  expandStages,
  runStages,
  stageNames,
  encodingWarnings,
  generate,
}
/* No side effect */
