// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "sury/src/S.mjs";

let aSchema = S.float;

let bSchema = S.string;

let cSchema = S.int;

let dSchema = S.bool;

export {
  aSchema,
  bSchema,
  cSchema,
  dSchema,
}
/* S Not a pure module */
