// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Errors from "./Errors.res.mjs";
import * as Schema from "./Schema.res.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";

function parseDocument(json) {
  if (typeof json === "object" && json !== null && !Array.isArray(json)) {
    let match = json["components"];
    if (match === undefined) {
      return {
        TAG: "Ok",
        _0: []
      };
    }
    let exit = 0;
    if (typeof match === "object" && match !== null && !Array.isArray(match)) {
      let match$1 = match["schemas"];
      if (match$1 === undefined) {
        return {
          TAG: "Ok",
          _0: []
        };
      }
      let exit$1 = 0;
      if (typeof match$1 === "object" && match$1 !== null && !Array.isArray(match$1)) {
        let entries = Object.entries(match$1);
        let results = entries.map(param => {
          let schemaType = Schema.parse(param[1]);
          if (schemaType.TAG === "Ok") {
            return {
              TAG: "Ok",
              _0: {
                name: param[0],
                schema: schemaType._0
              }
            };
          } else {
            return {
              TAG: "Error",
              _0: schemaType._0
            };
          }
        });
        let errors = Core__Array.filterMap(results, r => {
          if (r.TAG === "Ok") {
            return;
          } else {
            return r._0;
          }
        }).flat();
        if (errors.length > 0) {
          return {
            TAG: "Error",
            _0: errors
          };
        }
        let schemas = Core__Array.filterMap(results, r => {
          if (r.TAG === "Ok") {
            return r._0;
          }
        });
        return {
          TAG: "Ok",
          _0: schemas
        };
      }
      exit$1 = 3;
      if (exit$1 === 3) {
        return {
          TAG: "Error",
          _0: [Errors.makeError({
              TAG: "InvalidJson",
              _0: "schemas must be an object"
            }, undefined, undefined, undefined)]
        };
      }
    } else {
      exit = 2;
    }
    if (exit === 2) {
      return {
        TAG: "Error",
        _0: [Errors.makeError({
            TAG: "InvalidJson",
            _0: "components must be an object"
          }, undefined, undefined, undefined)]
      };
    }
  }
  return {
    TAG: "Error",
    _0: [Errors.makeError({
        TAG: "InvalidJson",
        _0: "document must be an object"
      }, undefined, undefined, undefined)]
  };
}

export {
  parseDocument,
}
/* No side effect */
