// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Errors from "./Errors.mjs";
import * as Schema from "./Schema.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.mjs";

function pathToName(path) {
  return path.split("/").filter(s => {
    if (s !== "") {
      return !s.startsWith("{");
    } else {
      return false;
    }
  }).map(segment => segment.split("-").map(part => {
    let first = part.charAt(0).toUpperCase();
    let rest = part.slice(1);
    return first + rest;
  }).join("")).join("");
}

function ucFirst(s) {
  let first = s.charAt(0).toUpperCase();
  let rest = s.slice(1);
  return first + rest;
}

function parsePathResponses(pathsJson) {
  if (typeof pathsJson !== "object" || pathsJson === null || Array.isArray(pathsJson)) {
    return {
      TAG: "Ok",
      _0: []
    };
  }
  let results = Object.entries(pathsJson).flatMap(param => {
    let methodsJson = param[1];
    let path = param[0];
    if (typeof methodsJson === "object" && methodsJson !== null && !Array.isArray(methodsJson)) {
      return Core__Array.filterMap(Object.entries(methodsJson), param => {
        let opJson = param[1];
        let method = param[0];
        let httpMethods = [
          "get",
          "post",
          "put",
          "patch",
          "delete"
        ];
        if (!httpMethods.includes(method)) {
          return;
        }
        if (typeof opJson !== "object" || opJson === null || Array.isArray(opJson)) {
          return;
        }
        let match = opJson["responses"];
        if (match === undefined) {
          return;
        }
        if (typeof match !== "object" || match === null || Array.isArray(match)) {
          return;
        }
        let r = match["200"];
        let responseJson = r !== undefined ? r : match["201"];
        if (responseJson === undefined) {
          return;
        }
        if (typeof responseJson !== "object" || responseJson === null || Array.isArray(responseJson)) {
          return;
        }
        let match$1 = responseJson["content"];
        if (match$1 === undefined) {
          return;
        }
        if (typeof match$1 !== "object" || match$1 === null || Array.isArray(match$1)) {
          return;
        }
        let match$2 = match$1["application/json"];
        if (match$2 === undefined) {
          return;
        }
        if (typeof match$2 !== "object" || match$2 === null || Array.isArray(match$2)) {
          return;
        }
        let schemaJson = match$2["schema"];
        if (schemaJson === undefined) {
          return;
        }
        let name = ucFirst(method) + pathToName(path) + "Response";
        let schemaType = Schema.parse(schemaJson);
        if (schemaType.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: {
              name: name,
              schema: schemaType._0,
              discriminatorTag: undefined,
              discriminatorPropertyName: undefined,
              fieldDiscriminators: undefined,
              variantEncoding: Schema.variantEncodingOfJson(schemaJson)
            }
          };
        } else {
          return {
            TAG: "Error",
            _0: schemaType._0
          };
        }
      });
    } else {
      return [];
    }
  });
  let errors = Core__Array.filterMap(results, r => {
    if (r.TAG === "Ok") {
      return;
    } else {
      return r._0;
    }
  }).flat();
  if (errors.length > 0) {
    return {
      TAG: "Error",
      _0: errors
    };
  }
  let schemas = Core__Array.filterMap(results, r => {
    if (r.TAG === "Ok") {
      return r._0;
    }
  });
  return {
    TAG: "Ok",
    _0: schemas
  };
}

function extractDiscriminatorFromPair(items, discDict) {
  let match = discDict["propertyName"];
  if (match === undefined) {
    return;
  }
  if (typeof match !== "string") {
    return;
  }
  let memberNames = Core__Array.filterMap(items, item => {
    if (typeof item !== "object" || item === null || Array.isArray(item)) {
      return;
    }
    let match = item["$ref"];
    if (match === undefined) {
      return;
    }
    if (typeof match !== "string") {
      return;
    }
    let parts = match.split("/");
    return parts[parts.length - 1 | 0];
  });
  if (memberNames.length < 2) {
    return;
  }
  let lcNames = memberNames.map(n => {
    let first = n.charAt(0).toLowerCase();
    let rest = n.slice(1);
    return first + rest;
  });
  let firstName = Core__Option.getOr(lcNames[0], "unknown");
  let restNames = lcNames.slice(1);
  let unionName = firstName + restNames.map(n => "Or" + ucFirst(n)).join("");
  return [
    unionName,
    match
  ];
}

function extractFieldDiscriminators(schemaJson) {
  let result = {};
  if (typeof schemaJson === "object" && schemaJson !== null && !Array.isArray(schemaJson)) {
    let match = schemaJson["properties"];
    if (typeof match === "object" && match !== null && !Array.isArray(match)) {
      Object.entries(match).forEach(param => {
        let propJson = param[1];
        if (typeof propJson !== "object" || propJson === null || Array.isArray(propJson)) {
          return;
        }
        let match = propJson["anyOf"];
        let directItems;
        let exit = 0;
        if (Array.isArray(match)) {
          directItems = match;
        } else {
          exit = 1;
        }
        if (exit === 1) {
          let match$1 = propJson["oneOf"];
          directItems = Array.isArray(match$1) ? match$1 : undefined;
        }
        let match$2 = propJson["discriminator"];
        let exit$1 = 0;
        if (directItems !== undefined && match$2 !== undefined) {
          if (typeof match$2 === "object" && match$2 !== null && !Array.isArray(match$2)) {
            let match$3 = extractDiscriminatorFromPair(directItems, match$2);
            if (match$3 !== undefined) {
              result[match$3[0]] = match$3[1];
              return;
            } else {
              return;
            }
          }
          exit$1 = 1;
        } else {
          exit$1 = 1;
        }
        if (exit$1 === 1) {
          let match$4 = propJson["items"];
          if (match$4 === undefined) {
            return;
          }
          if (typeof match$4 !== "object" || match$4 === null || Array.isArray(match$4)) {
            return;
          }
          let match$5 = match$4["anyOf"];
          let nestedItems;
          let exit$2 = 0;
          if (Array.isArray(match$5)) {
            nestedItems = match$5;
          } else {
            exit$2 = 2;
          }
          if (exit$2 === 2) {
            let match$6 = match$4["oneOf"];
            nestedItems = Array.isArray(match$6) ? match$6 : undefined;
          }
          let match$7 = match$4["discriminator"];
          if (nestedItems === undefined) {
            return;
          }
          if (match$7 === undefined) {
            return;
          }
          if (typeof match$7 !== "object" || match$7 === null || Array.isArray(match$7)) {
            return;
          }
          let match$8 = extractDiscriminatorFromPair(nestedItems, match$7);
          if (match$8 !== undefined) {
            result[match$8[0]] = match$8[1];
            return;
          } else {
            return;
          }
        }
      });
    }
  }
  return result;
}

function extractDiscriminatorPropertyName(schemaJson) {
  if (typeof schemaJson !== "object" || schemaJson === null || Array.isArray(schemaJson)) {
    return;
  }
  let match = schemaJson["discriminator"];
  if (match === undefined) {
    return;
  }
  if (typeof match !== "object" || match === null || Array.isArray(match)) {
    return;
  }
  let match$1 = match["propertyName"];
  if (typeof match$1 === "string") {
    return match$1;
  }
}

function extractDiscriminatorTag(schemaJson) {
  if (typeof schemaJson !== "object" || schemaJson === null || Array.isArray(schemaJson)) {
    return;
  }
  let match = schemaJson["properties"];
  if (match === undefined) {
    return;
  }
  if (typeof match !== "object" || match === null || Array.isArray(match)) {
    return;
  }
  let match$1 = match["_tag"];
  if (match$1 === undefined) {
    return;
  }
  if (typeof match$1 !== "object" || match$1 === null || Array.isArray(match$1)) {
    return;
  }
  let match$2 = match$1["const"];
  if (typeof match$2 === "string") {
    return match$2;
  }
}

function parseSchemaDict(schemas) {
  let entries = Object.entries(schemas);
  let results = entries.map(param => {
    let schemaJson = param[1];
    let discriminatorTag = extractDiscriminatorTag(schemaJson);
    let discriminatorPropertyName = extractDiscriminatorPropertyName(schemaJson);
    let fieldDiscs = extractFieldDiscriminators(schemaJson);
    let fieldDiscriminators = Object.entries(fieldDiscs).length > 0 ? fieldDiscs : undefined;
    let schemaType = Schema.parse(schemaJson);
    if (schemaType.TAG === "Ok") {
      return {
        TAG: "Ok",
        _0: {
          name: param[0],
          schema: schemaType._0,
          discriminatorTag: discriminatorTag,
          discriminatorPropertyName: discriminatorPropertyName,
          fieldDiscriminators: fieldDiscriminators,
          variantEncoding: Schema.variantEncodingOfJson(schemaJson)
        }
      };
    } else {
      return {
        TAG: "Error",
        _0: schemaType._0
      };
    }
  });
  let errors = Core__Array.filterMap(results, r => {
    if (r.TAG === "Ok") {
      return;
    } else {
      return r._0;
    }
  }).flat();
  if (errors.length > 0) {
    return {
      TAG: "Error",
      _0: errors
    };
  }
  let schemas$1 = Core__Array.filterMap(results, r => {
    if (r.TAG === "Ok") {
      return r._0;
    }
  });
  return {
    TAG: "Ok",
    _0: schemas$1
  };
}

function parseComponentSchemas(componentsJson) {
  if (typeof componentsJson === "object" && componentsJson !== null && !Array.isArray(componentsJson)) {
    let match = componentsJson["schemas"];
    if (match === undefined) {
      return {
        TAG: "Ok",
        _0: []
      };
    }
    let exit = 0;
    if (typeof match === "object" && match !== null && !Array.isArray(match)) {
      return parseSchemaDict(match);
    }
    exit = 2;
    if (exit === 2) {
      return {
        TAG: "Error",
        _0: [Errors.makeError({
            TAG: "InvalidJson",
            _0: "schemas must be an object"
          }, undefined, undefined, undefined)]
      };
    }
  }
  return {
    TAG: "Error",
    _0: [Errors.makeError({
        TAG: "InvalidJson",
        _0: "components must be an object"
      }, undefined, undefined, undefined)]
  };
}

function parseDefsSchemas(doc, key) {
  let match = doc[key];
  if (match === undefined) {
    return {
      TAG: "Ok",
      _0: []
    };
  }
  if (typeof match === "object" && match !== null && !Array.isArray(match)) {
    return parseSchemaDict(match);
  }
  return {
    TAG: "Error",
    _0: [Errors.makeError({
        TAG: "InvalidJson",
        _0: key + ` must be an object`
      }, undefined, undefined, undefined)]
  };
}

function buildParamsObjectJson(params) {
  let properties = {};
  let required = [];
  params.forEach(param => {
    if (typeof param !== "object" || param === null || Array.isArray(param)) {
      return;
    }
    let match = param["in"];
    let location = typeof match === "string" ? match : undefined;
    let isQueryOrPath;
    if (location !== undefined) {
      switch (location) {
        case "path" :
        case "query" :
          isQueryOrPath = true;
          break;
        default:
          isQueryOrPath = false;
      }
    } else {
      isQueryOrPath = false;
    }
    if (!isQueryOrPath) {
      return;
    }
    let match$1 = param["name"];
    let match$2 = param["schema"];
    if (match$1 === undefined) {
      return;
    }
    if (typeof match$1 !== "string") {
      return;
    }
    if (match$2 === undefined) {
      return;
    }
    let cleanSchema;
    cleanSchema = typeof match$2 === "object" && match$2 !== null && !Array.isArray(match$2) ? Object.fromEntries(Object.entries(match$2).filter(param => param[0] !== "default")) : match$2;
    properties[match$1] = cleanSchema;
    let match$3 = param["required"];
    let isRequired = match$3 === true;
    let pathRequired = location === "path";
    if (isRequired || pathRequired) {
      required.push(match$1);
      return;
    }
  });
  if (Object.entries(properties).length === 0) {
    return;
  }
  let obj = {};
  obj["type"] = "object";
  obj["properties"] = properties;
  obj["required"] = required;
  return obj;
}

function parsePathParameters(pathsJson) {
  if (typeof pathsJson !== "object" || pathsJson === null || Array.isArray(pathsJson)) {
    return {
      TAG: "Ok",
      _0: []
    };
  }
  let results = Object.entries(pathsJson).flatMap(param => {
    let methodsJson = param[1];
    let path = param[0];
    if (typeof methodsJson === "object" && methodsJson !== null && !Array.isArray(methodsJson)) {
      return Core__Array.filterMap(Object.entries(methodsJson), param => {
        let opJson = param[1];
        let method = param[0];
        let httpMethods = [
          "get",
          "post",
          "put",
          "patch",
          "delete"
        ];
        if (!httpMethods.includes(method)) {
          return;
        }
        if (typeof opJson !== "object" || opJson === null || Array.isArray(opJson)) {
          return;
        }
        let match = opJson["parameters"];
        if (match === undefined) {
          return;
        }
        if (!Array.isArray(match)) {
          return;
        }
        let objJson = buildParamsObjectJson(match);
        if (objJson === undefined) {
          return;
        }
        let name = ucFirst(method) + pathToName(path) + "Params";
        let schemaType = Schema.parse(objJson);
        if (schemaType.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: {
              name: name,
              schema: schemaType._0,
              discriminatorTag: undefined,
              discriminatorPropertyName: undefined,
              fieldDiscriminators: undefined,
              variantEncoding: undefined
            }
          };
        } else {
          return {
            TAG: "Error",
            _0: schemaType._0
          };
        }
      });
    } else {
      return [];
    }
  });
  let errors = Core__Array.filterMap(results, r => {
    if (r.TAG === "Ok") {
      return;
    } else {
      return r._0;
    }
  }).flat();
  if (errors.length > 0) {
    return {
      TAG: "Error",
      _0: errors
    };
  }
  let schemas = Core__Array.filterMap(results, r => {
    if (r.TAG === "Ok") {
      return r._0;
    }
  });
  return {
    TAG: "Ok",
    _0: schemas
  };
}

function extractAllDiscriminatorMappings(json) {
  let result = {};
  let walk = j => {
    if (Array.isArray(j)) {
      j.forEach(walk);
      return;
    }
    switch (typeof j) {
      case "object" :
        let match = j["oneOf"];
        let match$1 = j["discriminator"];
        if (Array.isArray(match) && typeof match$1 === "object" && match$1 !== null && !Array.isArray(match$1)) {
          let match$2 = match$1["mapping"];
          if (typeof match$2 === "object" && match$2 !== null && !Array.isArray(match$2)) {
            Object.entries(match$2).forEach(param => {
              let refValue = param[1];
              if (typeof refValue !== "string") {
                return;
              }
              let parts = refValue.split("/");
              let schemaName = parts[parts.length - 1 | 0];
              if (schemaName !== undefined) {
                result[schemaName] = param[0];
                return;
              }
            });
          }
        }
        Object.entries(j).forEach(param => walk(param[1]));
        return;
      default:
        return;
    }
  };
  walk(json);
  return result;
}

function rewriteVariantTagsInType(schema, tagByRef) {
  if (typeof schema !== "object") {
    return schema;
  }
  switch (schema._tag) {
    case "Optional" :
      return {
        _tag: "Optional",
        _0: rewriteVariantTagsInType(schema._0, tagByRef)
      };
    case "Nullable" :
      return {
        _tag: "Nullable",
        _0: rewriteVariantTagsInType(schema._0, tagByRef)
      };
    case "Object" :
      return {
        _tag: "Object",
        _0: schema._0.map(f => ({
          name: f.name,
          type: rewriteVariantTagsInType(f.type, tagByRef),
          required: f.required
        }))
      };
    case "Array" :
      return {
        _tag: "Array",
        _0: rewriteVariantTagsInType(schema._0, tagByRef)
      };
    case "PolyVariant" :
      let newCases = schema._0.map(c => {
        let refName = c.payload;
        if (typeof refName !== "object") {
          return {
            _tag: c._tag,
            payload: rewriteVariantTagsInType(refName, tagByRef)
          };
        }
        if (refName._tag !== "Ref") {
          return {
            _tag: c._tag,
            payload: rewriteVariantTagsInType(refName, tagByRef)
          };
        }
        let actualTag = tagByRef[refName._0];
        if (actualTag !== undefined && actualTag !== c._tag) {
          return {
            _tag: actualTag,
            payload: c.payload
          };
        } else {
          return c;
        }
      });
      return {
        _tag: "PolyVariant",
        _0: newCases
      };
    case "Dict" :
      return {
        _tag: "Dict",
        _0: rewriteVariantTagsInType(schema._0, tagByRef)
      };
    case "Union" :
      return {
        _tag: "Union",
        _0: schema._0.map(t => rewriteVariantTagsInType(t, tagByRef))
      };
    default:
      return schema;
  }
}

function resolveRefTagsInPolyVariants(schemas, mappingByRef) {
  let tagByRef = {};
  schemas.forEach(s => {
    let tag = s.discriminatorTag;
    if (tag !== undefined) {
      tagByRef[s.name] = tag;
      return;
    }
  });
  Object.entries(mappingByRef).forEach(param => {
    tagByRef[param[0]] = param[1];
  });
  return schemas.map(s => ({
    name: s.name,
    schema: rewriteVariantTagsInType(s.schema, tagByRef),
    discriminatorTag: s.discriminatorTag,
    discriminatorPropertyName: s.discriminatorPropertyName,
    fieldDiscriminators: s.fieldDiscriminators,
    variantEncoding: s.variantEncoding
  }));
}

function parseDocument(json) {
  if (typeof json === "object" && json !== null && !Array.isArray(json)) {
    let componentsJson = json["components"];
    let componentSchemas = componentsJson !== undefined ? parseComponentSchemas(componentsJson) : ({
        TAG: "Ok",
        _0: []
      });
    let defsSchemas = parseDefsSchemas(json, "$defs");
    let definitionsSchemas = parseDefsSchemas(json, "definitions");
    let pathsJson = json["paths"];
    let pathSchemas = pathsJson !== undefined ? parsePathResponses(pathsJson) : ({
        TAG: "Ok",
        _0: []
      });
    let pathsJson$1 = json["paths"];
    let paramSchemas = pathsJson$1 !== undefined ? parsePathParameters(pathsJson$1) : ({
        TAG: "Ok",
        _0: []
      });
    let mappingByRef = extractAllDiscriminatorMappings(json);
    let exit = 0;
    if (componentSchemas.TAG === "Ok" && defsSchemas.TAG === "Ok" && definitionsSchemas.TAG === "Ok" && pathSchemas.TAG === "Ok") {
      if (paramSchemas.TAG === "Ok") {
        return {
          TAG: "Ok",
          _0: resolveRefTagsInPolyVariants([
            componentSchemas._0,
            defsSchemas._0,
            definitionsSchemas._0,
            pathSchemas._0,
            paramSchemas._0
          ].flat(), mappingByRef)
        };
      }
      exit = 2;
    } else {
      exit = 2;
    }
    if (exit === 2) {
      let errs = Core__Array.filterMap([
        componentSchemas,
        defsSchemas,
        definitionsSchemas,
        pathSchemas,
        paramSchemas
      ], r => {
        if (r.TAG === "Ok") {
          return;
        } else {
          return r._0;
        }
      }).flat();
      return {
        TAG: "Error",
        _0: errs
      };
    }
  }
  return {
    TAG: "Error",
    _0: [Errors.makeError({
        TAG: "InvalidJson",
        _0: "document must be an object"
      }, undefined, undefined, undefined)]
  };
}

export {
  pathToName,
  ucFirst,
  parsePathResponses,
  extractDiscriminatorFromPair,
  extractFieldDiscriminators,
  extractDiscriminatorPropertyName,
  extractDiscriminatorTag,
  parseSchemaDict,
  parseComponentSchemas,
  parseDefsSchemas,
  buildParamsObjectJson,
  parsePathParameters,
  extractAllDiscriminatorMappings,
  rewriteVariantTagsInType,
  resolveRefTagsInPolyVariants,
  parseDocument,
}
/* No side effect */
