// Generated by ReScript, PLEASE EDIT WITH CARE


function buildSchemasDict(schemas) {
  let dict = {};
  schemas.forEach(s => {
    dict[s.name] = s.schema;
  });
  return dict;
}

function generate(schema, schemasDict) {
  if (typeof schema !== "object") {
    switch (schema) {
      case "String" :
        return "sample";
      case "Number" :
        return 3.14;
      case "Integer" :
        return 42;
      case "Boolean" :
        return true;
      case "Null" :
        return null;
    }
  } else {
    switch (schema._tag) {
      case "Optional" :
      case "Nullable" :
        return generate(schema._0, schemasDict);
      case "Array" :
        return [generate(schema._0, schemasDict)];
      case "Dict" : {
        let dict = {};
        dict["key"] = generate(schema._0, schemasDict);
        return dict;
      }
      case "Object" : {
        let dict = {};
        schema._0.forEach(field => {
          dict[field.name] = generate(field.type, schemasDict);
        });
        return dict;
      }
      case "Enum" : {
        let first = schema._0[0];
        if (first !== undefined) {
          return first;
        } else {
          return "";
        }
      }
      case "Ref" : {
        let resolved = schemasDict[schema._0];
        if (resolved !== undefined) {
          return generate(resolved, schemasDict);
        } else {
          let dict = {};
          dict["_ref"] = schema._0;
          return dict;
        }
      }
      case "PolyVariant" : {
        let firstCase = schema._0[0];
        if (firstCase !== undefined) {
          let base = generate(firstCase.payload, schemasDict);
          let baseDict;
          if (typeof base === "object" && base !== null && !Array.isArray(base)) {
            baseDict = base;
          } else {
            baseDict = {};
          }
          baseDict["_tag"] = firstCase._tag;
          return baseDict;
        } else {
          return null;
        }
      }
      case "Union" : {
        let firstType = schema._0[0];
        if (firstType !== undefined) {
          return generate(firstType, schemasDict);
        } else {
          return null;
        }
      }
    }
  }
}

function generateAll(schemas) {
  let dict = buildSchemasDict(schemas);
  let result = {};
  schemas.forEach(s => {
    result[s.name] = generate(s.schema, dict);
  });
  return result;
}

function generateForSchema(schemas, name) {
  let dict = buildSchemasDict(schemas);
  let schema = dict[name];
  if (schema !== undefined) {
    return generate(schema, dict);
  }
}

export {
  buildSchemasDict,
  generate,
  generateAll,
  generateForSchema,
}
/* No side effect */
