// Generated by ReScript, PLEASE EDIT WITH CARE


function buildSchemasDict(schemas) {
  let dict = {};
  schemas.forEach(s => {
    dict[s.name] = s.schema;
  });
  return dict;
}

function generate(_schema, schemasDict) {
  while (true) {
    let schema = _schema;
    if (typeof schema !== "object") {
      switch (schema) {
        case "String" :
          return "sample";
        case "Number" :
          return 3.14;
        case "Integer" :
          return 42;
        case "Boolean" :
          return true;
        case "Null" :
          return null;
      }
    } else {
      switch (schema._tag) {
        case "Optional" :
        case "Nullable" :
          _schema = schema._0;
          continue;
        case "Object" :
          let dict = {};
          schema._0.forEach(field => {
            dict[field.name] = generate(field.type, schemasDict);
          });
          return dict;
        case "Array" :
          return [generate(schema._0, schemasDict)];
        case "Ref" :
          let name = schema._0;
          let resolved = schemasDict[name];
          if (resolved !== undefined) {
            _schema = resolved;
            continue;
          }
          let dict$1 = {};
          dict$1["_ref"] = name;
          return dict$1;
        case "Enum" :
          let v = schema._0[0];
          if (v !== undefined) {
            return v;
          } else {
            return "";
          }
        case "PolyVariant" :
          let variantCase = schema._0[0];
          if (variantCase === undefined) {
            return null;
          }
          let dict$2 = generate(variantCase.payload, schemasDict);
          let baseDict;
          baseDict = typeof dict$2 === "object" && dict$2 !== null && !Array.isArray(dict$2) ? dict$2 : ({});
          baseDict["_tag"] = variantCase._tag;
          return baseDict;
        case "Dict" :
          let dict$3 = {};
          dict$3["key"] = generate(schema._0, schemasDict);
          return dict$3;
        case "Union" :
          let firstType = schema._0[0];
          if (firstType === undefined) {
            return null;
          }
          _schema = firstType;
          continue;
      }
    }
  };
}

function generateAll(schemas) {
  let dict = buildSchemasDict(schemas);
  let result = {};
  schemas.forEach(s => {
    result[s.name] = generate(s.schema, dict);
  });
  return result;
}

function generateForSchema(schemas, name) {
  let dict = buildSchemasDict(schemas);
  let schema = dict[name];
  if (schema !== undefined) {
    return generate(schema, dict);
  }
}

export {
  buildSchemasDict,
  generate,
  generateAll,
  generateForSchema,
}
/* No side effect */
