// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Array from "@rescript/core/src/Core__Array.mjs";

function buildSchemasDict(schemas) {
  let dict = {};
  schemas.forEach(s => {
    dict[s.name] = s.schema;
  });
  return dict;
}

function generate(_schema, schemasDict) {
  while (true) {
    let schema = _schema;
    if (typeof schema !== "object") {
      switch (schema) {
        case "String" :
          return "sample";
        case "Number" :
          return 3.14;
        case "Integer" :
          return 42;
        case "Boolean" :
          return true;
        case "Null" :
        case "Unknown" :
          return null;
      }
    } else {
      switch (schema._tag) {
        case "Optional" :
        case "Nullable" :
          _schema = schema._0;
          continue;
        case "Object" :
          let dict = {};
          schema._0.forEach(field => {
            dict[field.name] = generate(field.type, schemasDict);
          });
          return dict;
        case "Array" :
          return [generate(schema._0, schemasDict)];
        case "Ref" :
          let name = schema._0;
          let resolved = schemasDict[name];
          if (resolved !== undefined) {
            _schema = resolved;
            continue;
          }
          let dict$1 = {};
          dict$1["_ref"] = name;
          return dict$1;
        case "Enum" :
          let v = schema._0[0];
          if (v !== undefined) {
            return v;
          } else {
            return "";
          }
        case "PolyVariant" :
          let variantCase = schema._0[0];
          if (variantCase === undefined) {
            return null;
          }
          let dict$2 = generate(variantCase.payload, schemasDict);
          let baseDict;
          baseDict = typeof dict$2 === "object" && dict$2 !== null && !Array.isArray(dict$2) ? dict$2 : ({});
          baseDict["_tag"] = variantCase._tag;
          return baseDict;
        case "Dict" :
          let dict$3 = {};
          dict$3["key"] = generate(schema._0, schemasDict);
          return dict$3;
        case "Union" :
          let firstType = schema._0[0];
          if (firstType === undefined) {
            return null;
          }
          _schema = firstType;
          continue;
        case "AllOf" :
          let dict$4 = {};
          schema._0.forEach(t => {
            let armDict = generate(t, schemasDict);
            if (typeof armDict !== "object" || armDict === null || Array.isArray(armDict)) {
              return;
            }
            Object.entries(armDict).forEach(param => {
              dict$4[param[0]] = param[1];
            });
          });
          return dict$4;
        case "Refined" :
          return refineSample(generate(schema._0, schemasDict), schema._1);
      }
    }
  };
}

function refineSample(base, refs) {
  let formatSample = Core__Array.findMap(refs, r => {
    if (r._tag !== "Format") {
      return;
    }
    switch (r._0) {
      case "Uuid" :
        return "123e4567-e89b-12d3-a456-426614174000";
      case "Email" :
        return "user@example.com";
      case "Uri" :
        return "https://example.com";
      case "IsoDate" :
        return "2026-01-15";
      case "IsoDateTime" :
        return "2026-01-15T10:30:00.000Z";
      case "IsoTime" :
        return "10:30:00";
      case "Duration" :
        return "P1D";
      case "Ipv4" :
        return "192.0.2.1";
      case "Ipv6" :
        return "2001:db8::1";
      case "Hostname" :
        return "example.com";
    }
  });
  if (formatSample !== undefined) {
    return formatSample;
  } else {
    return Core__Array.reduce(refs, base, (acc, r) => {
      switch (r._tag) {
        case "MinLength" :
          if (typeof acc !== "string") {
            return acc;
          }
          let n = r._0;
          if (acc.length < n) {
            return acc + "x".repeat(n - acc.length | 0);
          } else {
            return acc;
          }
        case "MaxLength" :
          if (typeof acc !== "string") {
            return acc;
          }
          let n$1 = r._0;
          if (acc.length > n$1) {
            return acc.slice(0, n$1);
          } else {
            return acc;
          }
        case "Gte" :
          if (typeof acc !== "number") {
            return acc;
          }
          let n$2 = r._0;
          if (acc < n$2) {
            return n$2;
          } else {
            return acc;
          }
        case "Lte" :
          if (typeof acc !== "number") {
            return acc;
          }
          let n$3 = r._0;
          if (acc > n$3) {
            return n$3;
          } else {
            return acc;
          }
        case "Gt" :
          if (typeof acc !== "number") {
            return acc;
          }
          let n$4 = r._0;
          if (acc <= n$4) {
            return n$4 + 1.0;
          } else {
            return acc;
          }
        case "Lt" :
          if (typeof acc !== "number") {
            return acc;
          }
          let n$5 = r._0;
          if (acc >= n$5) {
            return n$5 - 1.0;
          } else {
            return acc;
          }
        default:
          return acc;
      }
    });
  }
}

function generateAll(schemas) {
  let dict = buildSchemasDict(schemas);
  let result = {};
  schemas.forEach(s => {
    result[s.name] = generate(s.schema, dict);
  });
  return result;
}

function generateForSchema(schemas, name) {
  let dict = buildSchemasDict(schemas);
  let schema = dict[name];
  if (schema !== undefined) {
    return generate(schema, dict);
  }
}

export {
  buildSchemasDict,
  generate,
  refineSample,
  generateAll,
  generateForSchema,
}
/* No side effect */
