// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Errors from "./Errors.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.mjs";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function isNullType(json) {
  if (typeof json !== "object" || json === null || Array.isArray(json)) {
    return false;
  }
  let match = json["type"];
  return match === "null";
}

function extractRefName(refPath) {
  let parts = refPath.split("/");
  return Core__Option.getOr(parts[parts.length - 1 | 0], refPath);
}

function parseEnumValues(arr) {
  let values = Core__Array.filterMap(arr, item => {
    if (typeof item === "string") {
      return item;
    }
  });
  if (values.length === arr.length) {
    return values;
  }
}

function extractTagFromConst(dict) {
  let match = dict["_tag"];
  if (match === undefined) {
    return;
  }
  if (typeof match !== "object" || match === null || Array.isArray(match)) {
    return;
  }
  let match$1 = match["const"];
  if (typeof match$1 === "string") {
    return match$1;
  }
}

function extractTagFromProperty(dict, propertyName) {
  let match = dict[propertyName];
  if (match === undefined) {
    return;
  }
  if (typeof match !== "object" || match === null || Array.isArray(match)) {
    return;
  }
  let match$1 = match["const"];
  if (typeof match$1 === "string") {
    return match$1;
  }
}

function extractDiscriminatorPropertyName(dict) {
  let match = dict["discriminator"];
  if (match === undefined) {
    return;
  }
  if (typeof match !== "object" || match === null || Array.isArray(match)) {
    return;
  }
  let match$1 = match["propertyName"];
  if (typeof match$1 === "string") {
    return match$1;
  }
}

function parseFormat(name) {
  switch (name) {
    case "date" :
      return "IsoDate";
    case "date-time" :
      return "IsoDateTime";
    case "duration" :
      return "Duration";
    case "email" :
      return "Email";
    case "hostname" :
      return "Hostname";
    case "ipv4" :
      return "Ipv4";
    case "ipv6" :
      return "Ipv6";
    case "time" :
      return "IsoTime";
    case "uri" :
    case "url" :
      return "Uri";
    case "uuid" :
      return "Uuid";
    default:
      return;
  }
}

function getInt(dict, key) {
  let match = dict[key];
  if (typeof match === "number") {
    return match | 0;
  }
}

function getFloat(dict, key) {
  let match = dict[key];
  if (typeof match === "number") {
    return match;
  }
}

function collectStringRefinements(dict) {
  let refs = [];
  let match = dict["format"];
  if (typeof match === "string") {
    let f = parseFormat(match);
    if (f !== undefined) {
      refs.push({
        _tag: "Format",
        _0: f
      });
    }
  }
  Core__Option.forEach(getInt(dict, "minLength"), n => {
    refs.push({
      _tag: "MinLength",
      _0: n
    });
  });
  Core__Option.forEach(getInt(dict, "maxLength"), n => {
    refs.push({
      _tag: "MaxLength",
      _0: n
    });
  });
  let match$1 = dict["pattern"];
  if (typeof match$1 === "string") {
    refs.push({
      _tag: "Pattern",
      _0: match$1
    });
  }
  return refs;
}

function collectNumberRefinements(dict) {
  let refs = [];
  let exclusiveMinIsFlag = Primitive_object.equal(dict["exclusiveMinimum"], true);
  let exclusiveMaxIsFlag = Primitive_object.equal(dict["exclusiveMaximum"], true);
  Core__Option.forEach(getFloat(dict, "minimum"), n => {
    refs.push(exclusiveMinIsFlag ? ({
        _tag: "Gt",
        _0: n
      }) : ({
        _tag: "Gte",
        _0: n
      }));
  });
  Core__Option.forEach(getFloat(dict, "maximum"), n => {
    refs.push(exclusiveMaxIsFlag ? ({
        _tag: "Lt",
        _0: n
      }) : ({
        _tag: "Lte",
        _0: n
      }));
  });
  Core__Option.forEach(getFloat(dict, "exclusiveMinimum"), n => {
    refs.push({
      _tag: "Gt",
      _0: n
    });
  });
  Core__Option.forEach(getFloat(dict, "exclusiveMaximum"), n => {
    refs.push({
      _tag: "Lt",
      _0: n
    });
  });
  Core__Option.forEach(getFloat(dict, "multipleOf"), n => {
    refs.push({
      _tag: "MultipleOf",
      _0: n
    });
  });
  return refs;
}

function refine(base, refs) {
  if (refs.length === 0) {
    return base;
  } else {
    return {
      _tag: "Refined",
      _0: base,
      _1: refs
    };
  }
}

function parseSchema(json, path) {
  if (typeof json === "object" && json !== null && !Array.isArray(json)) {
    return parseObject(json, path);
  }
  return {
    TAG: "Error",
    _0: [Errors.makeError({
        TAG: "InvalidJson",
        _0: "expected object"
      }, path, undefined, undefined)]
  };
}

function parsePrimitiveType(dict, path) {
  let match = dict["type"];
  if (match !== undefined) {
    if (Array.isArray(match)) {
      let typeStrings = Core__Array.filterMap(match, t => {
        if (typeof t === "string") {
          return t;
        }
      });
      let hasNull = typeStrings.includes("null");
      let nonNullTypes = typeStrings.filter(t => t !== "null");
      if (!hasNull) {
        return {
          TAG: "Error",
          _0: [Errors.makeError({
              TAG: "UnsupportedFeature",
              _0: "type array without null"
            }, path, undefined, undefined)]
        };
      }
      if (nonNullTypes.length !== 1) {
        return {
          TAG: "Error",
          _0: [Errors.makeError({
              TAG: "InvalidJson",
              _0: "type array must have exactly one non-null type"
            }, path, undefined, undefined)]
        };
      }
      let nonNullType = nonNullTypes[0];
      let newDict = Object.fromEntries(Object.entries(dict).map(param => {
        let k = param[0];
        if (k === "type") {
          return [
            k,
            nonNullType
          ];
        } else {
          return [
            k,
            param[1]
          ];
        }
      }));
      let inner = parsePrimitiveType(newDict, path);
      if (inner.TAG === "Ok") {
        return {
          TAG: "Ok",
          _0: {
            _tag: "Nullable",
            _0: inner._0
          }
        };
      } else {
        return {
          TAG: "Error",
          _0: inner._0
        };
      }
    }
    switch (typeof match) {
      case "string" :
        switch (match) {
          case "array" :
            return parseArrayType(dict, path);
          case "boolean" :
            return {
              TAG: "Ok",
              _0: "Boolean"
            };
          case "integer" :
            return {
              TAG: "Ok",
              _0: refine("Integer", collectNumberRefinements(dict))
            };
          case "null" :
            return {
              TAG: "Ok",
              _0: "Null"
            };
          case "number" :
            return {
              TAG: "Ok",
              _0: refine("Number", collectNumberRefinements(dict))
            };
          case "object" :
            return parseObjectType(dict, path);
          case "string" :
            let match$1 = dict["const"];
            let exit = 0;
            if (match$1 !== undefined) {
              if (typeof match$1 === "string") {
                return {
                  TAG: "Ok",
                  _0: {
                    _tag: "Enum",
                    _0: [match$1]
                  }
                };
              }
              exit = 2;
            } else {
              exit = 2;
            }
            if (exit === 2) {
              let match$2 = dict["enum"];
              if (match$2 === undefined) {
                return {
                  TAG: "Ok",
                  _0: refine("String", collectStringRefinements(dict))
                };
              }
              let exit$1 = 0;
              if (Array.isArray(match$2)) {
                let values = parseEnumValues(match$2);
                if (values !== undefined) {
                  return {
                    TAG: "Ok",
                    _0: {
                      _tag: "Enum",
                      _0: values
                    }
                  };
                } else {
                  return {
                    TAG: "Error",
                    _0: [Errors.makeError({
                        TAG: "InvalidJson",
                        _0: "enum values must be strings"
                      }, path, undefined, undefined)]
                  };
                }
              }
              exit$1 = 3;
              if (exit$1 === 3) {
                return {
                  TAG: "Error",
                  _0: [Errors.makeError({
                      TAG: "InvalidJson",
                      _0: "enum must be an array"
                    }, path, undefined, undefined)]
                };
              }
            }
            break;
          default:
            return {
              TAG: "Error",
              _0: [Errors.unknownType(match, path, undefined, undefined)]
            };
        }
        break;
    }
    return {
      TAG: "Error",
      _0: [Errors.makeError({
          TAG: "InvalidJson",
          _0: "type must be a string or array"
        }, path, undefined, undefined)]
    };
  }
  let match$3 = dict["const"];
  if (typeof match$3 === "string") {
    return {
      TAG: "Ok",
      _0: {
        _tag: "Enum",
        _0: [match$3]
      }
    };
  }
  let match$4 = dict["properties"];
  if (match$4 !== undefined) {
    return parseObjectType(dict, path);
  } else {
    return {
      TAG: "Ok",
      _0: "Unknown"
    };
  }
}

function parseArrayType(dict, path) {
  let itemSchema = dict["items"];
  if (itemSchema === undefined) {
    return {
      TAG: "Error",
      _0: [Errors.missingField("items", path, "array type requires items schema", undefined)]
    };
  }
  let itemType = parseSchema(itemSchema, path.concat(["items"]));
  if (itemType.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        _tag: "Array",
        _0: itemType._0
      }
    };
  } else {
    return {
      TAG: "Error",
      _0: itemType._0
    };
  }
}

function parseAnyOf(items, path, keywordOpt) {
  let keyword = keywordOpt !== undefined ? keywordOpt : "anyOf";
  let hasNull = items.some(isNullType);
  let nonNullItems = items.filter(item => !isNullType(item));
  if (hasNull && nonNullItems.length === 1) {
    let match = nonNullItems[0];
    if (match === undefined) {
      return {
        TAG: "Error",
        _0: [Errors.makeError({
            TAG: "InvalidJson",
            _0: keyword + ` with only null types`
          }, path, undefined, undefined)]
      };
    }
    if (typeof match === "object" && match !== null && !Array.isArray(match)) {
      let innerType = parseObject(match, path.concat([keyword + `[0]`]));
      if (innerType.TAG === "Ok") {
        return {
          TAG: "Ok",
          _0: {
            _tag: "Nullable",
            _0: innerType._0
          }
        };
      } else {
        return {
          TAG: "Error",
          _0: innerType._0
        };
      }
    }
    return {
      TAG: "Error",
      _0: [Errors.makeError({
          TAG: "InvalidJson",
          _0: keyword + ` item must be object`
        }, path, undefined, undefined)]
    };
  }
  if (nonNullItems.length >= 2) {
    let results = nonNullItems.map((item, i) => parseSchema(item, path.concat([keyword + `[` + i.toString() + `]`])));
    let errors = Core__Array.filterMap(results, r => {
      if (r.TAG === "Ok") {
        return;
      } else {
        return r._0;
      }
    }).flat();
    if (errors.length > 0) {
      return {
        TAG: "Error",
        _0: errors
      };
    }
    let types = Core__Array.filterMap(results, r => {
      if (r.TAG === "Ok") {
        return r._0;
      }
    });
    let types$1 = types.some(t => t === "Number") ? types.filter(t => t !== "Integer") : types;
    let inner = types$1.length !== 1 ? ({
        _tag: "Union",
        _0: types$1
      }) : types$1[0];
    return {
      TAG: "Ok",
      _0: hasNull ? ({
          _tag: "Nullable",
          _0: inner
        }) : inner
    };
  }
  if (nonNullItems.length !== 1) {
    return {
      TAG: "Error",
      _0: [Errors.makeError({
          TAG: "InvalidJson",
          _0: keyword + ` must not be empty`
        }, path, undefined, undefined)]
    };
  }
  let item = nonNullItems[0];
  if (item !== undefined) {
    return parseSchema(item, path.concat([keyword + `[0]`]));
  } else {
    return {
      TAG: "Error",
      _0: [Errors.makeError({
          TAG: "InvalidJson",
          _0: keyword + ` must not be empty`
        }, path, undefined, undefined)]
    };
  }
}

function parseObjectType(dict, path) {
  let match = dict["properties"];
  let hasDeclaredFields = typeof match === "object" && match !== null && !Array.isArray(match) ? Object.entries(match).length > 0 : false;
  let valueSchema = dict["additionalProperties"];
  let exit = 0;
  if (valueSchema !== undefined) {
    switch (typeof valueSchema) {
      case "boolean" :
        if (valueSchema) {
          if (!hasDeclaredFields) {
            return {
              TAG: "Ok",
              _0: {
                _tag: "Dict",
                _0: "Unknown"
              }
            };
          }
          exit = 1;
        } else {
          exit = 1;
        }
        break;
      case "object" :
        if (hasDeclaredFields) {
          exit = 1;
        } else {
          let valueType = parseSchema(valueSchema, path.concat(["additionalProperties"]));
          if (valueType.TAG === "Ok") {
            return {
              TAG: "Ok",
              _0: {
                _tag: "Dict",
                _0: valueType._0
              }
            };
          } else {
            return {
              TAG: "Error",
              _0: valueType._0
            };
          }
        }
        break;
      default:
        exit = 1;
    }
  } else {
    exit = 1;
  }
  if (exit === 1) {
    let match$1 = dict["required"];
    let requiredFields = match$1 !== undefined ? (
        Array.isArray(match$1) ? Core__Array.filterMap(match$1, item => {
            if (typeof item === "string") {
              return item;
            }
          }) : []
      ) : [];
    let match$2 = dict["properties"];
    if (match$2 === undefined) {
      return {
        TAG: "Ok",
        _0: {
          _tag: "Object",
          _0: []
        }
      };
    }
    let exit$1 = 0;
    if (typeof match$2 === "object" && match$2 !== null && !Array.isArray(match$2)) {
      let entries = Object.entries(match$2).filter(param => param[0] !== "_tag");
      let results = entries.map(param => {
        let name = param[0];
        let propType = parseSchema(param[1], path.concat([name]));
        if (propType.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: {
              name: name,
              type: propType._0,
              required: requiredFields.includes(name)
            }
          };
        } else {
          return {
            TAG: "Error",
            _0: propType._0
          };
        }
      });
      let errors = Core__Array.filterMap(results, r => {
        if (r.TAG === "Ok") {
          return;
        } else {
          return r._0;
        }
      }).flat();
      if (errors.length > 0) {
        return {
          TAG: "Error",
          _0: errors
        };
      }
      let fields = Core__Array.filterMap(results, r => {
        if (r.TAG === "Ok") {
          return r._0;
        }
      });
      return {
        TAG: "Ok",
        _0: {
          _tag: "Object",
          _0: fields
        }
      };
    }
    exit$1 = 2;
    if (exit$1 === 2) {
      return {
        TAG: "Error",
        _0: [Errors.makeError({
            TAG: "InvalidJson",
            _0: "properties must be an object"
          }, path, undefined, undefined)]
      };
    }
  }
}

function parseAllOf(items, path) {
  let results = items.map((item, i) => parseSchema(item, path.concat([`allOf[` + i.toString() + `]`])));
  let errors = Core__Array.filterMap(results, r => {
    if (r.TAG === "Ok") {
      return;
    } else {
      return r._0;
    }
  }).flat();
  if (errors.length > 0) {
    return {
      TAG: "Error",
      _0: errors
    };
  } else {
    return {
      TAG: "Ok",
      _0: {
        _tag: "AllOf",
        _0: Core__Array.filterMap(results, r => {
          if (r.TAG === "Ok") {
            return r._0;
          }
        })
      }
    };
  }
}

function externalWrapperKey(item) {
  if (typeof item !== "object" || item === null || Array.isArray(item)) {
    return;
  }
  let match = item["$ref"];
  let match$1 = item["properties"];
  let match$2 = item["required"];
  if (match !== undefined) {
    return;
  }
  if (match$1 === undefined) {
    return;
  }
  if (typeof match$1 !== "object" || match$1 === null || Array.isArray(match$1)) {
    return;
  }
  if (match$2 === undefined) {
    return;
  }
  if (!Array.isArray(match$2)) {
    return;
  }
  let keys = Object.keys(match$1);
  let requiredKeys = Core__Array.filterMap(match$2, r => {
    if (typeof r === "string") {
      return r;
    }
  });
  if (keys.length !== 1) {
    return;
  }
  let key = keys[0];
  if (requiredKeys.length !== 1) {
    return;
  }
  let reqKey = requiredKeys[0];
  if (key === reqKey) {
    return key;
  }
}

function detectExternalTagging(items) {
  let keys = Core__Array.filterMap(items, externalWrapperKey);
  if (items.length > 0 && keys.length === items.length) {
    return Object.keys(Object.fromEntries(keys.map(k => [
      k,
      true
    ]))).length === keys.length;
  } else {
    return false;
  }
}

function parseExternalOneOf(items, path) {
  let caseResults = items.map((item, i) => {
    let path$1 = path.concat([`oneOf[` + i.toString() + `]`]);
    let match = externalWrapperKey(item);
    if (typeof item === "object" && item !== null && !Array.isArray(item) && match !== undefined) {
      let match$1 = item["properties"];
      let inner = typeof match$1 === "object" && match$1 !== null && !Array.isArray(match$1) ? match$1[match] : undefined;
      if (inner === undefined) {
        return {
          TAG: "Error",
          _0: [Errors.makeError({
              TAG: "InvalidJson",
              _0: "externally-tagged wrapper has no payload schema"
            }, path$1, undefined, undefined)]
        };
      }
      let payload = parseSchema(inner, path$1.concat([match]));
      if (payload.TAG === "Ok") {
        return {
          TAG: "Ok",
          _0: {
            _tag: match,
            payload: payload._0
          }
        };
      } else {
        return {
          TAG: "Error",
          _0: payload._0
        };
      }
    }
    return {
      TAG: "Error",
      _0: [Errors.makeError({
          TAG: "InvalidJson",
          _0: "oneOf item is not an externally-tagged wrapper"
        }, path$1, undefined, undefined)]
    };
  });
  let errors = Core__Array.filterMap(caseResults, r => {
    if (r.TAG === "Ok") {
      return;
    } else {
      return r._0;
    }
  }).flat();
  if (errors.length > 0) {
    return {
      TAG: "Error",
      _0: errors
    };
  } else {
    return {
      TAG: "Ok",
      _0: {
        _tag: "PolyVariant",
        _0: Core__Array.filterMap(caseResults, r => {
          if (r.TAG === "Ok") {
            return r._0;
          }
        })
      }
    };
  }
}

function hasScalarOneOfItem(items) {
  return items.some(item => {
    if (typeof item === "object" && item !== null && !Array.isArray(item) && Core__Option.isNone(item["$ref"]) && Core__Option.isNone(item["properties"])) {
      return !isNullType(item);
    } else {
      return false;
    }
  });
}

function parseOneOf(items, path, discriminatorPropertyNameOpt) {
  let discriminatorPropertyName = discriminatorPropertyNameOpt !== undefined ? Primitive_option.valFromOption(discriminatorPropertyNameOpt) : undefined;
  let propName = Core__Option.getOr(discriminatorPropertyName, "_tag");
  let caseResults = items.map((item, i) => {
    let path$1 = path.concat([`oneOf[` + i.toString() + `]`]);
    if (typeof item === "object" && item !== null && !Array.isArray(item)) {
      let match = item["$ref"];
      let exit = 0;
      if (match !== undefined) {
        if (typeof match === "string") {
          let name = extractRefName(match);
          return {
            TAG: "Ok",
            _0: {
              _tag: name,
              payload: {
                _tag: "Ref",
                _0: name
              }
            }
          };
        }
        exit = 2;
      } else {
        exit = 2;
      }
      if (exit === 2) {
        let match$1 = item["properties"];
        let exit$1 = 0;
        if (match$1 !== undefined) {
          if (typeof match$1 === "object" && match$1 !== null && !Array.isArray(match$1)) {
            let tag = extractTagFromProperty(match$1, propName);
            if (tag === undefined) {
              return {
                TAG: "Error",
                _0: [Errors.makeError({
                    TAG: "MissingRequiredField",
                    _0: propName + " with const"
                  }, path$1, undefined, undefined)]
              };
            }
            let match$2 = item["required"];
            let requiredFields = match$2 !== undefined ? (
                Array.isArray(match$2) ? Core__Array.filterMap(match$2, i => {
                    if (typeof i === "string") {
                      return i;
                    }
                  }) : []
              ) : [];
            let entries = Object.entries(match$1).filter(param => param[0] !== propName);
            let fieldResults = entries.map(param => {
              let name = param[0];
              let propType = parseSchema(param[1], path$1.concat([name]));
              if (propType.TAG === "Ok") {
                return {
                  TAG: "Ok",
                  _0: {
                    name: name,
                    type: propType._0,
                    required: requiredFields.includes(name)
                  }
                };
              } else {
                return {
                  TAG: "Error",
                  _0: propType._0
                };
              }
            });
            let errors = Core__Array.filterMap(fieldResults, r => {
              if (r.TAG === "Ok") {
                return;
              } else {
                return r._0;
              }
            }).flat();
            if (errors.length > 0) {
              return {
                TAG: "Error",
                _0: errors
              };
            }
            let fields = Core__Array.filterMap(fieldResults, r => {
              if (r.TAG === "Ok") {
                return r._0;
              }
            });
            return {
              TAG: "Ok",
              _0: {
                _tag: tag,
                payload: {
                  _tag: "Object",
                  _0: fields
                }
              }
            };
          }
          exit$1 = 3;
        } else {
          exit$1 = 3;
        }
        if (exit$1 === 3) {
          return {
            TAG: "Error",
            _0: [Errors.makeError({
                TAG: "InvalidJson",
                _0: "oneOf item must have properties"
              }, path$1, undefined, undefined)]
          };
        }
      }
    }
    return {
      TAG: "Error",
      _0: [Errors.makeError({
          TAG: "InvalidJson",
          _0: "oneOf item must be object"
        }, path$1, undefined, undefined)]
    };
  });
  let errors = Core__Array.filterMap(caseResults, r => {
    if (r.TAG === "Ok") {
      return;
    } else {
      return r._0;
    }
  }).flat();
  if (errors.length > 0) {
    return {
      TAG: "Error",
      _0: errors
    };
  }
  let cases = Core__Array.filterMap(caseResults, r => {
    if (r.TAG === "Ok") {
      return r._0;
    }
  });
  return {
    TAG: "Ok",
    _0: {
      _tag: "PolyVariant",
      _0: cases
    }
  };
}

function applyNullable(dict, result) {
  let match = dict["nullable"];
  if (match === undefined) {
    return result;
  }
  if (typeof match !== "boolean") {
    return result;
  }
  if (!match) {
    return result;
  }
  if (result.TAG !== "Ok") {
    return result;
  }
  let t = result._0;
  if (typeof t !== "object" || t._tag !== "Nullable") {
    return {
      TAG: "Ok",
      _0: {
        _tag: "Nullable",
        _0: t
      }
    };
  } else {
    return {
      TAG: "Ok",
      _0: t
    };
  }
}

function parseObject(dict, path) {
  let match = dict["$ref"];
  if (match !== undefined) {
    if (typeof match === "string") {
      return applyNullable(dict, {
        TAG: "Ok",
        _0: {
          _tag: "Ref",
          _0: extractRefName(match)
        }
      });
    }
    return {
      TAG: "Error",
      _0: [Errors.makeError({
          TAG: "InvalidJson",
          _0: "$ref must be a string"
        }, path, undefined, undefined)]
    };
  }
  let match$1 = dict["oneOf"];
  if (match$1 !== undefined) {
    if (Array.isArray(match$1)) {
      if (hasScalarOneOfItem(match$1)) {
        return parseAnyOf(match$1, path, "oneOf");
      }
      let hasNull = match$1.some(isNullType);
      let nonNullItems = match$1.filter(item => !isNullType(item));
      if (hasNull && nonNullItems.length === 1) {
        let match$2 = nonNullItems[0];
        if (match$2 === undefined) {
          return {
            TAG: "Error",
            _0: [Errors.makeError({
                TAG: "InvalidJson",
                _0: "oneOf with only null types"
              }, path, undefined, undefined)]
          };
        }
        let exit = 0;
        if (typeof match$2 === "object" && match$2 !== null && !Array.isArray(match$2)) {
          let innerType = parseObject(match$2, path.concat(["oneOf[0]"]));
          if (innerType.TAG === "Ok") {
            return {
              TAG: "Ok",
              _0: {
                _tag: "Nullable",
                _0: innerType._0
              }
            };
          } else {
            return {
              TAG: "Error",
              _0: innerType._0
            };
          }
        }
        exit = 2;
        if (exit === 2) {
          return {
            TAG: "Error",
            _0: [Errors.makeError({
                TAG: "InvalidJson",
                _0: "oneOf item must be object"
              }, path, undefined, undefined)]
          };
        }
      } else {
        if (hasNull && nonNullItems.length >= 2) {
          let discriminatorPropName = extractDiscriminatorPropertyName(dict);
          let inner = parseOneOf(nonNullItems, path, Primitive_option.some(discriminatorPropName));
          if (inner.TAG === "Ok") {
            return {
              TAG: "Ok",
              _0: {
                _tag: "Nullable",
                _0: inner._0
              }
            };
          } else {
            return {
              TAG: "Error",
              _0: inner._0
            };
          }
        }
        let discriminatorPropName$1 = extractDiscriminatorPropertyName(dict);
        let match$3 = dict["x-variant-encoding"];
        let exit$1 = 0;
        if (typeof match$3 === "string") {
          switch (match$3) {
            case "external" :
              return parseExternalOneOf(match$1, path);
            case "internal" :
              return parseOneOf(match$1, path, Primitive_option.some(discriminatorPropName$1));
            default:
              exit$1 = 2;
          }
        } else {
          exit$1 = 2;
        }
        if (exit$1 === 2) {
          if (Core__Option.isNone(discriminatorPropName$1) && detectExternalTagging(match$1)) {
            return parseExternalOneOf(match$1, path);
          } else {
            return parseOneOf(match$1, path, Primitive_option.some(discriminatorPropName$1));
          }
        }
      }
    }
    return {
      TAG: "Error",
      _0: [Errors.makeError({
          TAG: "InvalidJson",
          _0: "oneOf must be an array"
        }, path, undefined, undefined)]
    };
  }
  let match$4 = dict["allOf"];
  if (match$4 !== undefined) {
    if (Array.isArray(match$4)) {
      return parseAllOf(match$4, path);
    }
    return {
      TAG: "Error",
      _0: [Errors.makeError({
          TAG: "InvalidJson",
          _0: "allOf must be an array"
        }, path, undefined, undefined)]
    };
  }
  let match$5 = dict["anyOf"];
  if (match$5 === undefined) {
    return applyNullable(dict, parsePrimitiveType(dict, path));
  }
  if (Array.isArray(match$5)) {
    return parseAnyOf(match$5, path, undefined);
  }
  return {
    TAG: "Error",
    _0: [Errors.makeError({
        TAG: "InvalidJson",
        _0: "anyOf must be an array"
      }, path, undefined, undefined)]
  };
}

function variantEncodingOfJson(json) {
  if (typeof json !== "object" || json === null || Array.isArray(json)) {
    return;
  }
  let match = json["oneOf"];
  if (Array.isArray(match)) {
    let hasNull = match.some(isNullType);
    let match$1 = json["x-variant-encoding"];
    let exit = 0;
    if (typeof match$1 === "string") {
      switch (match$1) {
        case "external" :
          return "External";
        case "internal" :
          return "Internal";
        case "list" :
          return "List";
        default:
          exit = 2;
      }
    } else {
      exit = 2;
    }
    if (exit === 2) {
      if (!hasNull && Core__Option.isNone(extractDiscriminatorPropertyName(json)) && detectExternalTagging(match)) {
        return "External";
      } else {
        return;
      }
    }
  }
  let match$2 = json["enum"];
  let match$3 = json["x-variant-encoding"];
  if (Array.isArray(match$2) && match$3 === "list") {
    return "List";
  }
}

let parseAt = parseSchema;

function parse(json) {
  return parseSchema(json, []);
}

export {
  isNullType,
  extractRefName,
  parseEnumValues,
  extractTagFromConst,
  extractTagFromProperty,
  extractDiscriminatorPropertyName,
  parseFormat,
  getInt,
  getFloat,
  collectStringRefinements,
  collectNumberRefinements,
  refine,
  parseSchema,
  parsePrimitiveType,
  parseArrayType,
  parseAnyOf,
  parseObjectType,
  parseAllOf,
  externalWrapperKey,
  detectExternalTagging,
  parseExternalOneOf,
  hasScalarOneOfItem,
  parseOneOf,
  applyNullable,
  parseObject,
  variantEncodingOfJson,
  parseAt,
  parse,
}
/* No side effect */
