// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "sury/src/S.mjs";

let floatOrStringSchema = S.union([
  S.schema(s => (s.m(S.float))),
  S.schema(s => (s.m(S.string)))
]);

export {
  floatOrStringSchema,
}
/* floatOrStringSchema Not a pure module */
